modules/cibconfig.py

In case of switch --no-version of crm_diff not available, skip the version information in cib diff.
Skipping the epoch and num_updates information in source and target has the same result as completely skipping the version section in generated diff.

Remove CIB version in case no --no-version.

---

configure.ac

- On debian we enabled multiarch support for pacemaker, and
so the includes install to /usr/include/<triplet_path>/
pacemaker; requiring configure.ac to be updated to include
said path for its search when AC_CHECK_HEADERS is run for 
crm_conf.h.
Change-Id: I8a18dda2229caaf4a398561a0f4e239c9964e239
Signed-off-by: Richard B Winters <rik@mmogp.com>

Fix CFLAGS for supporting triplet paths with pacemaker

---

modules/constants.py
modules/report.py
test/testcases/history.exp
test/testcases/ra.exp

@dmuhamedagic : I rewrote the transition detection so that it would use either of the transition start messages, since I noticed that some transitions only printed the old message (I think this is why we've been missing transitions).
One thing that's a concern is that a lot of transitions will be detected twice, and right now we keep the second, not the first Transition object created. I think we'd want to keep the first, most likely?

high: report: Rewrite transition detection to fix missing transitions

---

modules/cibconfig.py
test/testcases/confbasic.exp
test/testcases/edit.exp
test/unittests/test_bugs.py

In general, constraints should apply to the outer-most container of a resource, not resources that appear in a group, clone or m/s.
Resolves: #101

medium: cibconfig: Warn if constraint applies to container child (bsc#927423) (#101)

---

modules/cibconfig.py
test/testcases/edit
test/testcases/edit.exp
test/unittests/__init__.py
test/unittests/test_bugs.py
test/unittests/test_objset.py
test/unittests/test_parse.py

I'm a bit nervous about this change, so in order to make it stand out a bit I am making it a pull request.
The core problem is this: Pacemaker no longer enforces unique ids for nodes, and remote nodes may have associated resources with the same name as the node.
crmsh, on the other hand, has no notion of scope and has always assumed that ids are globally unique. The bugs resulting from this change may be subtle. All tests are passing, but who knows.

high: cibconfig: Allow node/rsc id collision in _set_update (bsc#948547)

---

doc/crm.8.adoc

Some `<>` brackets were missing.  There may be others which still need to be fixed.

doc: fix some command syntax grammar in the man page

---

modules/ui_node.py
test/testcases/node.exp

crm_attribute -U was deprecated in favour of -N (--node)
N.B. I haven't tested this at all; just going on what @gao-yan told me on IRC.  So please test before merging :-)

[UNTESTED] low: don't use deprecated crm_attribute -U option

---

doc/crm.8.adoc
modules/cibconfig.py
modules/ui_configure.py

This adds a new method called "push" to the "configure load" command of crmsh. This new method differs from replace and update in that it removes configuration lines from the running configuration that are not present in the imported content (file/URL). Similar to the behavior of "configure edit" except that you can specify an import file instead of using an interactive editor.
I've tested this new feature with Pacemaker 1.1.12 + Corosync 2.3.4 and it works as expected, and the current two methods (update and replace) still appear to work as well. Tested the auto-complete function too.
I also fixed the grammar of a line in the help text for "configure load" and provided an example line using "push" for completeness.
--Marc

Add the "push" Method to the "configure load" Command

---

Makefile.am
configure.ac

The fix for Debian which was added to resolve packaging issues is not necessary,  so this pull request offers the commits to remove the respective logic.
- The `AM_CONDITIONAL` added to `configure.ac` is removed
- The extra logic found in `Makefile.am` for setting `--prefix` is removed

Patch queue/remove fix for debian

---

Makefile.am

Do not remove generated docs and manuals which may cause parallel make
issue:
| rm -rf  doc/crm.8.html doc/crmsh_hb_report.8.html doc/crm.8 doc/crmsh_hb_report.8
| .../usr/bin/install: cannot stat 'doc/crm.8.html': No such file or directory
Signed-off-by: Kai Kang <kai.kang@windriver.com>

Makefile.am: do not remove generated docs

---

modules/config.py

Debian and Ubuntu doesn't use the directory /usr/lib64. They switched to
a different directory structure for better multiarch support.
This also fixes a problem where crmsh can't find crmd on recent
Debian/Ubuntu 64bit installations (same as in #67) because the
autodetection doesn't find the correct crm_daemon_dir path
References:
* https://wiki.debian.org/Multiarch/
* https://wiki.ubuntu.com/MultiarchSpec

medium: config: add multiarch support for libdir

---

hb_report/hb_report.in

(N.B. I didn't test this yet.)
If the logs are empty, it could be because the user accidentally chose
the wrong timeframe, e.g. with `"Fri 11 16:41"`, the `11` is parsed as
the year not the date.  So suggest the user checks the timeframe
when they get an empty report.
Also use `grep`'s `-q` option which doesn't hide real errors, and use
`if` rather than `||` in the unlikely case the script is ever invoked with
the `-e` option enabled.
https://bugzilla.suse.com/show_bug.cgi?id=970823

low: hb_report: Suggest user checks timeframe on empty logs (bsc#970823)

---

doc/crm.8.adoc
doc/website-v1/man-1.2.adoc
doc/website-v1/man-2.0.adoc

It seems "timeframe" is deprecated in favour of "limit", so the examples should reflect that.

make history example consistent with timeframe deprecation

---

crmsh/logtime.py

Found the following time formats:
2016-03-23T12:46:59+0100 and
2016-03-23T12:42:00.671293+01:00
The first one wasn't matched by fmt1 in _syslog2node_formats.

low: history: update the syslog format matching

---

crmsh/cibconfig.py
crmsh/cliformat.py
crmsh/constants.py
crmsh/parse.py
crmsh/ui_configure.py
crmsh/xmlutil.py
doc/crm.8.adoc
test/unittests/test_cliformat.py
test/unittests/test_parse.py

For a description of the alerts feature, see http://clusterlabs.org/pipermail/users/2016-April/002762.html
Bugs non-withstanding, the feature should now be fully supported by this PR.

high: parse: Support for event-driven alerts (fate#320855)

---

setup.py

Even though crmsh is not in pypi, I should be to install crm directly from github using pip.
With the current `setup.py` file the packages are installed but the command-line interface isn't.
Using this PR I can install locally using
```
$ cd ~/Projects/github/steenzout/crmsh
$ virtualenv env
$ source env/bin/activate
$ pip install -r requirements.txt
$ python setup.py install
$ which crm
~/Projects/github/steenzout/crmsh/env/bin/crm
```
Demo using my own branch and using pip pointing directly from github:
```
$ cd ~/
$ virtualenv env2
$ source env2/bin/activate
$ pip install -r ~/Projects/github/steenzout/crmsh/requirements.txt
$ pip install -e git+git://github.com/steenzout/crmsh.git@steenzout-setup-scripts#egg=crmsh
$ $ which crm
~/Projects/github/steenzout/crmsh/env2/bin/crm
```

ability to install crmsh using pip

---

crmsh/parse.py

Commits 65fa115874f4fac5020eb4ffda9d8ee6db69dda1 and f971e47e248aee1649c3c04a3a53937bff894149
changed _TARGET_RE from r'([^:]+):$' to r'([\w=-]+):$'. The new regular expression no longer accepts
many character the old one would. One character for example is '.', which could be in the target
name if fully qualified domain names are used for the node names.
If it is more desired to keep the regex restrictive it could be changed to r'([\w=\.-]+):$' to allow '.' but that would still restrict characters which were once allowed but might not be legal in the node name.

parse: Use original _TARGET_RE

---

doc/crm.8.adoc

can not describe this setting example when I obey relaxng rule of Pacemaker .

low: Fix a setting example of the alert to become the error

---

.travis.yml
data-manifest
setup.py
test/evaltest.sh
test/regression.sh
test/testcases/history.excl
test/testcases/history.exp
test/travis-expected-pacemaker-1.1.12.patch
test/travis-tests.sh

Travis runs on Ubuntu trusty, which is limited to Pacemaker 1.1.12. The regression tests are unfortunately somewhat dependent on the Pacemaker version, and tend to follow the latest release. So we have to patch the expected output to match what we get when running against 1.1.12.

dev: Run regression test suite on Travis CI

---

crmsh/ui_configure.py

When I add a new primitive resource and when I want add 'op' to this resource,
I input 'tab' after 'op', but the shell does not give me the hints, for example, "start", "stop" and "monitor"
So, I make the change
Regards,
Xin

give the op's hint when type tab after 'op'

---

crmsh/utils.py

Parsing ps output turns out to be tricky, so
use the /proc filesystem for process discovery
instead.
Fixes: #182

low: utils: Use /proc for process discovery

---

crmsh/bootstrap.py
crmsh/corosync.py

In a two-node cluster, I 've one node configured with open-vswtich:
5: br-fixed: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue
state UNKNOWN group default
inet 192.168.124.88/24 scope global br-fixed
inet 192.168.124.87/24 scope global secondary br-fixed
In this case, if you use unicast, and set both nodelist and bindnetaddr,
corosync will mess up the address in some condition, and Jan Friesse
also pointed that specifiing both bind addr and nodelist is kind of "not
very often used" configuration.
This patch removes bindnetaddr for unicast.

remove bindnetaddr for unicast(bsc#1030437)

---

crmsh/ra.py

lsb, service, stonith and systemd don't have any providers;
so, it shouldn't be completed when type 'tab' after these ra classes.

complete change about 'crm ra list [classes]'

---

crmsh/cibconfig.py
crmsh/cliformat.py
crmsh/parse.py
crmsh/ui_configure.py
doc/crm.8.adoc
test/testcases/commit.exp
test/testcases/confbasic
test/testcases/confbasic.exp
test/testcases/edit.exp
test/unittests/test_cliformat.py

This PR is to support versioned operations recently introduced by [#1127](https://github.com/ClusterLabs/pacemaker/pull/1127).
The syntax is as follows:
```
configure primitive A ocf:pacemaker:Dummy \
op start \
op_params 2: rule #ra-version version:lt 2.0 fake=real \
op_params 1: fake=fake \
op_meta 2: rule #ra-version version:gte 1.0 timeout=40s \
op_meta 1: timeout=20s
```
generates
```
<primitive id="A" class="ocf" provider="pacemaker" type="Dummy">
<operations>
<op name="start" interval="0" id="A-start-0">
<instance_attributes score="2" id="A-start-0-instance_attributes">
<rule score="INFINITY" id="A-start-0-instance_attributes-rule">
<expression attribute="#ra-version" operation="lt" value="2.0" type="version" id="A-start-0-instance_attributes-rule-expression"/>
</rule>
<nvpair …
```

Feature: add versioned operations support

---

crmsh/bootstrap.py
crmsh/ui_cluster.py
doc/crm.8.adoc

(bsc#1045118)
The interactive prompt for a device needs a "diskless" option as well.

high: bootstrap: Add option to enable diskless SBD mode to cluster init

---

crmsh/ui_context.py

Currently, not all the options can be completed by 'Tab', for example:
crm->configure->verify
crm->configure->back
crm->configure->master
crm->cluster->init
Maybe because the subcommand doesn't have completer yet;
Maybe because the subcommand itself is an alias of other command;
This commit will completed all of the options.

medium: ui_context: Make all the options can be completed

---

crmsh/bootstrap.py
crmsh/ui_cluster.py

1) add "delete" alias for "remove" option
2) when given a node name which is not configured in cluster, program will crash
so replace 'nodename' to 'seed_host' can resolve this
3) give a confirm message when remove node
it will be nice hints

low: bootstrap: some patches about cluster remove

---

scripts/health/report.py
utils/crm_clean.py

in crm_clean.py, if the clean request came from scripts:health,
delete all except health-report
in report.py, print workdir after all things done
this came from crmsh github issue #175

low:scripts:health: save health-report when run "crm cluster health"

---

crmsh/command.py

like 'crm cluster geo-init-arbitrator'

medium:command:adjust the 'ls' print width for long option

---

crmsh/ui_cluster.py
doc/crm.8.adoc

* Update /etc/corosync/corosync.conf with the new name on all nodes
* Change the cluster-name property in the CIB
* Reload the corosync configuration on all nodes(use corosync-cmapctl)
other:
* command corosync-cfgtool -R can not reload totem.cluster_name
* I have no idea how to update any references to the cluster name
* this is for the issue #219

medium: ui_cluster: Add cluster rename command

---

crmsh/ui_cluster.py

or the same node name will be completed many times with many "Tab"s

low: ui_cluster: complete node name once when input crm->cluster->remove

---

crmsh/command.py
crmsh/ui_context.py

(Improved cd completion)
* code changes happened just in command:_cd_completer function
* on the root level, complete sublevel names after "cd ":
complete the 'cd' command self
* on the sublevel, complete other sublevel path after "cd ../":
e.g. on the "configure" level, type "cd ../" and "tab", you can get "../cib ../ra ../script ../node" etc.
* complete sublevel names if this sublevel also have some sublevel names:
e.g. type "cd configure/" and "tab", you can get "configure/assist configure/cib configure/ra" etc.
* prevent '..' complete after every tab

low: command: a clear and better way replace for commit 4ac8d4

---

crmsh/bootstrap.py

When run "crm->cluster->join", if peer node doesn't  configured any RA,
there will pop up a error message:
"Call cib_query failed (-6): No such device or address"
Thanks,
xin

low: bootstrap: suppress the error message

---

crmsh/ui_cluster.py

as the bug [1048187](https://bugzilla.suse.com/show_bug.cgi?id=1048187) discussion,
it's a safe way to give user a hints that need to restart service
Regards, 
xin

low: ui_cluster: change cluster name need restart cluster service

---

crmsh/bootstrap.py

e.g. configure two nodes cluster use unicast,
when second node join in the cluster,
because command "cibadmin -Ql --xpath '/cib/status/node_state'" just return one node,
the expected votes not changed to "2"
I think there should be:
1) sync config file(nodelist) after add node
2) reload corosync after init_cluster_local() to apply the nodelist
3) sleep enough time while inquire using "cibadmin":)
BTW: if not do step1 and step2, cibadmin -Ql always return one node

high: bootstrap: expected votes wouldn't update in unicast mode

---

crmsh/bootstrap.py
crmsh/ui_cluster.py
crmsh/ui_context.py

When running crm->cluster->init(or other bootstrap function),
completion makes no sense, it's better to disable it
I think this is a better and clear way against #218 
1) When meet multi_input and ask in bootstrap, still have completion handler, but the handler will complete nothing
2) remove the history item after inputs in bootstrap, because these items cannot use for other crmsh's commands and levels

medium: bootstrap: disable completion and history when running bootstrap

---

crmsh/bootstrap.py
crmsh/corosync.py
crmsh/ui_cluster.py
crmsh/utils.py

1) use "-I" option stand for IPv6 in ui_cluster
2) totem.ip_version should set as "ipv6"
3) choose one interface which has IPv6 address as default values
4) each node must have an uniqe nodeid when using IPv6,
the nodeid came from IPv6 address in default interface
5) for IPv6 network computation, learn from
https://github.com/tehmaze/ipcalc

medium: bootstrap: configure with IPv6(mcast)

---

crmsh/bootstrap.py

so, use status_long and status_done to give the hints
BTW: in join_csync2 function,  #245 can really reduce the rate of csync2 run fail :)

low: bootstrap: join_csync2 may take a long while

---

crmsh/utils.py

so this can get full node list no matter  what the node's status;
based on this, in ui_cluster, do_start/do_stop/do_enable/do_disable can use self.do_run to control all nodes

medium: utils: list_cluster_nodes: read nodes list from cib.xml

---

crmsh/ui_node.py

or crm->node->server will crash when cluster have not configured any nodes or cluster service is not running
and crash message is:
AttributeError: 'NoneType' object has no attribute 'xpath'

low: ui_node: return False when cibdump2elem return None

---

crmsh/utils.py

in #261 , I removed code which use 'crm_node -l'
It's wrong because the contents of cib in ram maybe are different from the cib.xml file
so, it should be use 'crm_node -l' when service is running, and then, read the cib.xml if return code != 0

fix: utils.list_cluster_nodes: use "crm_node -l" first

---

crmsh/bootstrap.py

if don't do this, 
when this is a configured cluster, already have cib.xml, and if user want to reconfigure,
because list_cluster_nodes in corosync.add_node will read the cib.xml,
the add_node function will return and say "already in configuration",
and wouldn't update the nodelist in corosync.conf

fix: bootstrap: remove cib.xml before corosync.add_node

---

crmsh/bootstrap.py
crmsh/corosync.py

1. skip second heartbeat configure when number of local networks < 2
2. bindnetaddrs must be different and the gap between ports must larger than 1
3. give different default value for second configuration
4. IPv4 & IPv6 support

medium: enable adding the second heartbeat line for mcast

---

crmsh/bootstrap.py

It's better stop config process here,
instead of trying to init local cluster

low: bootstrap: give error hints when use sbd without watchdog

---

crmsh/ui_ra.py

When need to show the agent supported by cluster,
grouped by different classes or providers, Tab by Tab,
instead of completing all the agents at one time.
First completion:  agent classes
Second completion: providers of ocf or types of other classes
Last completion:   types of ocf agents

medium: ui_ra: Improve resource agents completion

---

crmsh/ui_corosync.py

* remove node name which already completed
to avoid this situation: diff node1 node1 node1 node1...
* limit completing node number to 2
to avoid this situation: diff node1 node2 node3

low: ui_corosync: adjust for do_diff completer

---

crmsh/ui_corosync.py

like #290, to avoid this situation: push node1 node1 node1 node1...

medium: ui_corosync: adjust do_push's completer

---

crmsh/completers.py
crmsh/ui_context.py

Hi krig,
I have an idea popped when doing bundle work.
"id" is required in many places, 
e.g. in do_primitive, we can replace compl.null to compl.attr_id, 
and stop completing when meeting "id=",
this can make configure process more fluent because compl.attr_id give hints for users:)
But, this can lead errors in test or in hawk, we can make it portable no matter "id=" is used or not.
If this commit make sense, I will continue to do the replace work and port work:)
Regards,
xin

medium: ui_context: Stop completing when an id is required

---

crmsh/command.py
crmsh/ui_context.py

If dont do this, type "ctrl+C" when using "help command" will cause
the term lost curses

low: ui_context: reset term when using "help command+ctrlC"

---

crmsh/ui_configure.py

The crash came from commit 309d2e6 (medium: ui_configure: Replace compl.null to compl.attr_id where an id is required), which will cause IndexError: tuple index out of range

medium: ui_configure: fix crash when no args given

---

crmsh/ui_context.py

For example:
"master" is the alias name of "ms",
input "crm configure master" will not complete, until input a space ' ';
use this commit, "crm configure master" will continue completing after input "Tab"
This can make using crmsh more fluently:)
Regards,
xin

Low: ui_context: Continue completing when input is an alias

---

utils/crm_pkg.py
utils/crm_script.py

bsc#1067823 still not work
apply this commit, some errors disappeared, 
but some strange status shown in wizards page
e.g. I use wizards page to install apache2 and configure vip,
apache2 package can be successfully installed,
the resource group also started successfully,
but some strange status like: b''
b'true\n'
b'"status" already present\n'
shown in page
when I use command line "crm script run apache virtual-ip:id=vip virtual-ip:ip=10.10.10.123 virtual-ip:cidr_netmask=24 install=true id=fs"
it works well

low: utils: convert bytes to str(bsc#1067823)

---

crmsh/ra.py

The fence-agents package added a couple of new attributes:
deprecated: This parameter is no longer recommended
obsoletes: This parameter replaces an older deprecated parameter
This is a small workaround to avoid warning when deprecated
required parameters are not configured.

low: ra: Don't require deprecated parameters (#321)

---

crmsh/ui_configure.py

When inputs like: id=ids, all 'id' words will be stripped

low: ui_configure: fix for 309d2e, remove "id=" in a save way

---

crmsh/cibconfig.py

if use reset, for example, after adding a valid resource and commit it,
without leaving the configure level,
delete completer will not get the id to delete

low: cibconfig: use refresh instead of reset after commit

---

hb_report/utillib.py

return None in print_logseg function will cause ---- TypeError: Can't convert 'NoneType' object to str implicitly

fix: hb_report: return "" to avoid TypeError

---

crmsh/ui_configure.py

to keep code simple and clean,
and to improve _advanced_completer for group/clone/ms resource type

low: ui_configure: use filter_keys replace any_startswith

---

crmsh/cibconfig.py
crmsh/parse.py
doc/crm.8.adoc
test/unittests/test_cliformat.py
test/unittests/test_parse.py

Adds support for new select tag in alert syntax (as of Pacemaker 1.1.17).

Support new alert syntax (#280)

---

crmsh/ui_configure.py

For now, configure->primitive->xxx->@ will not complete rsc template names;
It's better to show them directly:)

low: ui_configure: Complete rsc template correctly

---

crmsh/ui_configure.py

Completer "primitive_complete_complex" does not work for rsc_template

low: ui_configure: enable completer for rsc_template

---

hb_report/hb_report.in
hb_report/utillib.py

If not match any log content in given timeframe for a log file, 
collect this log.info is not necessary.
I will fire a bug if this commit make sense

fix: hb_report: Don't create *.log.info file if not in timespan

---

crmsh/bootstrap.py

Hi krig,
As bin mentioned in #350,
bootstrap should always ask whether to use sbd, even sbd is already configured before.

low: bootstrap: Always ask whether to use sbd

---

crmsh/ui_resource.py
doc/crm.8.adoc
test/testcases/resource
test/testcases/resource.exp
test/unittests/test_resource.py

As of Pacemaker 2.0, refresh now deletes all resource history,
which matches the old behaviour of cleanup.
Cleanup now only cleans up any resource failures.

high: ui_resource: Undeprecate refresh and remove reprobe (bsc#1084736)

---

crmsh/utils.py
hb_report/utillib.py

* encoding utf-8 when open a file
if journal.log include some special characters(ASCII number >=128), UnicodeEncodeError will raise when write to a file(call str2file)
* pacemaker.log should not exclude as HA_LOG
or ha-cluster-bootstrap.log will see as HA_LOG, pacemaker.log will not be collected

high: hbreport: adjustment for hbreport(bsc#1088784)

---

doc/crm.8.adoc

Example marker begin and end lines have to have the same length, but
one place was unbalanced.  Fix it.
The error was caught by asciidoctor, which tends to be picker than
asciidoc.
Signed-off-by: Takashi Iwai <tiwai@suse.de>

doc: Fix unbalanced example marker

---

crmsh/ui_configure.py

In crm configure, when use '\' to input at a new line, prompt string should always
be ">";
But when the input endswith "=" and "Tab", help messages poped, and prompt string
changed to a constants one like "crm(live/Tbw1)configure# "
That looks bad

low: ui_configure: Adjust prompt string after help messages(bsc#1090140)

---

crmsh/bootstrap.py

To make sure that hawk booting process looks like a primary process in the whole bootstrap, 
not like a part of SBD configuration

 low: bootstrap: Strip spaces before some status descriptions

---

crmsh/utils.py

Hello
This PR permits the use of crmsh to configure cluster hosted on GCE.
GCE instances are peculiar because the network interface is configured with a /32 address.
Regards
dud

[crmsh 3] crmsh cluster init : support GCE

---

scripts/init/configure.py
scripts/init/main.yml
scripts/init/verify.py

Hello
I'm using crmsh to setup a cluster on GCP. Unfortunately GCE instances are configured in a pretty unsual way in that VM are all set a /32 IP, that is all LAN-destined trafic goes through the GCP gateway. So we may not configure Corosync to bind on the network address, we have to request it to use the local IP address.
I've noticed that these init scripts are now deprecated in the latest release, so I'd like to know if there is an interest in this code before spending time to port it to the newer init mechanism. If so, let me known what should be reworked or improved.
Regards 
dud

[crmsh 2] crmsh cluster init : support GCE

---

test/run-in-travis.sh

Hi krig:
I create this request because I want the whole Travis-CI return failed status when unittest failed and testcases success

Low: Travis-CI: make sure exit value is not 0 while unittest failed

---

crmsh/bootstrap.py
crmsh/utils.py
test/unittests/test_utils.py

ipaddress is from std library, remove ipcalc code, keep simple and stable

dev: Using ipaddress instead of ipcalc in Python3

---

crmsh/bootstrap.py

ha-cluster-init command has option "-i" to bind ip address to the specific interface,
I use -i option to change the default network address(bindnetaddr in corosync.conf), but it doesn't work

Fix: bootstrap: "-i" option doesn't work(bsc#1103833, bsc#1103834)

---

crmsh/bootstrap.py

Warning message should be shown whether quiet option has been set.

Low: bootstrap: No warning message when using '-q'

---

crmsh/ui_context.py

I found commit #378, to resolve #367, have some problems:
1. commands in ui_cluster like init, join, add, remove, and geo_* already accept "-h" and "--help" option,
#378 will overwrite them
2. var line_list maybe from root level like ["configure", "property", "-h"], its length not always be 2
I can not find a good way to solve this.
So I just focus on the "property" command temporary.

dev: a conservative way for commit 715f27

---

hb_report/utillib.py

Got "STOPPED" flag file in hbreport contents, 
while the cluster is running on this node,
This is because the processes name in pacemaker has been changed
(crmd to pacemaker-controld, but hbreport code still check crmd)

hbreport: process name change for pacemaker 2.0(bsc#1106052)

---

crmsh/ra.py

In the 3.0 branch, the constructor for RAInfo in crmsh/ra.py is missing the exclude_from_completion argument.

Fix missing argument in RAInfo's constructor.

---

crmsh/bootstrap.py

default_networks should be a list, otherwise the string is treated as a list of characters.

Fix incorrect bindnetaddr in corosync.conf (bsc#1103833) (bsc#1103834)

---

crmsh/ui_maintenance.py

This fix ensures that enable/disable actions via the command "crm maintenance" are committed automatically.

auto-commit enabling/disabling maintenance mode for a whole cluster

---

crmsh/cibconfig.py
crmsh/ra.py
data-manifest
test/containerized-regression-tests.sh
test/testcases/acl.exp
test/testcases/bugs.exp
test/testcases/bundle.exp
test/testcases/commit.exp
test/testcases/confbasic.exp
test/testcases/delete.exp
test/testcases/edit.exp
test/testcases/newfeatures.exp
test/testcases/resource.exp
test/testcases/rset.exp
test/unit-tests-in-container.sh
test/unittests/test_cliformat.py

For fence-agents in particular, some parameters were changed from `this-form` to `this_form`.
To combat this, we check if a configured parameter is missing from metadata but its `this_form` is present. In that case, we change the name to the existing parameter.
This patch does not handle the case where both `this_form` and `this-form` are configured.

Fix and test for agent parameters changing from dashed form to underscored form

---

utils/crm_pkg.py

Make sure return type for stdout and stderr is always bytes
or stdout/stderr.decode('utf-8') fails.

low: utils: convert string contstants to bytes

---

crmsh/log_patterns.py

Python 3.7 gives 'FutureWarning: Possible nested set' so
replace any regexp [[] with \[.

dev: log_patterns: fix regexp warning for [[]

---

crmsh/options.py
crmsh/ui_cluster.py

hi krig, 
How about making change like this?
I create this PR because I want to get options value and help info when completing, before this sub-command run("cluster init" command here).
Btw1, maybe putting all sub-command's options in one file is easy to maintain? I don't know exactly.
Btw2, in crmsh, we are using three option parse function: argparse, optparse and getopt(in hbreport),
i think it's better to unify them into one, like argparse? cause optparse is deprecated.

dev: Suggestion: Try to centralize command options in one file

---

crmsh/main.py
crmsh/utils.py

This is from yan's requirement
> Many times when we asked users to provide the output of "crm -d ..." for the purpose of debugging, we'd almost always ask them to also run "date" and tell us the timestamp so that we could later dig into the corresponding specific context of the logs  meanwhile for example from hb_report, rather than getting lost in the dozens of thousands lines of them.
It'd be very convenient if "crm -d" could include a timestamp itself for example at the beginning of the output.

low: msg: add timestamp for DEBUG messages(bsc#1129380)

---

crmsh/utils.py
test/unittests/test_utils.py

The sysconfig parser broke on sysconfig values containing equals.
This commit adds both a fix and tests.

medium: utils: Handle sysconfig values containing = (bsc#1129317)

---

crmsh/parse.py
test/unittests/test_parse.py

Detect illegal ordering of attributes and error out early instead of triggering a more obscure validation error when trying to commit.
Unfortunately there is no way to allow mixing of instance_attributes
with op node attributes, as reconstructing the line-based syntax
from the XML is impossible.
This fix detects when the ordering is illegal and errors out.

medium: parse: op params detect and error ... (bsc#1129210)

---

crmsh/cibconfig.py
crmsh/xmlutil.py

crmsh was passing a sanitized CIB version as the basis for
patches. This works as long as the CIB is already sanitized
(apparently almost always the case) but generates strange
diffs otherwise.

high: cibconfig: Use correct CIB as patch base (bsc#1127716)

---

crmsh/bootstrap.py

> When running 'crm cluster init' to try to configure cluster with mcast,
in  step "Network address to bind to", that is "bindnetaddr" in corosync.conf, when inputting specific IP address which is a real address in local node, crmsh considers it's invalid.
While according to 'man corosync.conf', this way is totally valid.

Fix: bindnetaddr should accept both network and specific IP

---

crmsh/ui_node.py
test/testcases/node
test/testcases/node.exp

Sometimes nodes are in "pending" state which is not really "offline".
But "stonith_admin --confirm" will tell pacemaker the node is down...
So basically we need narrow down the cases that we run
"stonith_admin --confirm" for.

medium: ui_node: Check corosync state before clearstate (bsc#1129702)

---

crmsh/bootstrap.py

1. Fix incorrect bindnetaddr in corosync.conf
2. According to 'man corosync.conf', bindnetaddr should accept both network and specific IP
They also become a problem for 12sp3 after we backporting from master

Improve two issues from crmsh-3.0

---

crmsh/utils.py
test/unittests/test_utils.py

This bug is brought by #433 
logic will double process the comment line,
and will raise the error like `UnboundLocalError: local variable 'matched' referenced before assignment` when configuring sbd using bootstrap

Fix: utils: fix logic for process non comments line(bsc#1145823)

---

crmsh/scripts.py

unittests.test_scripts.test_load_legacy ... /usr/lib/python3/dist-packages/crmsh/scripts.py:431: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.

scripts: fix yaml loader warning

---

crmsh/cibconfig.py
crmsh/xmlutil.py
test/testcases/edit
test/testcases/edit.exp

Rather than retrieving the latest CIB again to pass it to "crm_diff -o",
we should stick with what "self.cib_elem" is originally based on no
matter if there's any new changes from the live CIB in the meantime.
Otherwise there's race condition that the generated CIB diff reverts the
changes made right before.
self.cib_orig should be sanitized with sanitize_cib_for_patching() based
on the original self.cib_elem that hasn't yet been sanitized.

High: cibconfig: Correctly sanitize the original CIB as patch base (bsc#1127716, bsc#1138405)

---

crmsh/cibconfig.py
crmsh/xmlutil.py

Backport of https://github.com/ClusterLabs/crmsh/pull/461 for crmsh-3.0 branch.
Rather than retrieving the latest CIB again to pass it to "crm_diff -o",
we should stick with what "self.cib_elem" is originally based on no
matter if there's any new changes from the live CIB in the meantime.
Otherwise there's race condition that the generated CIB diff reverts the
changes made right before.
self.cib_orig should be sanitized with sanitize_cib_for_patching() based
on the original self.cib_elem that hasn't yet been sanitized.

[crmsh-3.0] High: cibconfig: Correctly sanitize the original CIB as patch base (bsc#1127716, bsc#1138405)

---

crmsh/ui_cluster.py
crmsh/utils.py
doc/crm.8.adoc
test/unittests/test_utils.py

**Assumption:** Two nodes cluster(15sp1-1 and 15sp1-2)
---
**Problem:** For a running two nodes cluster, run `crm cluster run "ls"`, will give this error:
```
ERROR: [15sp1-1]: Exited with error code 255, Error output: The authenticity of host '15sp1-1 (10.10.10.51)' can't be established.
ECDSA key fingerprint is SHA256:gOm0UDlChIQvNXXWn0N+bzVa+yj5Y80krR/i0boe/Z8.
Are you sure you want to continue connecting (yes/no)? 
Host key verification failed.
```
**Suggested Solution:** Add `'StrictHostKeyChecking=no'` ssh_options for parallax
**Related commit:** 2f84449238f0212958813bf5ab5584f75ff47e3b
---
**Problem:** When cluster service is totally stopped, run `crm cluster run "ls" 15sp1-1`, crmsh crashed:
```
ERROR: running cibadmin -Ql: Connection to the CIB manager failed: Transport endpoint …
```

Fix: ui_cluster: Improve crm cluster run command(bsc#1145520)

---

crmsh/bootstrap.py

We should back port this to crmsh-3.0

[crmsh-3.0] Fix: Corosync default ports should be 5405 and 5407(bsc#1066196)

---

crmsh/ui_resource.py
test/testcases/resource
test/testcases/resource.exp

When applying a maintenance attribute, the crmsh asked the user if he wanted to delete the maintenance attribute for those primitives that had a different value. It's more logical however to ask the user if he also wants to delete the maintenance attribute from the primitives that have the same value, because this is exactly the intention - to maintain the group not each primitive separately. Even if the user would like to customize each resource individually, he can answer 'No'.

Dev: ui_resource: ask about ALL primitives when overriding attributes

---

crmsh/bootstrap.py
crmsh/corosync.py
test/unittests/test_corosync.py

I have two nodes, node1 using 'crm cluster init -u' and node2 using 'crm cluster join', it works;
But then I run 'crm cluster stop; crm cluster join' on node2, corosync.conf will become 3 nodes cluster config file, cause node2's ip address appended it again

reject append ipaddress to config file if already have(bsc#1127095, 1127096)

---

crmsh/ui_node.py
crmsh/xmlutil.py
doc/crm.8.adoc
doc/website-v1/man-2.0.adoc
doc/website-v1/man-3.adoc
test/testcases/node
test/testcases/node.exp

The crmsh will change the cib.xml itself, instead of using the crm_attribute when changing the maintenance status of a node. Besides, it will inform the user if there are resources in the maintenance or is-manage mode.

Node do maintenance

---

crmsh/bootstrap.py
crmsh/ui_cluster.py
test/unittests/test_bootstrap.py

Using **--yes/-y** option with **ha-cluster-init** will cause re-generate/overwrite ssh key if ssh key already exists.
That may cause problem or inconvenient for user.
One colleague complain to me that he can not access the node passwordless after configured HA cluster because ssh key changed
I think this is the inconvenient point other user might have
That will cause inconvenient during regression test for #464.
In [.travis.yml](https://github.com/liangxin1300/crmsh/blob/b8198e60405473c3201730adbbc212c17f53930a/.travis.yml#L42), I start two nodes for cluster, another one node for qnetd.
Since both setup cluster and setup qdevice/qnetd need to input password, I deploy ssh key firstly in image ([Dockerfile](https://github.com/liangxin1300/myDockerfiles/blob/0b3d55e110f3d3902e1123032efa91341 …

Low: bootstrap: don't overwrite ssh key if already exists

---

crmsh/ui_configure.py
crmsh/ui_node.py
doc/crm.8.adoc
doc/website-v1/man-2.0.adoc
doc/website-v1/man-3.adoc
test/testcases/confbasic
test/testcases/confbasic.exp

When setting the whole cluster into the maintenance mode by
$ crm configure property maintenance=true
the crmsh will inform the user, that there are already nodes,
clones, groups or primitives that have the maintenance property.

Dev: ui_configure: do_property: ask to remove maintenance from primitives and nodes

---

crmsh/parallax.py
data-manifest
test/unittests/test_parallax.py

crmsh use parallax a lot, recently:
* #464 In qdevice/qnetd TLS certification process, need call remote command and exchange remote key files
* #483  Doing regression test on bootstrap process using python-behave, need call remote command
So we should simplify and provide a standard way to use parallax, to avoid set parallax options and handle the exceptions each time or forget to set something like ssh options

Create class Parallax to simplify using parallax

---

.travis.yml
data-manifest
test/docker_scripts.sh
test/features/bootstrap_init_join_remove.feature
test/features/bootstrap_options.feature
test/features/environment.py
test/features/steps/step_bootstrap.py
test/features/steps/utils.py
test/run-in-travis.sh

* Most of bugs for crmsh, came from bootstrap and hb_report, those two features which are also changed frequently, are lack of functional testing.
* New feature for supporting Qdevice also need functional testing. See #464 
* Existing regression test based on shell is not suitable to implement above two requirements.
* Python-behave is behaviour-driven development, Python style.
Integrated with TravisCI and docker, functional testing for above requirements are easy to implement and maintain.
* This PR is using behave to test basic functionalities of bootstrap;
Drive this PR to merge, as a baseline.
* Apply python-behave on key features of crmsh, like qdevice and hb_report, which are lack of functional testing;
* Apply python-behave on new coming PRs of crmsh for functional testing;
* To …

Doing functional test on bootstrap process using python-behave

---

.travis.yml
crmsh/completers.py
crmsh/ui_resource.py
crmsh/ui_utils.py
crmsh/utils.py
data-manifest
doc/crm.8.adoc
test/features/environment.py
test/features/resource_failcount.feature
test/features/steps/step_implenment.py
test/run-in-travis.sh
test/unittests/test_utils.py

Can't set the resource failcount correctly.
e.g.
Dummy resource `d` failed on monitor on node1, using
`crm resource failcount d show node1`
shows the failcount number
If we want to use this:
`crm resource failcount d set node1 0`
to reset the failcount to zero, it doesn't work 
> from SLE12SP3 and SLE15,  fail-counts are no longer recorded "per resource", instead they are recorded "per resource operation per node". 
> So if to make "crm resource failcount <rsc> set" correctly work again, the interface needs to be completed/extended, for example like:
> crm resource failcount \<rsc\> set \<node\> \<operation\> \<interval\> \<value\>
I changed this set sub-command like this:
`failcount <rsc> set <node> <value> [operation]`
If user want to set the failcount, program fetch the current …

Set resource failcount correctly(bsc#1144241)

---

crmsh/bootstrap.py
crmsh/ui_cluster.py

Both for command line and interactive mode.
For command line:
```
crm cluster init -s /dev/sda1 -s /dev/sdb1
```
For interactive mode:
Prompt string is 
```
Path to storage device (e.g. /dev/disk/by-id/...), or "none", use ";" as separator for multi path
```
use `;` as separator is the same way mentioned in `/etc/sysconfig/sbd`

Dev: bootstrap: support multi disk sbd configure

---

crmsh/bootstrap.py
crmsh/ui_cluster.py

Both for command line and interactive mode.
For command line:
```
crm cluster init -s /dev/sda1 -s /dev/sdb1
```
For interactive mode:
Prompt string is 
```
Path to storage device (e.g. /dev/disk/by-id/...), or "none", use ";" as separator for multi path
```
use `;` as separator is the same way mentioned in `/etc/sysconfig/sbd`

[crmsh-3.0]Feature: bootstrap: support multi disk sbd configure

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

First node configured as unicast, when second node joining, missed the default IP,
got `ERROR: cluster.join: No value for ring0`
Using `pick_default_value` function to provide default value for function `prompt_for_string`
* Make unit test for function `pick_default_value`
* Add `-v` option on `nose` to make unit test results more verbose

[crmsh-3.0]Fix: bootstrap: get default ip correctly when cluster join(bsc#1156319)

---

test/unittests/test_report.py

Backport from #496 
Use current year instead of assuming 2019.

[crmsh-4.1] dev: unittest: fix test_report.py failing in 2020

---

crmsh/bootstrap.py
crmsh/corosync.py
test/unittests/test_corosync.py

This PR is a backport from #422 , since I found that 12sp3 also has the same problem

[crmsh-3.0] reject append ipaddress to config file if already have

---

crmsh/bootstrap.py
crmsh/ui_cluster.py

This PR is improvement for #489 
* Support both '-s device1 -s device2' and '-s 'device1;device2' for command line option
* Improve the logic of code
* Maximum number of SBD device is 3
BTW, this PR need to backport to branch crmsh-3.0 and crmsh-4.1

Improve multi sbd case usability

---

crmsh/bootstrap.py

In non-interactive mode, when peer IP is not in the same network with the join node,
will lead to endless looping

[crmsh-3.0] Dev: bootstrap: avoid endless loop for noninteractive when join

---

crmsh.spec.in

[crmsh-4.1] Fix: crmsh.spec: using mktemp to create tmp file(bsc#1154163)

---

crmsh/main.py
crmsh/ui_cluster.py
data-manifest
test/features/bootstrap_options.feature
test/features/steps/const.py
test/features/steps/step_implenment.py

Hi:
Since `optparse` is **deprecated**, I suggest we should replace it with `argparse`.
There are some differences between `optparse` and `argparse` that should be noticed in replacing:
- in usage message, `optparse` using `%prog` as format specifier, while `argparse` using `%(prog)s`
- `argparse` using `version` in `add_argument` function
- to keep code compatible,  in `argparse`, using `parse_known_arg` instead of `parse_args`
- `optparse` using `add_help_option` while `argparse` using `add_help`
- `optparse` using `disable_interspersed_args` to set parsing to stop on the first non-option.
For example, if don't using `disable_interspersed_args`, `crm cluster init -h` will be parsed as `crm -h` and print `crm` help message;
In `argparse`, we don't have interface …

Dev: replace optparse with argparse

---

hb_report/utillib.py
test/unittests/test_report.py

We ever added this line to collect all process back-traces for helping to analyze a ocfs2 cluster hang problem,but in some actual production environments, there are lots of processes in a cluster node,
this dump operation will take too much time, even bring a short system hang.
Then, we should delete this operation during a generic cluster information collection.

Fix: hb_report: disable dump all tasks stack into dmesg(bsc#1158060)

---

.travis.yml
crmsh/main.py
crmsh/ui_cluster.py
crmsh/utils.py
test/features/bootstrap_bugs.feature

space value like 
```
crm cluster init -i "  "
crm -c " "
crm cluster init --name " "
```
is harmful, should raise `ValueError`

Fix: Not allowed space value for option(bsc#1141976)

---

crmsh/ui_configure.py
data-manifest
doc/crm.8.adoc
test/features/resource_set.feature
test/features/steps/step_implenment.py

Like issue #474 mentioned, it's not convenient for modifying an existing resource op monitor parameter.
Using `edit` can modify it but it's not work if user want to script this process
This PR extend the functionalities of configure.set subcommand, while try to keep compatible, if we want to update/add op parameters for en existing resource, we can do it like this:
```
set vip1.monitor.on-fail ignore
set drbd.monitor.10s.interval 20s
```
usage for configure.set
```
set <path> <value>
path:: id.[op_type.][interval.]name
```
Behave test file is [here](https://github.com/ClusterLabs/crmsh/blob/38047ca78b46164b9f65b8d448cc66e15971b972/test/features/resource_set.feature)
include validation and normal using for configure.set

Feature: configure: make configure.set to update operation

---

crmsh/utils.py

I have found that at least the new AWS instances are not detected with the `detect_cloud` method.
This is the current output: 
```
ec2-user@xarbulu-hana01:~> sudo dmidecode -s system-version
4.2.amazon
```

Low: utils: update detect_cloud pattern for aws

---

crmsh/utils.py
test/unittests/test_utils.py

Backport from #522 and backport unittest from #524

[crmsh-4.1] Low: utils: update detect_cloud pattern for aws

---

crmsh/bootstrap.py
crmsh/corosync.py
crmsh/utils.py
test/features/bootstrap_bugs.feature
test/features/steps/step_implenment.py
test/features/steps/utils.py
test/unittests/test_bootstrap.py
test/unittests/test_corosync.py

While in node join process in udpu mode, we do have restriction that forcing the join node address being the same network with the init node's. Corosync doesn't have such limit, so we should loose this checking.
But, loosing this check may have side effect: for normal/non-cloud environment, corosync might be configured with **crossed** link, in which scenario each node can not see each other after joining.
Take an example for **crossed** link:
```
node1's interface: eth1, eth2
node2's interface: eth1, eth2
node1: use eth1 for corosync
node2: use eth2 for corosync
```
So we should have to check the cluster status during joining. 
**If join node itself is online while can't see init node**, bootstrap on join node will:
1. recover original corosync.conf and sync it to init node
2. stop …

For udpu, don't check join node's ip was in the same network

---

crmsh/bootstrap.py
test/docker_scripts.sh
test/features/qdevice_setup_remove.feature
test/unittests/test_bootstrap.py

Based on https://github.com/LINBIT/csync2/blob/master/doc/csync2.adoc#resolving-a-conflict
Csync2 option -f should be used **after** conflicts happen, not **before**
This PR based on the truth that:
We trust each steps change to configure file **on the bootstrap side**, so we use -f option to win all possible conficts
```
When    Run "echo "# This is test for bsc#1166684" >> /etc/corosync/corosync.conf" on "hanode1"
When    Run "scp /etc/corosync/corosync.conf root@hanode2:/etc/corosync" on "hanode1"
```
These two lines added after two-nodes cluster started.
Means change the corosync.conf manually, so csync2 db not aware the change.
Then next functional test try to setup qdevice on the running cluster.
Command `csync -rxv /etc/corosync/corosync.conf` will failed.
Now use '-f' option to …

Resolve csync2 conflicts(bsc#1166684)

---

crmsh/bootstrap.py

In some network scenarios, there is no default route configured.
In that environment, when specifying interface while running `crm cluster init -i nic`, running `ssh_remote` and `csync2_remote` stages will fail as `Failed to determine default network interface`, because internally, bootstrap program try to find default network interface through route
Binding interface when calling "crm cluster init" in `ssh_remote` and `csync2_remote` stages can avoid such issue happened

Dev: bootstrap: binding interface when calling "crm cluster init" internally

---

crmsh/bootstrap.py

`stonith-sbd` resource should not be added unless sbd is configured and sbd device be specified by '-s' option

Fix: bootstrap: Change condition to add stonith-sbd resource

---

.travis.yml
crmsh/corosync.py
crmsh/ui_cluster.py
data-manifest
test/docker_scripts.sh
test/features/qdevice_setup_remove.feature
test/features/qdevice_usercase.feature
test/features/qdevice_validate.feature
test/features/steps/const.py
test/features/steps/step_implenment.py
test/unittests/test_corosync.py

The work of this pull request was based on #464 
- Check whether corosync-qdevice installed
- Check whether corosync-qnetd installed
- All qdevice related options require --qnetd-hostname
- Add --qdevice-heuristics-mode option to configure heuristics mode
- Make qdevice related options as a separate argparse group
- Test master survive scenarios using behave
- Complete unit test and functional test
- **Check whether corosync-qdevice installed**
```
crm cluster init -y --qnetd-hostname=10.10.10.53
ERROR: cluster.init: Package "corosync-qdevice" not installed on this node
```
- **Check whether corosync-qnetd installed**
When valid qnetd raise ValueError, give specific suggestion
```
crm cluster init -y --qnetd-hostname=10.10.10.53
WARNING: chronyd.service is not configured …
```

Qdevice configure process improve

---

crmsh/ui_context.py
test/crm-interface
test/features/bootstrap_bugs.feature
test/testcases/bugs.exp
test/testcases/confbasic.exp
test/testcases/history.exp
test/testcases/resource.exp

When using `alias` command, give warning like 
`This command 'migrate' is deprecated, please use 'move'`

Low: ui_context: give warning if using alias command

---

doc/crm.8.adoc

After merged #380 , all alias sub-command not show in <TAB> completion, so this PR is to make man page content consistent with the current situation

Fix: doc: Update man page about completion example of crm resource

---

crmsh/ui_resource.py

sub-command `crm resource refresh <Tab>` should complete resource first

Fix: ui_resource: refresh <Tab> should complete resource first

---

crmsh/ui_resource.py

[crmsh-4.1] Fix: ui_resource: refresh <Tab> should complete resource first

---

crmsh/corosync.py
test/unittests/test_corosync.py

Original test `test_add_node_ucast` function operate real config file makes the test failed on second time, since the config file changed. So I use the-mock-way to make the whole unit test re-entrant.

Dev: unittest: change test_add_node_ucast to make whole test reentrant

---

crmsh/corosync.py
test/unittests/test_corosync.py

[crmsh-4.1]Dev: unittest: change test_add_node_ucast to make whole test reentrant

---

crmsh/corosync.py
test/unittests/test_corosync.py

[crmsh-3.0] Dev: unittest: change test_add_node_ucast to make whole test reentrant

---

crmsh/ui_cluster.py
crmsh/utils.py
test/unittests/test_report.py
test/unittests/test_utils.py

To make sure we got the right interface name when init/join
Additionally, use choices to validate -t option

Validate interface using argparse choices

---

crmsh/ui_corosync.py

corosync's quorum and qnetd status just show nodeid, 
It will be convenient to show cluster nodes using command `crm_node -l` which output contain nodeid and node name's mapping

Low: ui_corosync: print cluster nodes while getting quorum and qnetd status

---

crmsh/bootstrap.py
crmsh/constants.py
crmsh/corosync.py
crmsh/crm_pssh.py
crmsh/parallax.py
crmsh/scripts.py
crmsh/ui_cluster.py
crmsh/utils.py
hb_report/utillib.py
test/features/bootstrap_bugs.feature
test/features/bootstrap_init_join_remove.feature
test/features/bootstrap_options.feature
test/features/geo_setup.feature
test/features/qdevice_options.feature
test/features/qdevice_setup_remove.feature
test/features/qdevice_usercase.feature
test/features/qdevice_validate.feature
test/features/resource_failcount.feature
test/features/resource_set.feature
test/features/steps/const.py
test/features/steps/utils.py
test/unittests/test_bootstrap.py
test/unittests/test_utils.py

Using default ssh key of system might have potential side effects and not flexible
* bootstrap.init_ssh/join_ssh only maintain **crmsh key: /root/.ssh/id_rsa.crmsh**
* ssh/scp use -i option to use the crmsh key
* For crmsh.parallax.parallax_call/parallax_copy/parallax_slurp, whether to use crmsh key is optional(default yes)
* Remove --no-overwrite-sshkey option
* Remove ssh_remote stage
* Remove ssh_merge stage
* Related change for hb_report
* Related changes for UT and functional test

Fix: bootstrap: crmsh use its own specific ssh key(bsc#1169581)

---

crmsh/bootstrap.py
crmsh/ui_cluster.py
data-manifest
test/features/bootstrap_sbd.feature
test/features/steps/step_implenment.py
test/unittests/test_bootstrap.py

We are facing several issues about sbd in crmsh lately.
It's might not a good way to add more codes without structure, and might cause more issues with small piece of code here and there.
It's better to manage sbd as a whole part.
Create a class `SBDManager`, and a set of methods to manage sbd configuration and services
Treats sbd as a whole part
Specific methods are easy to find, understand and test
- Create class `SBDManager`
- `SBDManager.sbd_init` to get sbd device, initialize and write configure file
- `SBDManager.manage_sbd_service` to enable or disable sbd service
- `SBDManager.configure_sbd_resource` to configure stonith-sbd resource and stonith-enabled property
- `SBDManager.join_sbd` to check and verify sbd device on join process
- Make `-s`(for sbd device) option and `-S`(for …

SBD management improve

---

crmsh/cibconfig.py
test/testcases/newfeatures
test/testcases/newfeatures.exp

Alert-specific XML nodes `select_fencing`, `select_nodes` and `select_resources` should not have any ID attributes added. The attribute is not valid in this context according to the alert schema.
```
ERROR: Relax-NG validity error : Extra element alerts in interleave
alerts (7): Element configuration failed to validate content
error: main: CIB did not pass DTD/schema validation
Errors found during check: config not valid
Do you still want to commit (y/n)?
```

Low: cibconfig: Avoid adding the ID attribute to select_* nodes

---

crmsh/bootstrap.py
crmsh/constants.py
crmsh/corosync.py
crmsh/crm_pssh.py
crmsh/parallax.py
crmsh/scripts.py
crmsh/ui_cluster.py
crmsh/utils.py
hb_report/utillib.py
test/features/bootstrap_bugs.feature
test/features/bootstrap_init_join_remove.feature
test/features/bootstrap_options.feature
test/features/geo_setup.feature
test/features/qdevice_options.feature
test/features/qdevice_setup_remove.feature
test/features/qdevice_usercase.feature
test/features/qdevice_validate.feature
test/features/resource_failcount.feature
test/features/resource_set.feature
test/features/steps/const.py
test/features/steps/utils.py
test/unittests/test_bootstrap.py
test/unittests/test_utils.py

Consider #575 will cause compatibility problem with old version of crmsh, we decided to revert it.

Revert PR#575 -- Fix: bootstrap: crmsh use its own specific ssh key(bsc#1169581)

---

crmsh/bootstrap.py
crmsh/corosync.py
crmsh/ui_cluster.py
crmsh/utils.py
test/docker_scripts.sh
test/features/bootstrap_options.feature
test/features/qdevice_usercase.feature
test/features/steps/const.py
test/features/steps/step_implenment.py
test/unittests/test_bootstrap.py
test/unittests/test_corosync.py
test/unittests/test_utils.py

Changes:
- Enable specify second interface using `-i` option while init and join process
- Add `validate_option` in `Context` class to valid options(reusable by init and join process)
- Add class `utils.IP` to get some properties of IP address
- Add class `utils.Interface` to get information from one interface
- Add class `utils.InterfacesInfo` to collect interfaces information on local node
- Refactor `bootstrap.init_network` function, get all needed network information through `utils.InterfacesInfo`
- Refactor multiple `bootstrap.valid_*` functions, add class `bootstrap.Validation` to validate values from interactive inputs
- Delete redundant codes and functions
TODO:
RPM:
https://build.opensuse.org/package/show/home:XinLiang:branches:network:ha-clustering:Factory/crmsh

Bootstrap network improvement

---

crmsh/bootstrap.py
crmsh/corosync.py
crmsh/ui_cluster.py
crmsh/utils.py
test/features/bootstrap_bugs.feature
test/features/bootstrap_init_join_remove.feature
test/features/bootstrap_options.feature
test/features/geo_setup.feature
test/features/qdevice_options.feature
test/features/qdevice_setup_remove.feature
test/features/qdevice_usercase.feature
test/features/qdevice_validate.feature
test/features/resource_failcount.feature
test/features/resource_set.feature
test/unittests/test_bootstrap.py
test/unittests/test_corosync.py
test/unittests/test_utils.py

crmsh bootstrap has a very old default of overwriting the root id_rsa ssh key if the customer does not chose the opposite. Also, combined with automation options like -y (that answers yes for all the questions) makes a dangerous combination that can remove SSH access configured previously by the customer, and in extreme cases, could lock the machine depending of the configurations.
- Generate a new rsa key only if /root/.ssh/id_rsa not exist
- Add /root/.ssh/id_rsa.pub to /root/.ssh/authorized_keys, make sure this node itself authorized
- Generate a new rsa key only if /root/.ssh/id_rsa not exist
- Add /root/.ssh/id_rsa.pub to /root/.ssh/authorized_keys, make sure this node itself authorized
- Detect whether login to init node is passwordless, if not, paste /root/.ssh/id_rsa.pub to init …

bootstrap process will not overwrite existing ssh keys

---

crmsh/utils.py
hb_report/constants.py
hb_report/hb_report.in
hb_report/utillib.py

When creating a resulting archive in a slave collector ('hb_report
__slave'), the code tried to decode output produced by the tar utility
as a UTF-8 string (crmutils.get_stdout_stderr() -> to_ascii()). This
corrupted any binary files in the archive, such as gzipped pengine
files.
The patch fixes the problem by obtaining the output from the tar utility
as a bytes object and writing it in the repr() form on stdout of the
slave collector. Similarly, the receiving side is updated to accept this
format.

Low: hb_report: Fix collecting of binary data

---

crmsh/utils.py
hb_report/constants.py
hb_report/hb_report.in
hb_report/utillib.py

When creating a resulting archive in a slave collector ('hb_report
__slave'), the code tried to decode output produced by the tar utility
as a UTF-8 string (crmutils.get_stdout_stderr() -> to_ascii()). This
corrupted any binary files in the archive, such as gzipped pengine
files.
The patch fixes the problem by obtaining the output from the tar utility
as a bytes object and writing it in the repr() form on stdout of the
slave collector. Similarly, the receiving side is updated to accept this
format.

[crmsh-4.1] Low: hb_report: Fix collecting of binary data

---

crmsh/cibconfig.py
test/testcases/newfeatures
test/testcases/newfeatures.exp

[crmsh-4.1] Low: cibconfig: Avoid adding the ID attribute to select_* nodes

---

.travis.yml
crmsh/scripts.py
tox.ini

unittests.test_scripts.test_load_legacy ... /usr/lib/python3/dist-packages/crmsh/scripts.py:431: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.

[12sp2] scripts: fix yaml loader warning

---

crmsh/corosync.py
crmsh/ui_corosync.py
crmsh/utils.py
test/unittests/test_corosync.py
test/unittests/test_utils.py

While setup qdevice on init node, init node will copy its ssh key to qnetd node to setup passwordless ssh login with qnetd node.
But after merging PR #603, each cluster node has its own ssh key, so it's possible that query qnetd status using `crm corosync status qnetd` on other cluster nodes will failed.
The solution is to copy the ssh key to qnetd node if detecting need password while the first time querying qnetd status on the other node

Low: ui_corosync: copy ssh key to qnetd while detect need password

---

crmsh/corosync.py
test/features/qdevice_usercase.feature
test/unittests/test_corosync.py

Since the return code 2 of command `corosync-quorumtool -s` means no problem appeared but node is not quorate, we should adopt to handle that return code when quorum lost.
Additionally, behave test in `qdevice_usercase.feature` has changed to use command `crm corosync status quorum` to make sure this scenarios been tested while quorum lost

Low: corosync: handle the return code of corosync-quorumtool correctly

---

crmsh/bootstrap.py
test/features/bootstrap_sbd.feature
test/unittests/test_bootstrap.py

```
crm cluster init ssh -y
crm cluster init csync2 -y
crm cluster init corosync -y
crm cluster init sbd -s /dev/sdb1 -y (or diskless mode, crm cluster init sbd -S -y)
crm cluster init cluster -y
```
Then sbd.service would not start
Configure sbd and enable sbd.service are in different steps, now combine them together when calling `sbd_init`
* Dev: unittest: adjust unit test cases for sbd config process changes
* Dev: behave: adjust functional test for sbd config process changes
* Fix: bootstrap: revert ssh_merge function for compatibility(bsc#1175057)

Adjust sbd configure process in stage

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

This is a regression issue brought by https://github.com/ClusterLabs/crmsh/pull/617/commits/d4e0b8e57815925f3d625bcfda0d538ca69c1e91
before `join_ssh_merge`, all nodes should finish swapping ssh key, otherwise parallax would have errors like:
```
crm cluster join -c tbw-1 -y
Generating SSH key
Configuring SSH passwordless with root@tbw-1
Password: 
Configuring csync2...done
Merging known_hosts
WARNING: Failed to get known_hosts from tbw-2: Exited with error code 255, Error output: Warning: Permanently added 'tbw-2,10.10.10.27' (ECDSA) to the list of known hosts.
parallax error: SSH requested a password. Please create SSH keys or
use the -A option to provide a password.
parallax error: SSH requested a password. Please create SSH keys or
use the -A option to provide a password.
root@tbw-2: …
```

Low: bootstrap: swap keys with other nodes when join_ssh

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

[crmsh-4.1] Low: bootstrap: swap keys with other nodes when join_ssh

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

[crmsh-3.0] Low: bootstrap: swap keys with other nodes when join_ssh

---

.travis.yml
crmsh/bootstrap.py
crmsh/corosync.py
crmsh/ui_cluster.py
crmsh/ui_corosync.py
crmsh/utils.py
test/docker_scripts.sh
test/features/bootstrap_options.feature
test/features/qdevice_setup_remove.feature
test/features/qdevice_usercase.feature
test/features/qdevice_validate.feature
test/features/steps/step_implenment.py
test/features/steps/utils.py
test/unittests/test_bootstrap.py
test/unittests/test_corosync.py
test/unittests/test_utils.py

The work of this pull request was based on #540 and #464
- More reasonable naming for variables
- More function docstrings
- Move function to more reasonable location, like:
* change `bootstrap.add_nodelist_from_cmaptool` to `corosync.add_nodelist_from_cmaptool`
- Create functions to integrate similar functions inside one, like:
* create `QDevice.certificate_process_on_init` and `QDevice.certificate_process_on_join` methods to integrate certification related fuctions
- Change big function to small one, more easier for unit test, like:
* `bootstrap.init_qdevice`
- Refactor functions:
* Make `utils.service_is_enabled`, `utils.service_is_active` and `utils.package_is_installed` can be executed on remote node
- Create `utils.cluster_run_cmd` function to avoid using `crm …

Qdevice config process improve

---

.travis.yml
data-manifest
hb_report/utillib.py
test/features/hb_report_bugs.feature
test/features/steps/step_implenment.py
test/features/steps/utils.py
test/unittests/test_report.py

hb_report would not collect any archived logs like `/var/log/messages-20200819.xz`
* In `arch_logs` function, miss appending archived logs
* Should use `lzma.open` to open `.xz` files instead of using `open`
* Part of codes in this PR are borrowed from #557, in which this issue has been fixed
```
@clean
Scenario: Include archived logs(bsc#1148873)
When    Write multi lines to file "/var/log/log1"
"""
Sep 08 08:36:34 node1 log message line1
Sep 08 08:37:01 node1 log message line2
Sep 08 08:37:02 node1 log message line3
"""
And     Run "xz /var/log/log1" on "hanode1"
When    Write multi lines to file "/var/log/log1"
"""
Sep 08 09:37:02 node1 log message line4
Sep 08 09:37:12 node1 log message line5
"""
And     Run "hb_report -f 20200901 -E /var/log/log1 report1" on "hanode1"
Then    File …
```

hb report include archived log

---

.travis.yml
crm.conf.in
crmsh/config.py
crmsh/ui_configure.py
data-manifest
doc/crm.8.adoc
test/features/configure_bugs.feature
test/features/steps/step_implenment.py
test/run-in-travis.sh

`crm configure show` will display sensitive data like `password` in clear text
By adding default value to `/etc/crm/crm.conf`:
```
; [core]
; obscure_pattern = passw*
```
The sensitive data will be replaced by `*` by default.
If you don't want to obscure, change the `obscure_pattern` to blank.
If you want to replace more sensitive data, you could append more patterns
to `obscure_pattern` with format `pattern1 pattern2 pattern3` or `pattern1|pattern2|pattern3`.
```
When    Run "crm node utilization hanode1 set password qwertyui" on "hanode1"
When    Try "crm configure show|grep password|grep qwertyui"
Then    Expected return code is "1"
```

Obscure sesitive data by default

---

crmsh/config.py
crmsh/utils.py

When un-commented options in `/etc/crm/crm.conf` and missing un-commented section headers,
configparser.MissingSectionHeaderError will raise and print traceback
```
Traceback (most recent call last):
File "/usr/sbin/crm", line 29, in <module>
from crmsh import main
File "/usr/lib/python3.6/site-packages/crmsh/main.py", line 9, in <module>
from . import config
File "/usr/lib/python3.6/site-packages/crmsh/config.py", line 454, in <module>
load()
File "/usr/lib/python3.6/site-packages/crmsh/config.py", line 394, in load
_configuration.load()
File "/usr/lib/python3.6/site-packages/crmsh/config.py", line 315, in load
self._systemwide.read([_SYSTEMWIDE])
File "/usr/lib64/python3.6/configparser.py", line 697, in read
self._read(fp, filename)
File "/usr/lib64/python3.6/configparser.py", line …
```

Low: config: Try to handle configparser.MissingSectionHeaderError while reading

---

crmsh/config.py

backport from #630 
But change the way as print instead of raise like pr630, since that will cause circular import problem
```
def _safe_read(self, config_parser_inst, file_list):
"""
Try to handle configparser.MissingSectionHeaderError while reading
"""
try:
config_parser_inst.read(file_list)
except configparser.MissingSectionHeaderError as e:
print("{}: {}".format(type(e).__name__, e))
sys.exit(1)
```

[crmsh-4.1] Low: config: Try to handle configparser.MissingSectionHeaderError while reading

---

crmsh/config.py

[crmsh-3.0] Low: config: Try to handle configparser.MissingSectionHeaderError while reading

---

crmsh/bootstrap.py
crmsh/corosync.py
crmsh/utils.py
test/features/bootstrap_bugs.feature
test/features/steps/step_implenment.py
test/unittests/test_bootstrap.py
test/unittests/test_utils.py

After running `crm cluster remove peer-node`,
* On udpu mode, peer-node's address wouldn't be removed in corosync.conf
* Value of `expected_votes` and `two_node` changed, but not sync to other left cluster nodes
* `bootstrap_remove` function is huge, better to split into smaller one
* `remove_get_hostname` function is complex, I think it's not necessary to let user input once again,
just exit with error message. So I decide to delete this function
- `On udpu mode, peer-node's address wouldn't be removed in corosync.conf`
This is because pass the hostname to `corosync.del_node`, not ip address;
Add `get_cluster_node_ip` function to make sure we got the right parameter value, that is to say,
if a hostname configured, pass that hostname, if IP configured, pass that IP
- `Value of …

Fix bug of remove node(bsc#1165644)

---

.travis.yml
crmsh/cibverify.py
crmsh/parse.py
crmsh/ui_configure.py
data-manifest
doc/crm.8.adoc
test/features/constraints_bugs.feature
test/run-in-travis.sh
test/testcases/common.excl
test/unittests/test_parse.py

1. In pacemaker 2.x, `score` syntax in rsc_order configure was deprecated
2. crmsh give error while the return message of crm_verify was a warning
For problem 1, convert score to `kind`, that is, convert `INFINITY` and score greater than "0" to `Mandatory`, else, convert as `Optional`
For problem 2, give a warning if return message of crm_verify was a warning
For problem 1:
```Shell
When    Run "crm configure primitive d1 Dummy op monitor interval=10s" on "hanode1"
And     Run "crm configure primitive d2 Dummy op monitor interval=10s" on "hanode1"
And     Run "crm configure order o1 100: d1 d2" on "hanode1"
When    Run "crm configure show" on "hanode1"
Then    Expected "order o1 Mandatory: d1 d2" in stdout
```

Convert score to kind for rsc_order configure

---

crmsh/bootstrap.py
crmsh/utils.py
test/unittests/test_bootstrap.py
test/unittests/test_utils.py

1. Some service management related functions were here and there, and some of them were redundant
2. It will more convenient to make all of these functions running remotely or locally
1. Create class `ServerManager` which has a set of service management functions
2. Create shortcuts for the classmethod to make sure the API wouldn't change
This PR would be small enough to backport to other branches

Refactor service management codes

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

Missed in #648, already synced with #652 and #653

Stop service which is active, not which is available

---

crmsh/bootstrap.py
test/features/bootstrap_bugs.feature
test/features/steps/utils.py
test/unittests/test_bootstrap.py

[crmsh-4.1] Stop hawk service when removing node

---

crmsh/ui_cluster.py
test/unittests/test_ui_cluster.py

When trying to start an already started cluster, giving "Cluster services already started",
When trying to stop an already stopped cluster, giving "Cluster services already stopped"

Check cluster service status while start or stop

---

test/unittests/test_bugs.py
test/unittests/test_corosync.py
test/unittests/test_report.py
test/unittests/test_utils.py

by using command `grep -R -E -o "def .*\(" *|uniq -cd`, to print duplicated test function name
That should be changed, otherwise the same named function wouldn't be tested

Dev: unittest: adjust duplicated test function name

---

test/unittests/test_bugs.py
test/unittests/test_report.py

[crmsh-4.1] Dev: unittest: adjust duplicated test function name

---

hb_report/utillib.py
test/features/hb_report_bugs.feature

The hb_report result didn't include corosync.log
Collect corosync log if it was defined in **logging.logfile** in corosync.conf and in the time span
``` Shell
@clean
Scenario: Collect corosync.log(bsc#1148874)
When    Run "sed -i 's/\(\s*logfile:\s*\).*/\1\/var\/log\/cluster\/corosync.log/' /etc/corosync/corosync.conf" on "hanode1"
And     Run "hb_report report" on "hanode1"
And     Run "tar jxf report.tar.bz2" on "hanode1"
Then    File "corosync.log" not in "report.tar.bz2"
When    Run "rm -rf report.tar.gz report" on "hanode1"
When    Run "sed -i 's/\(\s*to_logfile:\s*\).*/\1yes/' /etc/corosync/corosync.conf" on "hanode1"
And     Run "crm cluster stop" on "hanode1"
And     Run "crm cluster start" on "hanode1"
And     Run "hb_report report" on "hanode1"
And     Run "tar jxf …
```

Fix: hb_report: collect corosync.log if it defined in config file(bsc#1148874)

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

- Using .format instead of %s
- Meaningful variable names
- Using print_error_msg instead of term.render
- Continue if sbd device value is None to avoid crash(bsc#1178333)
- Add unit test codes for _get_sbd_device_interactive function

Minor change for _get_sbd_device_interactive function

---

hb_report/hb_report.in

`hb_report-Thu-12-Nov-2020` will be more readable than `hb_report-4-12-11-2020`

Dev: hb_report: change the default dest data format, more readable

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

cluster init without qdevice should "systemctl disable corosync-qdevice" if it is enabled, and the similarly for cluster join

Fix: bootstrap: disable corosync-qdevice if not configured

---

crmsh/bootstrap.py
crmsh/utils.py
test/unittests/test_bootstrap.py
test/unittests/test_utils.py

In #680, we should check whether `corosync-qdevice` is available firstly, to avoid error if that package didn't installed
So I've improved `ServiceManager.disable_service` and `ServiceManager.enable_service` to make the action more solid

Fix: utils: improve disable_service and enable_service function

---

crm.conf.in
crmsh/bootstrap.py
crmsh/config.py
crmsh/join_lock.py
data-manifest
test/unittests/test_bootstrap.py
test/unittests/test_join_lock.py

For multi nodes scenarios, while multi nodes joining to the init node at the same time, the results will be undefined and risky.
It might cause errors on ssh key deployment, csync2 or config files not synced.
By touching a lock file to make multi nodes join process as one-by-one joining.
Assuming we have 3 nodes(A, B, C), A is the init node, just finish the init process.
1. A lock file will be touched on init node A when the first join node B try to join
2. B starts another thread to update the timestamp of the lock file(in 10s interval)
3. Another join nodes C detect(in 15s interval) lock file exists and timestamp updates, waiting...
4. B finished joining, remove lock file
5. If C found no local file exist, touch the lock file and starts joining
6. If C found lock file always exists and …

Add lock for multi nodes join in parallel

---

crm.conf.in
crmsh/bootstrap.py
crmsh/config.py
crmsh/join_lock.py
data-manifest
test/unittests/test_bootstrap.py
test/unittests/test_join_lock.py

backport #677 
Different from master branch: in `join_lock.py`, to avoid circular-imports, import bootstrap in which function needed

[crmsh-4.1] Add lock for multi nodes join in parallel

---

crm.conf.in
crmsh/bootstrap.py
crmsh/config.py
crmsh/join_lock.py
data-manifest
test/unittests/test_bootstrap.py
test/unittests/test_join_lock.py

backport #677 
Different from master branch: 
* in `join_lock.py`, to avoid circular-imports, import bootstrap in which function needed
* in `join_lock.py`, define TimeoutError class since it doesn't exist in python2.7

[crmsh-3.0] Add lock for multi nodes join in parallel

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

I make this PR based on these thinking:
- Detecting whether init node has cluster service running, on logical side, shouldn't be the task inside `setup_passwordless_with_other_nodes` function
- Instead, we should do this detecting job just after finishing `join_ssh`, that is, detect after finishing swapping the ssh key with the init node
- Considering the `init lock` I mentioned yesterday, if on init process we create `/tmp/.crmsh_join_lock_directory`, join node will wait. But I don't want to use this `init lock` to protect unready init node, instead, just to protect extra qdevice setup process. 
@arbulu89 , what do you think?

Low: bootstrap: check cluster was running on init node

---

crmsh/bootstrap.py
crmsh/corosync.py
crmsh/utils.py
test/unittests/test_corosync.py
test/unittests/test_utils.py

Purpose to create this PR: to distinguish `host unreachable error` and some `ssh error` like `Permission denied (publickey)` raised later when `join_ssh`

Dev: bootstrap: use ping to test host is reachable before joining

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

[crmsh-4.1] Low: bootstrap: check cluster was running on init node

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

[crmsh-3.0] Low: bootstrap: check cluster was running on init node

---

.github/workflows/crmsh-ci.yml

Default is 360m, see https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes

Dev: test: add timeout-minutes to each test job

---

test/docker_scripts.sh
test/features/bootstrap_bugs.feature

backport from 6d3bab34ea7554f2726914ae3ee1cd39403453c6 from master branch, without qdevice part

[crmsh-4.1] Simplify container deploy bash script docker_scripts.sh for functional test

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

When meeting error on bootstrap process, error message might make user confused like:
```Shell
WARNING: No watchdog device found. If SBD is used, the cluster will be unable to start without a watchdog.
Do you want to continue anyway (y/n)? y
WARNING: Failed to detect firewall: Could not open ports tcp=30865|5560|7630|21064, udp=
Generating SSH key
Configuring SSH passwordless with root@crmsh15sp2-1
ERROR: cluster.join: Failed to run "cat /root/.ssh/id_rsa.pub | ssh -oStrictHostKeyChecking=no root@crmsh15sp2-1 'cat >> /root/.ssh/authorized_keys'"
```
User cannot find reason why this command failed
In bootstrap.py, `invoke` was commonly used, it record log about what has executed, the stdout and the stderr after running command.
I change the return code of `invoke` function, return …

Dev: bootstrap: improve invoke to print error to give specific hints

---

crmsh/bootstrap.py

[crmsh-4.1] Fix: bootstrap: add /etc/modules-load.d/watchdog.conf into csync.cfg

---

crmsh/bootstrap.py

[crmsh-3.0] Fix: bootstrap: add /etc/modules-load.d/watchdog.conf into csync.cfg

---

crmsh/utils.py
test/unittests/test_utils.py

[crmsh-3.0] Fix: utils: skip if no netmask in the result of ip -o addr show

---

crmsh/utils.py
test/unittests/test_utils.py

[crmsh-4.1] Fix: utils: skip if no netmask in the result of ip -o addr show 

---

crmsh/utils.py
test/unittests/test_utils.py

When tun interface(like when using openvpn) was available, the format of output `ip -4 -o addr show` might not consistent as:
```
4: br1    inet 10.10.10.10/24 brd 10.10.10.255 scope global noprefixroute br1\       valid_lft forever preferred_lft forever
5: br2    inet 20.20.20.20/24 brd 20.20.20.255 scope global noprefixroute br2\       valid_lft forever preferred_lft forever
6: virbr0    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0\       valid_lft forever preferred_lft forever
61: tun0    inet 10.163.45.46 peer 10.163.45.45/32 scope global tun0\       valid_lft forever preferred_lft forever
```
Will cause init process failed with error `ERROR: cluster.init: not enough values to unpack (expected 2, got 1)`
Drop the interface item when detecting without netmask

Fix: utils: skip if no netmask in the result of ip -o addr show

---

Makefile.am
crmsh/completers.py
preflight_check/check.py
preflight_check/config.py
preflight_check/explain.py
preflight_check/ha-cluster-preflight-check
preflight_check/main.py
preflight_check/task.py
preflight_check/utils.py

This PR was for integrating [cluster_preflight_check](https://github.com/liangxin1300/cluster_preflight_check) into crmsh
- Consistency
- Easier to memorize for our customers
- Integrated under one root ("crm cluster")
- Less maintain job for  python-cluster-preflight-check package
- Easy to make tests under the existing crmsh test framework 
```
main.run
setup_basic_context
parse_argument
setup_logging
check.check  (-e/--env-check and -c/--cluster-check option, task.TaskCheck)
kill_process (--kill-sbd/--kill-corosync/--kill-pacemakerd, task.TaskKill)
fence_node   (--fence-node, task.TaskFence)
split_brain  (--split-brain-iptables, task.TaskSplitBrain)
``` 
- Prerequisite checking
- Logging
- Results/report dumping
- Run command
- Wait/Monitor result in thread
[only for Tumbleweed and …

Integrate preflight_check into crmsh

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

SBD devices might have the same name but different UUID between cluster nodes, that might lead to stonith action failed
- During join process, for each configured sbd device, compare local UUID with UUID on init node
- For outer tools (like preflight check) want to verify sbd device on an existing cluster, calling `bootstrap.SBDManager.verify_sbd_device`, will raise `ValueError` when having this problem
@arbulu89 @gao-yan @zzhou1 Any suggestions?
Thanks!

Fix: bootstrap: make sure sbd device UUID was the same between nodes

---

crmsh/bootstrap.py
crmsh/utils.py
test/unittests/test_bootstrap.py

backport #687, all the same except add function `utils.list_cluster_nodes_except_me` from master branch

[crmsh-3.0] Fix: bootstrap: make sure sbd device UUID was the same between nodes 

---

crmsh/bootstrap.py
crmsh/utils.py
test/unittests/test_bootstrap.py

backport #687, all the same except add function `utils.list_cluster_nodes_except_me` from master branch

[crmsh-4.1] Fix: bootstrap: make sure sbd device UUID was the same between nodes 

---

crmsh/bootstrap.py
crmsh/ui_cluster.py
test/features/bootstrap_sbd.feature
test/features/steps/const.py
test/unittests/test_bootstrap.py

see #714
- Add **class Watchdog** to find valid watchdog device name
- Drop `-w` option on join side
- Option `-w` on init side could be a watchdog device name or driver name
```
-w WATCHDOG, --watchdog WATCHDOG
Use the given watchdog device or driver name
```
- How to use class Watchdog?
```Python
self._watchdog_inst = Watchdog(_input=_context.watchdog)
self._watchdog_inst.init_watchdog()
self._watchdog_inst = Watchdog(peer_host=peer_host)
self._watchdog_inst.join_watchdog()
```
- In class Watchdog, will parse these in order:
> 1. value of `-w` option
> 2. result from /etc/sysconfig/sbd (value of SBD_WATCHDOG_DEV)
> 3. the first valid/unused device from result of sbd query-watchdog
> 4. softdog
- If to handle a driver name, and that driver was not loaded now, run:
```
invoke("echo {} > …
```

Use class Watchdog to simplify watchdog config

---

crmsh/corosync.py

[crmsh-3.0] Dev: corosync: change the permission of corosync.conf to 644

---

crmsh/corosync.py

[crmsh-4.1] Dev: corosync: change the permission of corosync.conf to 644

---

crmsh/config.py
crmsh/utils.py
preflight_check/check.py
preflight_check/task.py
test/unittests/test_preflight_check.py
test/unittests/test_preflight_main.py
test/unittests/test_preflight_task.py
test/unittests/test_preflight_utils.py
tox.ini

The pull request including:
1. Unit test cases of ASR SBD device feature. Test coverage is 100% for the new code.
Overall report for all preflight check code:
```
----------- coverage: platform linux, python 3.6.5-final-0 -----------
Name                                                                                     Stmts   Miss  Cover
------------------------------------------------------------------------------------------------------------
/warehouse/Source-code/git/HA-ClusterLabs/crmsh.git.review/preflight_check/__init__.py       0      0   100%
/warehouse/Source-code/git/HA-ClusterLabs/crmsh.git.review/preflight_check/check.py        187      2    99%
/warehouse/Source-code/git/HA-ClusterLabs/crmsh.git.review/preflight_check/config.py         8      0   100% …
```

Feature asr unit test cases and minor bug fix

---

hb_report/utillib.py
test/unittests/test_report.py

During dumping ocfs2 info in hb_report, running `lsof` directly might hanging for a long time,  and the most of output might have no related with ocfs2
Run `lsof` with specific ocfs2 device
Test rpm link: https://build.opensuse.org/package/show/home:XinLiang:branches:crmsh_testing3/crmsh

Fix: hb_report: run lsof with specific ocfs2 device

---

hb_report/utillib.py

Checking before dumping:
1. If has `mounted.ocfs2` command
2. if any ocfs2 partitions exist by checking output of `mounted.ocfs2`
RPM link: https://build.opensuse.org/package/show/home:XinLiang:branches:crmsh_testing6/crmsh

Add entry limitation for dump_ocfs2 function

---

crmsh/bootstrap.py
crmsh/ui_cluster.py
test/features/bootstrap_sbd.feature
test/features/steps/const.py
test/unittests/test_bootstrap.py

backport #689 All the same with the code part, slightly different with UT codes

[crmsh-4.1] Use class Watchdog to simplify watchdog config

---

crmsh/bootstrap.py
crmsh/ui_cluster.py
test/features/bootstrap_sbd.feature
test/features/steps/const.py
test/unittests/test_bootstrap.py

backport #689 ,   All the same with the code part, except using OrderedDict to store `self._watchdog_info_dict`, to get the right result when calling `self._get_first_unused_device`

[crmsh-3.0] Use class Watchdog to simplify watchdog config

---

crmsh/corosync.py
crmsh/utils.py

[crmsh-4.1] Dev: utils: change default file mod as 644 for str2file function

---

crmsh/corosync.py
crmsh/utils.py

[crmsh-3.0] Dev: utils: change default file mod as 644 for str2file function

---

crmsh/bootstrap.py
crmsh/utils.py
hb_report/hb_report.in
hb_report/utillib.py
test/unittests/test_bootstrap.py

It didn't work if run **hb_report** or **crm cluster copy** under **hacluster** user, which was required from Hawk
- Change function `bootstrap.configure_local_ssh_key` and `bootstrap.swap_public_ssh_key` to accept non-root user parameter; That is, for common user, bootstrap process also setup password-less among cluster nodes
- Assign `/usr/bin/sh` to hacluster's login shell, otherwise, it's impossible to run command remotely
- On interactive mode, behavior about changing hacluster's login shell and setup ssh access will be asked for confirm
- For `runtime` existing cluster, need to use `ssh` stage to setup password-less access for hacluster
* on init node, run `crm cluster init ssh -y`
* on join node, run `crm cluster join ssh -c <init node> -y`
- For `runtime` existing cluster, …

Run hb_report under hacluster

---

crmsh/ui_node.py
doc/crm.8.adoc

I think it's useless to leave a such subcommand just to show xml, which might increase confusing, see #685

Remove crm node status subcommand

---

crmsh/ra.py
crmsh/ui_configure.py

crmsh allow to configure undefined RA parameter in this way:
```
primitive id=d Dummy params test fake=xxx # here "test" was undefined
```
Then commit without any error raise, got this xml:
```
<primitive id="d" class="ocf" provider="heartbeat" type="Dummy">
<instance_attributes id="d-instance_attributes">
<nvpair name="test" id="d-instance_attributes-test"/>
<nvpair name="fake" value="xxx" id="d-instance_attributes-fake"/>
</instance_attributes>
</primitive>
```
In `ra.sanity_check_params`, crmsh did check if giving parameter exists, but did not check parameter without a value
So after change, in this case will raise an error
```
ERROR: d: parameter test does not exist
Do you still want to commit (y/n)?
```
Also, the completer of `crm configure primitive` might mislead user to add that …

Fix: ui_configure: raise error when params not exist

---

crmsh/bootstrap.py
crmsh/ui_cluster.py
crmsh/utils.py
test/features/qdevice_setup_remove.feature
test/features/qdevice_validate.feature
test/features/steps/step_implenment.py
test/unittests/test_bootstrap.py
test/unittests/test_ui_cluster.py
test/unittests/test_utils.py

Configuring qdevice with diskless SBD during init process will cause init node rebooted
And, removing qdevice with diskless SBD will also got the node rebooted
When setup qdevice, the current order was:
- Add qdevice configuration
- Run corosync reload (then quorum lost)
- Certification process (take a relative long time, then node got rebooted)
- Start qdevice service
When removing qdevice, the current order was:
- Stop qdevice service (then quorum lost)
- Remove configuration (the node got rebooted)
- Run corosync reload
In short, Diskless SBD require quorum, when reload qdevice configuration, quorum will lost for a while, then then node got rebooted
**Process 1**. Setup qdevice with bootstrap init process from beginning
**Process 2**. Append qdevice on an existing running cluster via …

Adjust qdevice configure process with diskless sbd

---

crmsh/corosync.py
crmsh/ui_cluster.py
crmsh/ui_corosync.py
crmsh/ui_node.py
crmsh/utils.py

I think under current live branches, no need to detect if the cluster stack is corosync

Dev: utils: remove unused utils.cluster_stack and its related codes

---

crmsh/bootstrap.py
crmsh/utils.py
test/unittests/test_bootstrap.py
test/unittests/test_utils.py

Using diskless SBD with less than 3 nodes was not recommend, it'd better if bootstrap giving related warning while configuring diskless SBD

Fix: bootstrap: raise warning when configuring diskless SBD with less than 3 nodes

---

crmsh/lock.py
test/features/bootstrap_bugs.feature
test/unittests/test_lock.py

**Just when** finished setup two nodes cluster with diskless SBD, I reboot node two **immediately**, then node one also be fenced by sbd.
After reboot, I found the lock directory not be deleted on node one, which should already be deleted when node two finished bootstrap join 
Should run `sync` command after remove lock directory, otherwise, the lock directory might not be deleted in time

Change lock directory under /run

---

crmsh/bootstrap.py
crmsh/corosync.py
crmsh/ui_cluster.py
test/features/qdevice_validate.feature
test/features/steps/const.py
test/unittests/test_bootstrap.py

```Bash
15sp2-1:~ # crm cluster init -y
Configuring csync2
Generating csync2 shared key (this may take a while)...done
csync2 checking files...done
Configuring corosync
WARNING: Not configuring SBD (/etc/sysconfig/sbd left untouched).
WARNING: Hawk not installed - not configuring web management interface.
Waiting for cluster..............done
Loading initial cluster configuration
Done (log saved to /var/log/crmsh/ha-cluster-bootstrap.log)
15sp2-1:~ # crm cluster init qdevice
Do you want to configure QDevice (y/n)? y
HOST or IP of the QNetd server to be used []15sp2-3
TCP PORT of QNetd server [5403]
QNetd decision ALGORITHM(ffsplit/lms) [ffsplit]
QNetd TIE_BREAKER(lowest/highest/valid node id) [lowest]
Whether using TLS on QDevice/QNetd(on/off/required) [on]
COMMAND to run with absolute …
```

Configure qdevice on interactive mode

---

crmsh/bootstrap.py
test/features/bootstrap_bugs.feature
test/unittests/test_bootstrap.py

When configuring an alias peer host name in /etc/hosts, crm cluster join/remove might failed
Change the logic of get_cluster_node_hostname function, always using `crm_node --name` to get the peer node's host name

Fix: bootstrap: get the peer node name correctly

---

crmsh/bootstrap.py
test/features/bootstrap_bugs.feature
test/unittests/test_bootstrap.py

[crmsh-3.0] Fix: bootstrap: get the peer node name correctly

---

crmsh/bootstrap.py
test/features/bootstrap_bugs.feature
test/unittests/test_bootstrap.py

[crmsh-4.1] Fix: bootstrap: get the peer node name correctly 

---

crmsh/bootstrap.py
crmsh/utils.py
test/unittests/test_bootstrap.py
test/unittests/test_utils.py

1. Not support space in value of `-s` option: `crm cluster init -s "/dev/sda1 " -y`
2. If has space between multi sbd devices in /etc/sysconfig/sbd, join process will raise an error:
`ERROR: cluster.join:  /dev/sdb1 doesn't look like a block device`
3. On init side, there was also an error if input space on interactive mode:
```
Path to storage device (e.g. /dev/disk/by-id/...), or "none" for diskless sbd, use ";" as separator for multi path []/dev/sda1; /dev/sdb1
ERROR:  /dev/sdb1 doesn't look like a block device
```
Anyway, it's too strict, should loose the limitation

Support parse space in sbd device name

---

crmsh/ui_cluster.py

When running `crm cluster disable`, if exist enabled qdevice service, then after reboot, both corosync and corosync-qdevice will all started

Dev: ui_cluster: enable/disable corosync-qdevice.service

---

crmsh/bootstrap.py
crmsh/constants.py
crmsh/ui_cluster.py
test/features/steps/const.py

```
QDevice configuration:
QDevice is a separate quorum device which acts as a third-party 
arbitration device for the cluster. Its primary use is to allow 
a cluster to sustain more node failures than standard quorum rules allow.
Options for configuring QDevice and QNetd.
--qnetd-hostname HOST
HOST or IP of the QNetd server to be used
--qdevice-port PORT   TCP PORT of QNetd server (default:5403)
--qdevice-algo ALGORITHM
QNetd decision ALGORITHM (ffsplit/lms,
default:ffsplit)
--qdevice-tie-breaker TIE_BREAKER
QNetd TIE_BREAKER (lowest/highest/valid_node_id,
default:lowest)
--qdevice-tls TLS     Whether using TLS on QDevice/QNetd (on/off/required,
default:on)
--qdevice-heuristics COMMAND
COMMAND to run with absolute path. For multiple
commands, use ";" to separate (details about
heuristics …
```

Dev: ui_cluster: add qdevice help info

---

crmsh/bootstrap.py
crmsh/corosync.py
crmsh/utils.py
test/unittests/test_bootstrap.py
test/unittests/test_corosync.py

I found that corosync.conf will become empty when reset init node just after join process finished, so the cluster service wouldn't be started on init node then.
How to reproduce it:
1. On init node: crm cluster init -u -i eth1 -i eth2 -y
2. On join node: crm cluster join -c <init_node> -y -i eth1 -i eth2 -y
3. Just when join process finished, quickly force reset the init node
4. After init node started, corosync.conf become empty
- Before finishing join process, run `sync <files>` command between cluster nodes, to make sure all these files' contents sync to disk
- Use `utils.str2file` to write data into file, `utils.str2file` could execute `os.fsync` internally
Change more string values as constants

Fix: bootstrap: sync files before finished joining

---

crmsh/corosync.py
crmsh/ui_corosync.py
doc/crm.8.adoc
test/unittests/test_corosync.py

```Bash
1084783311 15sp2-1 member
1084783193 15sp2-2 member
Qdevice information
-------------------
Model:                  Net
Node ID:                1084783311
HB interval:            10000ms
Sync HB interval:       30000ms
Configured node list:
0   Node ID = 1084783193
1   Node ID = 1084783311
Heuristics:             Disabled
Ring ID:                40a87a59.10c
Membership node list:   1084783193, 1084783311
Quorate:                Yes
Quorum node list:
0   Node ID = 1084783193, State = member
1   Node ID = 1084783311, State = member
Expected votes:         3
Last poll call:         2021-04-12T10:37:09 (cast vote)
Qdevice-net information
----------------------
Cluster name:           hacluster
QNetd host:             15sp2-3:5403
Connect timeout:        8000ms
HB interval: …
```

Dev: add "crm corosync status qdevice" sub-command

---

crmsh/bootstrap.py
crmsh/utils.py
test/unittests/test_bootstrap.py
test/unittests/test_utils.py

[crmsh-3.0] Fix: bootstrap: raise warning when configuring diskless SBD with less than 3 nodes

---

crmsh/bootstrap.py
crmsh/utils.py
test/unittests/test_bootstrap.py
test/unittests/test_utils.py

[crmsh-4.1] Fix: bootstrap: raise warning when configuring diskless SBD with less than 3 nodes

---

crmsh/bootstrap.py
crmsh/ui_cluster.py
crmsh/utils.py
test/features/bootstrap_sbd.feature
test/unittests/test_bootstrap.py
test/unittests/test_utils.py

```
Initializing SBD......done
Restarting cluster service
Waiting for cluster..............done
Done (log saved to /var/log/crmsh/ha-cluster-bootstrap.log)
```
Then we can see `stonith-sbd (stonith:external/sbd)` and sbd.service started on each node
```
Initializing SBD......done
WARNING: To start sbd.service, need to restart cluster service manually on each node
Done (log saved to /var/log/crmsh/ha-cluster-bootstrap.log)
```
Then we can restart cluster service at suitable time (`stonith-sbd (stonith:external/sbd)` already configured), then we can see sbd.service started on each node
```
Initializing diskless SBD......done
Restarting cluster service
Waiting for cluster..............done
Done (log saved to /var/log/crmsh/ha-cluster-bootstrap.log)
```
Then we can see sbd.service started on …

Add sbd stage on a running cluster

---

crmsh/bootstrap.py

Changed after #803 
Should raise exception while only calling `status_done` function when success

Dev: bootstrap: raise exception and execute status_done on success

---

crmsh/bootstrap.py
crmsh/watchdog.py
data-manifest
test/unittests/test_bootstrap.py
test/unittests/test_watchdog.py

bootstrap.py is huge, should split some classes into specific .py file, also make easier for maintain and testing

Split class Watchdog into watchdog.py from bootstrap.py

---

crmsh/bootstrap.py
crmsh/ocfs2.py
crmsh/ra.py
crmsh/ui_analyze.py
crmsh/ui_cluster.py
crmsh/ui_context.py
crmsh/utils.py
test/features/ocfs2.feature
test/features/steps/const.py
test/features/steps/step_implenment.py
test/run-in-travis.sh
test/unittests/test_bootstrap.py
test/unittests/test_ocfs2.py
test/unittests/test_utils.py

To make the OCFS2 configure process more simple, flexible and solid, also to extend using scenarios for OCFS2 + Cluster LVM, I refactored the code for configuring OCFS2
https://build.opensuse.org/package/show/home:XinLiang:branches:crmsh_ocfs2/crmsh
```
Storage configuration:
Options for configuring shared storage.
-s DEVICE, --sbd-device DEVICE
Block device to use for SBD fencing, use ";" as
separator or -s multiple times for multi path (up to 3
devices)
-o DEVICE, --ocfs2-device DEVICE
Block device to use for OCFS2; When using Cluster LVM2
to manage the shared storage, user can specify one or
multiple raw disks, use ";" as separator or -o
multiple times for multi path (must specify -C option)
NOTE: this is a Technical Preview
-C, --cluster-lvm2    Use Cluster LVM2 for OCFS2 (only valid …
```

Bootstrap support ocfs2 option

---

crmsh/help.py
crmsh/ui_cluster.py
crmsh/ui_context.py
doc/crm.8.adoc
test/features/steps/const.py

1. For some subcommands which were using argparse, help messages exist both in crm.8.adoc and code, it's easy to cause inconsistent since code in argparse might changed frequently
2. Run `crm cluster --help` will pop a warning: `WARNING: This command '--help' is deprecated, please use 'help'`, this is also inconsistent for the command syntax
**For problem 1**: In `crm.8.adoc`, mark those subcommands using argparse as `From Code`, then calling `-h/--help`, display that output, make sure only one place has help messages
**For problem 2**: Add additional condition based on https://github.com/ClusterLabs/crmsh/pull/558, to check whether the command name was -h or --help, don't consider it as alias
https://build.opensuse.org/package/show/home:XinLiang:branches:crmsh_testing/crmsh

Show help message from command line if that subcommand use argparse

---

crmsh/parse.py

```Bash
crm(live/15sp2-1)configure# property stonith-timeout=
ERROR: syntax in property: Unknown arguments: stonith-timeout= near <stonith-timeout=> parsing 'property stonith-timeout='
crm(live/15sp2-1)configure# property stonith-timeout
ERROR: syntax in property: Unknown arguments: stonith-timeout near <stonith-timeout> parsing 'property stonith-timeout'
```

Fix: parse: shouldn't allow property setting with an empty value

---

crmsh/parse.py

[crmsh-3.0] Fix: parse: shouldn't allow property setting with an empty value

---

crmsh/parse.py

[crmsh-4.1] Fix: parse: shouldn't allow property setting with an empty value

---

crmsh/utils.py

Since corosync already support link-local address, we should remove this limitation

Dev: utils: allow configure link-local ipv6 address

---

crmsh/bootstrap.py
crmsh/utils.py
test/unittests/test_bootstrap.py

When using diskless SBD with qdevice, **SBD_WATCHDOG_TIMEOUT** in /etc/sysconfig/sbd should larger than qdevice sync_timeout, see https://github.com/corosync/corosync-qdevice/issues/21
- **When set diskless SBD and qdevice together**, like `crm cluster init -S --qnetd-hostname <qnetd_addr>`, set **SBD_WATCHDOG_TIMEOUT**=35, set **stonith-timeou**t as (SBD_WATCHDOG_TIMEOUT*2+20)s，stonith-watchdog-timeout=-1
- **When adding qdevice on a running cluster also with diskless SBD running**, like `crm cluster init qdevice --qnetd-hostname <qnetd_addr>`, set **SBD_WATCHDOG_TIMEOUT**=35, and sync the sbd config file, **stonith-timeou**t=90s (stonith-watchdog-timeout already been set as -1), then restart the cluster service on needed (auto restart when no RA running; hints manually restart when RA …

Fix: bootstrap: update sbd watchdog timeout when using diskless SBD with qdevice

---

crmsh/ocfs2.py
crmsh/utils.py
test/unittests/test_ocfs2.py
test/unittests/test_utils.py

When detecting the OCFS2 device(value of `device` option in Filesystem RA) is a device-mapper device like lvm or raid, skip comparing the UUID on join node and init node

Fix: ocfs2: skip verifying UUID for ocfs2 device on top of raid or lvm on the join node 

---

.github/workflows/crmsh-ci.yml
crmsh/ocfs2.py
crmsh/utils.py
test/unittests/test_ocfs2.py
test/unittests/test_utils.py

[crmsh-4.3] Fix: ocfs2: skip verifying UUID for ocfs2 device on top of raid or lvm on the join node

---

crmsh/bootstrap.py

The bootstrap code expects that each line in the output from `crm_node -l` is in the following form: `<id> <nodename> <state>`, with all three fields always present. This is the usual situation but it is in some cases possible that `<nodename>` and/or `<state>` can be missing. For instance, a node can be configured in the `nodelist` in `corosync.conf` but until the node has joined the cluster, `crm_node -l` will report only its id. This configuration can even happen as a result of a previous incomplete `crm cluster join` run.
Two places that parse `crm_node -l` output in the bootstrap code are: in `setup_passwordless_with_other_nodes()` when setting up passwordless SSH, in `join_cluster()` when updating nodeids for IPv6. These functions can fail with `ValueError: not enough values to …

Fix: bootstrap: check for missing fields in 'crm_node -l' output (bsc#1182131)

---

crmsh/ui_resource.py
data-manifest
test/unittests/test_bugs.py
test/unittests/test_ratrace.py

* Split logic in `do_untrace()` into separate methods `_untrace_resource()`, `_untrace_op()` and `_untrace_op_interval()` in the same way how the trace logic is organized.
* When processing `untrace <rsc> <op>`, look up matching operations and remove the trace_ra flag from all of them. This deals with a situation when a stateful resource has two monitor operations, `trace <rsc> monitor` would set the trace_ra flag on both of them but a subsequent call to `untrace <rsc> monitor` would fail to remove these flags.
* When processing `untrace <rsc> probe`, search only for a monitor operation with interval="0". This improves consistency between `trace <rsc> probe` and `untrace <rsc> probe`. The trace variant always sets the trace_ra flag on a monitor operation with interval="0". The untrace …

Fix: resource: make untrace consistent with trace

---

crmsh/cibconfig.py
crmsh/parse.py

This is a fix PR to fix the regression came from #817
When previous cluster already has empty property before applying #817, like
```
node 1084783297: 15sp2-1
primitive stonith-sbd stonith:external/sbd \
params pcmk_delay_max=30s
property cib-bootstrap-options: \
have-watchdog=true \
dc-version="2.0.4+20200616.2deceaa3a-3.3.1-2.0.4+20200616.2deceaa3a" \
cluster-infrastructure=corosync \
cluster-name=hacluster \
stonith-enabled=true \
stonith-timeout=120 \
stonith-timeout
rsc_defaults rsc-options: \
resource-stickiness=1 \
migration-threshold=3
op_defaults op-options: \
timeout=600 \
record-pending=true
```
After applying #817, the output become mess
```
ERROR: syntax in property: Unknown arguments: stonith-timeout near <stonith-timeout> parsing 'property cib-bootstrap-options: …
```

Fix: parse: Should still be able to show the empty property if already exists

---

crmsh/cibconfig.py
crmsh/parse.py

[crmsh-4.3] Fix: parse: Should still be able to show the empty property if already exists

---

crmsh/ocfs2.py
test/unittests/test_ocfs2.py

[crmsh-4.3] Dev: ocfs2: set no-quorum-policy as freeze when configuring OCFS2

---

crmsh/ui_context.py
test/testcases/bugs.exp
test/testcases/confbasic.exp
test/testcases/history.exp
test/testcases/resource.exp

crmsh internally can correct some spell errors, like:
```
crm cluster ini   -->  crm cluster init
crm configure verfy --> crm configure verify
```
It will be helpful to add info when spell-corrections happen, like:
```
15sp2-1:~ # crm cluster ini
INFO: "ini" is accepted as "init"
15sp2-1:~ # crm configure
crm(live/15sp2-1)configure# verfy
INFO: "verfy" is accepted as "verify"
crm(live/15sp2-1)configure#
```

Dev: ui_context: Add info when spell-corrections happen

---

crmsh/ra.py
test/testcases/common.excl

Use --list-ocf-providers to check the crm_resource compatibility.
The --list-standards invokes systemd which takes quite some time.
Unfortunately, it doesn't seem like that will be fixed and, at any rate,
it's better to depend less on other system components.
This is no change in functionality, but a major improvement in
user experience. See #459 for more information.

Medium: ra: performance/usability improvement (avoid systemd)

---

crmsh/history.py
crmsh/utils.py
test/testcases/history.exp

[crmsh-4.1] Fix: history: use utils.mkdirp instead of system mkdir command

---

crmsh/history.py
crmsh/utils.py
test/testcases/history.exp

[crmsh-3.0] Fix: history: use utils.mkdirp instead of system mkdir command

---

doc/crm.8.adoc

[crmsh-4.3] Fix: doc: Note that resource tracing is only supported by OCF RAs

---

crmsh/constants.py
crmsh/utils.py
test/unittests/test_utils.py

* split into 3 functions for specific cloud type
* need to support non-Hyper-V in Azure case, see https://github.com/trento-project/trento/issues/194

Fix: utils: Improve detect_cloud function and support non-Hyper-V in Azure

---

crmsh/ui_resource.py
test/features/resource_set.feature
test/features/steps/step_implementation.py

- To support these format correctly:
```
crm resource move <res> <node>
crm resource move <res> <node> <lifetime>
crm resource move <res> <node> <lifetime> force
crm resource move <res> <lifetime> force
crm resource move <res> force
crm resource move <res> <node> force
```
- Add usage when more than 3 options after `<res>`
```
"usage: {} <rsc> [<node>] [<lifetime>] [force]".format(action)
```
- Remove move completer's option "reboot" and "forever"

Fix: ui_resource: Parse node and lifetime correctly

---

crmsh/cibconfig.py
crmsh/ocfs2.py
crmsh/utils.py
test/unittests/test_ocfs2.py
test/unittests/test_qdevice.py
test/unittests/test_utils.py

Changes:
- Give warning `The DLM cluster best practice suggests to set the cluster property \"no-quorum-policy=freeze\"` when commit,
while detecting `no-quorum-policy` not set as `freeze` when using DLM
- To avoid give above warning, adjust the code position to set no-quorum-policy as freeze when using ocfs2 stage to configure dlm+ocfs2 cluster
Related PR on pacemaker: https://github.com/ClusterLabs/pacemaker/pull/2583

Dev: Give warning when no-quorum-policy not set as freeze while using DLM

---

crmsh/constants.py
crmsh/idmgmt.py
crmsh/ui_node.py

In #797, standby/online part, there were issues:
- Can not handle and replace `false/no/n/0` value for standby
- standby nvpair could not contain node_id, then replace will not matched and failed
To avoid above issues:
- Not use re.sub to replace whole cib string
- Use xml query then `set` the value directly
Other than that:
- Avoid leading with number for xml ID
- Drop already standby/online check
- When doing standby, remove another type of lifetime standby

Dev: ui_node: Improve node standby/online methods

---

crmsh/ui_cluster.py

In #797, when doing actions to service like start/stop/enable/disable, 
or when doing actions to node like standby/online
function `parse_option_for_nodes` will return a node list, it'd better to check if each node is reachable, if not, remove that node from list

Dev: ui_cluster: Remove node from node list if node is unreachable

---

crmsh/bootstrap.py
crmsh/constants.py
crmsh/corosync.py
crmsh/crash_test/utils.py
crmsh/sbd.py
crmsh/utils.py
data-manifest
test/features/bootstrap_sbd_delay.feature
test/features/bootstrap_sbd_normal.feature
test/features/steps/step_implementation.py
test/unittests/test_bootstrap.py
test/unittests/test_corosync.py
test/unittests/test_crashtest_utils.py
test/unittests/test_sbd.py
test/unittests/test_utils.py

- Consolidate sbd timeout related methods/constants/formulas into class SBDTimeout
- Adjust stonith-timeout value, formulas are:
```
stonith-timeout >= 1.2 * (pcmk_delay_max + msgwait)  # for disk-based sbd
stonith-timeout >= 1.2 * max(stonith_watchdog_timeout, 2*SBD_WATCHDOG_TIMEOUT)  # for disk-less sbd
stonith-timeout >= max(STONITH_TIMEOUT_DEFAULT, token+consensus)  # for ALL situations
```
- Adjust SBD_DELAY_START value, formulas are:
```
SBD_DELAY_START = no # for non virtualization environment, which is the system default
SBD_DELAY_START >= (token + consensus + pcmk_delay_max + msgwait)  # for disk-based sbd
SBD_DELAY_START >= (token + consensus + 2*SBD_WATCHDOG_TIMEOUT) # for disk-less sbd
``` 
- Adjust pcmk_delay_max:
```
pcmk_delay_max=30 # only for the single stonith device in …
```

Dev: sbd: Adjust timeout related values

---

crmsh/bootstrap.py
crmsh/constants.py
crmsh/log.py
crmsh/ui_cluster.py
crmsh/utils.py
test/features/bootstrap_init_join_remove.feature
test/features/environment.py
test/features/steps/step_implementation.py
test/unittests/test_bootstrap.py
test/unittests/test_ui_cluster.py
test/unittests/test_utils.py

- Revert "Dev: ui_cluster: Make sure node is online when stop service"
Since to wait for node online when stopping cluster seems no make sense
- Dev: log: In status_long function, add a blank line when exception
To make the error message has more clear format
- Dev: ui_cluster: check dlm controld ra is running when stop cluster
When dlm controld is stopped, this time trying to stop cluster will cause error when trying to fetch dlm options
- Dev: ui_cluster: Exit stop process when there is no DC

Dev: ui_cluster: Improvement for stop process

---

crmsh/ui_node.py
test/docker_scripts.sh
test/features/bootstrap_bugs.feature
test/features/environment.py
test/testcases/common.excl
test/testcases/file.exp
test/testcases/ra.exp
test/testcases/resource.exp

- Change CI image as Tumbleweed
- Comment out hawk part in behave test since package not exist currently
- Adjust original test cases based on latest pacemaker and OCF 1.1
- When remove node, command `crm_node -R` might failed, if failed, remove that node from cib directly

Change master branch CI image as Tumbleweed

---

crmsh/bootstrap.py

When revisit the case, I think it's proper to just keep
```
The user 'hacluster' will have the login shell configuration changed to /bin/bash
```
Since each join node will show
```
Configuring SSH passwordless with hacluster@<node>
```
later

Fix: bootstrap: Change log info when need to change user login shell

---

crmsh/cibconfig.py
crmsh/cibverify.py
crmsh/completers.py
crmsh/rsctest.py
crmsh/ui_configure.py
crmsh/ui_resource.py
crmsh/xmlutil.py
test/crm-interface
test/testcases/confbasic.exp
test/testcases/file.exp
test/testcases/resource.exp

- For promotable clone resource, crmsh should find attribute promotable=true in xml
- Consider the compatibility, also keep the old way
- Give a deprecated warning when using "ms" subcommand

Fix: xmlutil: Parse promotable clone correctly and also consider compatibility

---

crmsh/bootstrap.py
crmsh/ui_cluster.py
test/features/bootstrap_options.feature
test/features/qdevice_usercase.feature
test/features/steps/const.py
test/features/steps/step_implementation.py
test/testcases/ra.exp

- Add `-U, --multicast` option for `crm cluster init` sub-command, to configure multicast
- `crm cluster init` will configure udpu cluster by default 
- Add functional test for the new added -U option

bootstrap: Change default transport type as udpu

---

crmsh/cibconfig.py
crmsh/config.py
crmsh/constants.py
crmsh/parse.py
crmsh/ra.py
crmsh/schema.py
crmsh/ui_configure.py
crmsh/ui_resource.py
crmsh/utils.py
crmsh/xmlutil.py
doc/crm.8.adoc
etc/crm.conf.in
test/features/qdevice_usercase.feature
test/features/resource_set.feature
test/testcases/ra.exp
test/unittests/test_utils.py

- Refactor `_prim_op_completer`, make it provide the correct role(Promoted/Unpromoted, or Master/Slave, depends on how RA written) to complete
```
crm(live/tbw-1)configure# primitive s ocf:pacemaker:Stateful op monitor 
depth=0           interval=10s      interval=11s      role=Promoted     role=Unpromoted   timeout=20s       
crm(live/tbw-1)configure# primitive s ocf:pacemaker:Stateful op monitor role=Promoted interval=10s op monitor 
depth=0           interval=10s      interval=11s      role=Promoted     role=Unpromoted   timeout=20s       
crm(live/tbw-1)configure# primitive s ocf:pacemaker:Stateful op monitor role=Promoted interval=10s op monitor role=Unpromoted interval=11s
```
```
crm(live/tbw-1)configure# primitive my ocf:heartbeat:mysql op monitor 
depth=0        interval=10s …
```

Support OCF 1.1 if desired

---

crmsh/crash_test/main.py

[crmsh-4.3] Fix: crash_test: Adjust help output of 'crm cluster crash_test -h'

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

Don't change pacemaker.service bootup preference when running `crm cluster start`

Fix: bootstrap: Don't change pacemaker.service bootup preference

---

.github/workflows/crmsh-ci.yml

To avoid this error inside container:
```
Feb 07 09:07:57 hanode1 systemd[1]: corosync.service: Failed to kill control group /system.slice/docker.service/system.slice/corosync.service, ignoring: Input/output error
Feb 07 09:07:57 hanode1 systemd[1]: corosync.service: Failed to kill control group /system.slice/docker.service/system.slice/corosync.service, ignoring: Input/output error
Feb 07 09:07:57 hanode1 systemd[1]: corosync.service: Failed to kill control group /system.slice/docker.service/system.slice/corosync.service, ignoring: Input/output error
Feb 07 09:07:57 hanode1 systemd[1]: corosync.service: Failed to kill control group /system.slice/docker.service/system.slice/corosync.service, ignoring: Input/output error
```

Dev: behave: Change docker cgroup driver as systemd

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

On interactive mode, when detect sbd already configured and input 'n', the sbd configure file shouldn't be overwritten

[crmsh-4.3] Fix: sbd: not overwrite SYSCONFIG_SBD and sbd-disk-metadata if input 'n'(bsc#1194870)

---

crmsh/cibconfig.py
crmsh/parse.py

[crmsh-4.1] Fix: parse: Should still be able to show the empty property if already exists

---

crmsh/utils.py
test/testcases/ra.exp

When using systemctl to check service status over ssh, such return codes  are normal:
```
0 | program is running or service is OK
1 | program is dead and /var/run pid file exists
2 | program is dead and /var/lock lock file exists
3 | program is not running
4 | program or service status is unknown
```
So non zero return code with some no harm stderr output from ssh(such as with ssh banner configured), will trigger the condition to raise exception

Fix: utils: Only raise exception when return code of systemctl command over ssh larger than 4

---

crmsh/utils.py

[crmsh-4.3] Fix: utils: Only raise exception when return code of systemctl command overssh larger than 4

---

crmsh/bootstrap.py
crmsh/lock.py
crmsh/qdevice.py
crmsh/ui_cluster.py
test/features/qdevice_setup_remove.feature
test/features/qdevice_validate.feature
test/unittests/test_bootstrap.py
test/unittests/test_lock.py
test/unittests/test_qdevice.py
test/unittests/test_ui_cluster.py

* Race condition might happen when multi cluster setup qdevice at the same time, include:
- init database on qnetd
```
Certificate database (/etc/corosync/qnetd/nssdb) already exists. Delete it to initialize new db
```
- qnetd sign the crq file while other cluster copy the new same name crq
* Not allow multi cluster with the same cluster name
* The crq and crt files on qnetd should be removed while removing qdevice
**Not allow multi cluster with the same cluster name:**
- During configuring qdevice process on this cluster, after setup passwordless between qnetd, special lock directory with cluster name should be created (like "/run/.crmsh_qdevice_lock_for_<cluster_name>")
- Raise error when finding cluster name directory exists on qnetd (like "/run/.crmsh_qdevice_lock_for_<cluster_name>") …

Improve for "one qnetd for multi cluster" scenario

---

crmsh/constants.py
crmsh/ui_resource.py
doc/crm.8.adoc
test/unittests/test_ratrace.py

By default all logs are stored in `/var/lib/heartbeat/trace_ra`
This patch adds a new resource attribute trace_dir to the `cib.file`
The `trace_dir` should come alongside the `trace_ra`,
whereas `trace_ra` signals that the resource is traced,
the `trace_dir` defines the path.

Dev: Parametrize the log dir

---

crmsh/constants.py
crmsh/ui_resource.py
doc/crm.8.adoc
test/unittests/test_ratrace.py

By default all logs are stored in /var/lib/heartbeat/trace_ra
This patch adds a new resource attribute trace_dir to the cib.file
The trace_dir should come alongside the trace_ra,
whereas trace_ra signals that the resource is traced,
the trace_dir defines the path.
(It's a backport of dadec52)

[crmsh-4.3] Dev: Parametrize the log dir

---

crmsh/corosync.py
crmsh/utils.py
hb_report/utillib.py
test/unittests/test_corosync.py

[crmsh-4.3] Fix: crm report: Read data in a save way, to avoid UnicodeDecodeError

---

crmsh/cibconfig.py
doc/crm.8.adoc

```
crm(live/tbw-1)configure# show related:Dummy
primitive d1 Dummy
primitive d2 Dummy
primitive d3 ocf:pacemaker:Dummy
crm(live/tbw-1)configure# show related:IPaddr2
primitive vip1 IPaddr2 \
params ip=10.10.10.123 \
op monitor interval=10s
primitive vip2 IPaddr2 \
params ip=10.10.10.124 \
op monitor interval=10s
crm(live/tbw-1)configure# show related:ocf:heartbeat:Dummy
primitive d1 Dummy
primitive d2 Dummy
```
Should be part of requirements from #698 and #819 
Others:

Dev: cinconfig: enable "related:" prefix to show the objects by given ra type

---

crmsh/parallax.py

It's too strict that raise exception when call/slurp/copy failed on some nodes, maybe it's better to pass the results to consumers, in this way, no interruption for other success ones.
For some key scenarios like bootstrap process, it's ok to keep strict when some nodes failed, to avoid inconsistent for the config files

Dev: parallax: Add strict option to avoid raise exception when set to False

---

crmsh/bootstrap.py
crmsh/ui_cluster.py
crmsh/utils.py
doc/crm.8.adoc
test/features/bootstrap_options.feature
test/features/steps/const.py
test/features/steps/step_implementation.py
test/unittests/test_bootstrap.py
test/unittests/test_utils.py

```
tbw-1:~ # crm cluster init -N tbw-1 -N tbw-2 -N tbw-3 -y
INFO: Loading "default" profile from /etc/crm/profiles.yml
INFO: SSH key for root does not exist, hence generate it now
INFO: SSH key for hacluster does not exist, hence generate it now
INFO: Configuring SSH passwordless with root@tbw-2
root@tbw-2's password: 
INFO: SSH key for root does not exist, hence generate it now
INFO: Configuring SSH passwordless with root@tbw-3
root@tbw-3's password: 
INFO: SSH key for root does not exist, hence generate it now
INFO: Configuring csync2
INFO: Generating csync2 shared key (this may take a while)...done
INFO: csync2 checking files...done
INFO: Configuring corosync (unicast)
WARNING: Not configuring SBD - STONITH will be disabled.
WARNING: Hawk not installed - not configuring web management …
```

Fix: bootstrap: -N option setup the current node and peers all together 

---

crmsh/bootstrap.py

This will cause `ERROR: Connection to remote host <nodename> failed.` to log.
And this is introduced since 96b5f8419, to avoid sync failed if configured files changed;
96b5f8419 should not be a problem anymore since e098387e2

Dev: bootstrap: Don't sync csync2 when peer node's csync2 service not ready

---

crmsh/bootstrap.py

[crmsh-4.3] Dev: bootstrap: Don't sync csync2 when peer node's csync2 service not ready

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

The ssh public key might not exist, which could impact on later steps for configuring passwordless between nodes.
Generate public key from private key if not exist
- No .ssh directory
- Already configured passwordless, without public key
- Only private key exists
- `-N` option

Dev: bootstrap: Generate public key from private key if not exist

---

crmsh/bootstrap.py
crmsh/parallax.py

crmsh.parallax will add StrictHostKeyChecking=no internally, can suppress the warning mentioned in bug 1202006

Fix: bootstrap: Use crmsh.parallax instead of parallax module directly

---

crmsh/bootstrap.py
crmsh/parallax.py

[crmsh-4.3] Fix: bootstrap: Use crmsh.parallax instead of parallax module directly

---

crmsh/bootstrap.py

[crmsh-4.4] Dev: bootstrap: Don't sync csync2 when peer node's csync2 service not ready

---

crmsh/bootstrap.py
crmsh/parallax.py

[crmsh-4.4]  Fix: bootstrap: Use crmsh.parallax instead of parallax module directly

---

crmsh/cibconfig.py
crmsh/ui_configure.py

cib_factory is cached in interactive `crm configure`. Refreshing before showing and modifying ensures concurrent commits to cib visible.

fix: configure: refresh cib before showing or modifying if no pending changes has been made (bsc#1202465)

---

crmsh/parallax.py
crmsh/ui_context.py
crmsh/utils.py

```
Job for corosync.service failed because the control process exited with error code.
See "systemctl status corosync.service" and "journalctl -xeu corosync.service" for details.
```
But in crmsh, don't raise any exception
```
Python 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from crmsh import utils
>>> utils.start_service('corosync.service', remote_addr="15sp4-2")
```
Revert 9cf075149412a757f7b1e527926922e34c9ce624.
Besides this,
- Dev: parallax: Add LogLevel=error ssh option to filter out warnings like ssh banner message
- Dev: ui_context: remove duplicated codes

Fix: utils: raise exception when failed to run command remotely

---

crmsh/bootstrap.py
crmsh/log.py

The console format will mass if there are messages during status_long:
```
INFO: BEGIN Starting pacemaker(delaying start of sbd for 71s) ...INFO: This is demo log
...........done
```
After applied this PR when succeeded:
```
INFO: BEGIN Starting pacemaker(delaying start of sbd for 71s) ...
INFO: This is demo log.
INFO: END Starting pacemaker(delaying start of sbd for 71s).
```
When failed:
```
INFO: BEGIN Starting pacemaker(delaying start of sbd for 71s) ...
INFO: This is demo log.
ERROR: FAIL Starting pacemaker(delaying start of sbd for 71s).
ERROR: cluster.start: Failed on ha-cluster-1: Exited with error code 1, Error output: Failed to start pacemaker.service: Unit pacemaker.service is masked.
```

Dev: log: print begin and end marker in different lines in status_long

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

[crmsh-4.4] Dev: bootstrap: Show remote node name when stopping service remotely

---

crmsh/bootstrap.py
crmsh/sbd.py
test/unittests/test_sbd.py

1. refactor `SBDTimeout` so that it can be calculated without calling `init_sbd` first.
2. add `remote_auth` to the list of init stages so that authkey for pacemaker can be created.

fix initializing a cluster step by step

---

crmsh/bootstrap.py
crmsh/ui_cluster.py
crmsh/utils.py
test/unittests/test_bootstrap.py
test/unittests/test_ui_cluster.py
test/unittests/test_utils.py

To avoid possible JOIN flood in corosync

Dev: bootstrap: Add delay to start corosync when node list larger than 5

---

crmsh/crash_test/main.py
crmsh/crash_test/task.py
test/unittests/test_crashtest_task.py

Removing ports from firewalld zone will not break established connections.

Fix: crash_test: do not use firewalld to isolate a cluster node

---

crmsh/bootstrap.py
crmsh/sbd.py
test/features/bootstrap_sbd_delay.feature

* After adding qdevice via stage on a running cluster with sbd running, the parameter `pcmk_delay_max` is useless and should be removed
* After removing qdevice from a two-node cluster with sbd running, the parameter `pcmk_delay_max` should be added

Dev: bootstrap: Adjust sbd related timeout when add/remove qdevice

---

crmsh/cibconfig.py
doc/crm.8.adoc

```
crm(live/15sp4-1)configure# show related:ocf
primitive d Dummy
primitive vip IPaddr2 \
params ip=10.10.10.125
crm(live/15sp4-1)configure# show related:stonith
primitive stonith-sbd stonith:external/sbd \
params
primitive ttt stonith:rps10 \
params pcmk_delay_max=30 serial_to_targets=sf
primitive xxx stonith:fence_eps \
params pcmk_delay_base=10
crm(live/15sp4-1)configure# show related:ip
primitive vip IPaddr2 \
params ip=10.10.10.125
```

Dev: cibconfig: "crm config show related:xxx" provides partial search among class, provider, type fields

---

crmsh/history.py
crmsh/report/constants.py
crmsh/report/core.py

`crm -d report` and `crm -d history peinputs` cannot print report debug messages
- Dev: report: make sure 'crm -d report' could increase the verbosity
(equal to `crm report -v`)
- Dev: history: print necessary log messages when collecting report

Dev: report: make sure 'crm -d report' could increase the verbosity

---

Dockerfile
crmsh.spec.in
crmsh.tmpfiles.d.conf
crmsh/log.py

The file had been created with umask 0022 in usual so that it was not group-writable.
Call chown and chmod explicitly to fix it.

fix: fail to open log file even if user is in haclient group (bsc#1204670)

---

Dockerfile
crmsh.spec.in
crmsh.tmpfiles.d.conf
crmsh/log.py
test/testcases/ra.exp

The file had been created with umask 0022 in usual so that it was not
group-writable.
Call chown and chmod explicitly to fix it.

[crmsh-4.4] fix: fail to open log file even if user is in haclient group (bsc#1204670)

---

crmsh/report/collect.py
crmsh/utils.py
test/features/crm_report_bugs.feature
test/features/steps/step_implementation.py

After #939 , if user specify other directory to trace ra log, crm report can't collect the log
Since the "trace_dir" attribute will be removed from cib after untrace, crm report need to parse crmsh.log to extract custom trace ra log directory on each node
```
@clean
Scenario: crm report collect trace ra log
When    Run "crm configure primitive d Dummy" on "hanode1"
And     Run "crm configure primitive d2 Dummy" on "hanode1"
Then    Resource "d" is started on "hanode1"
And     Resource "d2" is started on "hanode2"
When    Run "crm resource trace d monitor" on "hanode1"
Then    Expected "Trace for d:monitor is written to /var/lib/heartbeat/trace_ra/Dummy" in stdout
When    Wait "10" seconds
And     Run "crm resource untrace d" on "hanode1"
And     Run "crm resource trace d2 monitor …
```

Dev: report: collect ra trace files from specified directories

---

test/features/bootstrap_options.feature
test/run-functional-tests

related issue #962 
- Deploy containers and remove containers in parallel
- Improve info messages
- Set stonith-enabled=false after setup cluster
```
INFO: Loading docker image liangxin1300/haleap:15.4...
INFO: Create ha specific docker network "ha_network_first"...
INFO: Create ha specific docker network "ha_network_second"...
INFO: Setup cluster...
INFO: Deploying "hanode1"...
INFO: Deploying "hanode2"...
INFO: Building crmsh on "hanode1"...
INFO: Building crmsh on "hanode2"...
INFO: Copy corosync.conf to hanode1 hanode2
INFO: Cluster service started on "hanode1"
INFO: Cluster service started on "hanode2"
```

Dev: run-functional-tests: Deploy and remove containers in parallel

---

.github/workflows/crmsh-ci.yml
crmsh/bootstrap.py
crmsh/healthcheck.py
crmsh/main.py
crmsh/upgradeutil.py
crmsh/utils.py
data-manifest
test/crm-interface
test/features/healthcheck.feature
test/features/steps/step_implementation.py
test/unittests/test_healthcheck.py
test/unittests/test_upgradeuitl.py
test/unittests/test_utils.py

* add a mechanism for updating cluster config after version update:
- A sequence is written to `~hacluster/crmsh/upgrade_seq` and crmsh checks it to determine whether upgrade is needed whenever it runs.
- Upgrade is performed only when all nodes in cluster are running compatible version of crmsh. It is determined by comparing `CURRENT_UPGRADE_SEQ` in upgradeutil.py.
- Upgrade needs user confirm and is only performed in interactive mode.
* add health check and fix for passwordless ssh authentication for hacluster
* run health fix for passwordless ssh authentication for hacluster when with that upgrade mechanism
* run health fix for passwordless ssh authentication for hacluster when a node fails to join the cluster because of it
Upgrade is performed in the following scenarios:
1. Running …

Fix: ha-cluster-join fails to add nodes to a existing cluster after the version update (bsc#1201785)

---

crmsh/corosync.py

[crmsh-4.4] Fix: corosync: show corosync ring status if has fault

---

crmsh/log.py

As the workaround for remove the whole prompt line when delete characters; 
And the prompt line should be treated as an input action hints, not a info log; 
Related information still be recorded into the log file

Dev: log: Use original way for the prompt input

---

crmsh/cibconfig.py
crmsh/parse.py
crmsh/xmlutil.py
test/features/resource_set.feature
test/testcases/bugs.exp
test/testcases/confbasic-xml.exp
test/testcases/confbasic.exp
test/testcases/file.exp
test/testcases/resource.exp

When configure Promoted/Unpromoted resource, "promotable=true" is required and "interleave=true" is often
preferred.
So the solution is to complete this meta attribute.
Possible cases:
- input like `clone <clone-id> <res-id>`
If detected this primitive resource contain "promote" and "demote" actions,
then "meta promotable=true interleave=true" will be completed
- if the input contain `promotable` or `interleave`
then crmsh doesn't complete it
```
crm(live/15sp4-1)configure# primitive stateful-1 ocf:pacemaker:Stateful
crm(live/15sp4-1)configure# clone c1 stateful-1
crm(live/15sp4-1)configure# show
node 1: 15sp4-1
node 2: 15sp4-2
primitive stateful-1 ocf:pacemaker:Stateful \
op monitor timeout=20s interval=10s role=Promoted \
op monitor timeout=20s interval=11s role=Unpromoted \
op start …
```

Fix: cibconfig: Complete promotable=true and interleave=true for Promoted/Unpromoted resource

---

crmsh/qdevice.py

When using `crm cluster init` to configure diskless-sbd + qdevice, on interactive mode, `SBD_WATCHDOG_TIMEOUT` in /etc/sysconfig/sbd is not as expected as `SBD_WATCHDOG_TIMEOUT = quorum.device.sync_timeout  + 5`, will lead to situation where pacemaker fails to start
When running `crm cluster init` to configure diskless-sbd and qdevice,the sequence will be:
- configure diskless-sbd
- cluster service started
- configure qdevice; On this time, qdevice is not in the 'qdevice' stage,
so this piece of code (function adjust_sbd_watchdog_timeout_with_qdevice) will not be executed to adjust SBD_WATCHDOG_TIMEOUT

Fix: qdevice: Adjust SBD_WATCHDOG_TIMEOUT when configuring qdevice not using stage

---

crmsh/log.py
crmsh/qdevice.py

[crmsh-4.4] Fix: qdevice: Adjust SBD_WATCHDOG_TIMEOUT when configuring qdevice not using stage

---

crmsh/bootstrap.py
test/features/qdevice_validate.feature
test/unittests/test_bootstrap.py

[crmsh-4.3] Fix: qdevice: Adjust SBD_WATCHDOG_TIMEOUT when configuring qdevice not using stage 

---

crmsh/bootstrap.py
crmsh/qdevice.py
crmsh/sbd.py
test/unittests/test_bootstrap.py
test/unittests/test_qdevice.py
test/unittests/test_sbd.py

On interactive mode, when configuring qdevice with mistake, crmsh exit immediately.
crmsh ui should let user input again, until get the right input
So, the method `qdevice.QDevice.valid_qdevice_options` should be refactored

Dev: qdevice: Refactor qdevice validation code

---

crmsh/bootstrap.py
crmsh/constants.py
crmsh/sbd.py
crmsh/ui_cluster.py
crmsh/utils.py
test/features/bootstrap_options.feature
test/features/steps/const.py
test/unittests/test_bootstrap.py
test/unittests/test_sbd.py
test/unittests/test_utils.py

On some environments, the csync2 initialization process consumes too much time comparing to the whole cluster bootstrap process, and could be blamed as too slow. csync2 is not the critical component for the cluster stack. Adding an option to skip that could make it flexible to give users a choice, and users can initialize csyn2 for the cluster later on if need
Another bad situations did happen in the past, csync2 was broken because of its dependency, eg. gnutls bsc#1172695. This functionality gives the flexibility to provide the workaround to setup the cluster without csync2.
- On init side, add `-x` option to skip csync2 configure and sync; Or, can set environment variable 'SKIP_CSYNC2_SYNC=true' on init node:
```
crm cluster init -x -y
```
- Based on above, use scp to retrieve all …

Dev: bootstrap: Add option -x to skip csync2 initialization stage during the whole cluster bootstrap

---

crmsh/report/utillib.py

Fenced node could leave a zero byte length .xz file (which is not a file in xz format), which will raise EOFError while crm report trying to read it. So, it will be helpful to catch the exception while reading and make sure report process continues.

Fix: report: Catch read exception

---

crmsh/qdevice.py
test/unittests/test_qdevice.py

When configuring sbd and qdevice together like `crm cluster init -s <sbd> --qnetd-hostname <qnetd> -y`, corosync-qdevice.service will not start
According to the logic of `evaluate_qdevice_quorum_effect`, after configured sbd and cluster started, there is an RA(external/sbd) running, at this time, to use qdevice service, need to restart cluster later
When adding qdevice and not in qdevice stage, this means that qdevice is added from the beginning at init node. It's safe to restart the cluster, regardless of whether there is RA running or not.

Dev: qdevice: Adjust qdevice reload policy

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

On a 2-node cluster with sbd configured, start the cluster using "crm cluster start" on the first node and get a fence action for the second which was planned to enter the cluster a bit later
Just drop-in a volatile sbd service snippet to unset SBD_DELAY_START, when running "crm cluster start"
```
mkdir /run/systemd/system/sbd.service.d/
cat << EOF > /run/systemd/system/sbd.service.d/sbd_delay_start_disabled.conf
[Service]
UnsetEnvironment=SBD_DELAY_START
EOF
systemctl daemon-reload
```

Fix: bootstrap: Unset SBD_DELAY_START when running 'crm cluster start'

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

[crmsh-4.4] Fix: bootstrap: Unset SBD_DELAY_START when running 'crm cluster start'

---

crmsh/healthcheck.py
crmsh/upgradeutil.py
crmsh/utils.py

When crmsh is running in a background process group, for example,
```
crm status &
```
and upgradeutil tries to ask for user confirm, it will block until crmsh is brought to foreground (with fg).
However, configuration upgrading is not a critical operation, and it is better not to block when running in background.
When current process is not in the foreground process group, do not ask and skip the upgrade.
Close #1102.

Dev: upgradeutil: do not ask when running in a background process group

---

crmsh/ui_cluster.py
test/unittests/test_ui_cluster.py

s/Cluster services/The cluster stack/
To clarify that it starts/stops the whole stack, both resource agents and systemd pacemaker/corosync.service/services.
Related issue #413

Dev: ui_cluster: Improve cluster start/stop INFO

---

crmsh/bootstrap.py
crmsh/config.py
crmsh/corosync.py
crmsh/lock.py
crmsh/parallax.py
crmsh/qdevice.py
crmsh/sbd.py
crmsh/ui_cluster.py
crmsh/upgradeutil.py
crmsh/utils.py
crmsh/watchdog.py
crmsh/xmlutil.py
data-manifest
test/features/bootstrap_bugs.feature
test/features/bootstrap_init_join_remove_alice.feature
test/run-functional-tests
test/unittests/test_bootstrap.py
test/unittests/test_corosync.py
test/unittests/test_lock.py
test/unittests/test_parallax.py
test/unittests/test_qdevice.py
test/unittests/test_sbd.py
test/unittests/test_utils.py
test/unittests/test_watchdog.py

It enables creating the cluster under a custom user
Assume the users are alice@node1 and non@node2.
1) Bring the alice into sudoers file on the node1
and bob on the node2
for example
`$ sudo echo "alice ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers`
(use `visudo` rather than echo)
2) add /usr/sbin to the PATH for alice and bob (writ it in the ~/.bashrc)
`$ export PATH=$PATH:/usr/sbin`
And now you can do the usual routines under alice
```
alice@node1$ crm cluster init -y
bob@node2$ crm cluster join -c alice@node1 -y
or
alice@node1$ crm cluster init -N bob@node2 -y
```
The crm will start as a usual process with the same context as the
current user (alice/bob). However when it would lack permissions
for example to read/write file it would try again as the super-user.

Feature: replace root by a custom user with root privileges

---

doc/crm.8.adoc
doc/website-v1/man-2.0.adoc
doc/website-v1/man-3.adoc
doc/website-v1/man-4.3.adoc

The lintian QA tool reported a spelling error for the Debian package build:
* typoes -> typos

Fix spelling errors.

---

crmsh/ui_utils.py

crmsh fails with Python 3.11:
```
Traceback (most recent call last):
File "/usr/sbin/crm", line 35, in <module>
from crmsh import main
File "/usr/lib/python3/dist-packages/crmsh/main.py", line 17, in <module>
from . import ui_root
File "/usr/lib/python3/dist-packages/crmsh/ui_root.py", line 201, in <module>
Root.init_ui()
File "/usr/lib/python3/dist-packages/crmsh/command.py", line 503, in init_ui
prepare(children, child, aliases)
File "/usr/lib/python3/dist-packages/crmsh/command.py", line 488, in prepare
info = ChildInfo(child, cls)
^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/crmsh/command.py", line 558, in __init__
self.children = self.level.init_ui()
^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/crmsh/command.py", line 503, in init_ui
prepare(children, …
```

Don't use inspect.getargspec, removed in Python 3.11.

---

.github/workflows/crmsh-ci.yml
crmsh/ui_context.py
crmsh/utils.py
data-manifest
test/features/bootstrap_bugs.feature
test/features/user_access.feature
test/run-functional-tests
test/unittests/test_utils.py

-  When running bootstrap interface
```
hanode1:/ # useradd -m -s /bin/bash -N -g 90 xin1
hanode1:/ # su xin1 -c 'crm cluster init -y'
ERROR: Please run this command starting with "sudo".
Currently, this command needs to use sudo to escalate itself as root.
Please consider to add "xin1" as sudoer. For example:
echo "xin1 ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/xin1
hanode1:/ # echo "xin1 ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/xin1
hanode1:/ # su xin1 -c 'crm cluster init -y'
ERROR: Please run this command starting with "sudo"
```
- When running ACL(pacemaker cib related) interface
```
hanode1:/ #id xin1
uid=1003(xin1) gid=90(haclient) groups=90(haclient)
hanode1:/ # su xin1 -c 'crm node standby'
INFO: standby node hanode1
```
- When running bootstrap interface
```
hanode1:/ # useradd …
```

Dev: utils: Check current user's privilege and give hints to user

---

crmsh/bootstrap.py
crmsh/constants.py
crmsh/healthcheck.py
crmsh/parallax.py
crmsh/upgradeutil.py
test/features/healthcheck.feature
test/unittests/test_bootstrap.py
test/unittests/test_healthcheck.py

The mechanism of prepending `sudo` automatically provided by
`get_stdout_or_rasie_error` do not work in early bootstrap stage.
Prepend sudo manually instead.

 Dev: bootstrap: implement swapping hacluster's ssh key using non-root sudoer remote access

---

scripts/cryptctl/main.yml
test/testcases/scripts.exp

as the result the dropdown wizards in the configuration menu (https://127.0.0.1:7630/cib/live/wizards) don't work.

Fix: hawk fails to parse the slash (bsc#1206217)

---

crmsh/bootstrap.py
crmsh/corosync.py
crmsh/lock.py
crmsh/main.py
crmsh/parallax.py
crmsh/ui_cluster.py
crmsh/userdir.py
crmsh/utils.py
crmsh/watchdog.py
test/unittests/test_bootstrap.py
test/unittests/test_corosync.py
test/unittests/test_lock.py
test/unittests/test_parallax.py
test/unittests/test_utils.py

Many servers do not permit root to login from ssh for enhanced security.
This change enable crmsh to operate the cluster with this setup.
The implementation is to do most of work as root, and su to a non-root user,
which is only used for ssh login, only when a command is needed to be executed
on a remote node. The remote command is executed in a `sudo /bin/sh` shell, so
it also has privilege.
This relies on crmsh being called with sudo, so that crmsh will be able to
determine which non-root user to su to when it needs to create a ssh
session. When crmsh is not called with sudo, it should work the same way
as before.

Dev: bootstrap: allow the cluster to operate with ssh session under non-root sudoer (jsc#PED-290)

---

crmsh/report/core.py
crmsh/report/utillib.py

When running `crm report` under a sudoer user,
crmsh will try to use this sudoer user to ssh to the peer node when collecting report.

Dev: report: Enable crm report for sudoer user

---

crmsh/cibconfig.py
crmsh/history.py
crmsh/log_patterns.py
crmsh/main.py
crmsh/ui_configure.py
crmsh/ui_node.py
crmsh/utils.py
crmsh/xmlutil.py

- Use '/usr/sbin/pacemakerd --version'
- Raise fatal error if failed to get pacemaker's version
- Remove unused codes

Dev: utils: Change the way to get pacemaker's version

---

crmsh/utils.py

After #1130 , the output of ssh-copy-id could be suppressed, but also the prompt `Password` under non-root user.
With this commit, both root and non-root case could have `Password` prompt message
```
15sp4-2:~ # crm cluster join -c 15sp4-1 -y
INFO: SSH key for root does not exist, hence generate it now
INFO: Configuring SSH passwordless with root@15sp4-1
Password:
```
```
xin@15sp4-2:~> sudo crm cluster join -c 15sp4-1 -y
INFO: SSH key for xin does not exist, hence generate it now
INFO: Configuring SSH passwordless with xin@15sp4-1
Password: 
INFO: SSH key for hacluster does not exist, hence generate it now
```

Dev: utils: Suppress the output of ssh-copy-id for non-root user case

---

crmsh/bootstrap.py
crmsh/corosync.py
crmsh/qdevice.py
crmsh/utils.py
test/unittests/test_bootstrap.py
test/unittests/test_qdevice.py

* When --qnetd-hostname is provided as "user@host", use the specified user
* When --qnetd-hostname is provided as "host", use the same username as the local user

Fix: qdevice: Unable to setup qdevice under non-root user (bsc#1208770)

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

Or will got error:
```
xin@hanode2:~> sudo crm cluster join -c hanode1 -y
INFO: SSH key for xin does not exist, hence generate it now
INFO: Configuring SSH passwordless with xin@hanode1
Password: 
INFO: SSH key for hacluster does not exist, hence generate it now
ERROR: cluster.join: Can't fetch cluster nodes list from hanode1: error: Could not connect to controller: Permission denied
```

Dev: bootstrap: Add sudo before crm_node under non-root user on remote node

---

crmsh/log.py
crmsh/main.py
crmsh/utils.py
data-manifest
test/features/qdevice_validate.feature
test/features/resource_set.feature
test/features/steps/step_implementation.py
test/features/steps/utils.py
test/testcases/confbasic-xml.filter

- Dev: log: Redirect debug messages into stderr
If keep debug and info messages all in stdout, then some scripts that need to handle or analyze the output of the crm command might be messy.
- Dev: bootstrap: Don't save core.debug when saving core.hosts

Dev: log: Redirect debug messages into stderr

---

crmsh/bootstrap.py
crmsh/upgradeutil.py
crmsh/utils.py

And also backport 082e9b8fbfb86bc5b3c03c0a9c5853e4cd581ec4(Dev: upgradeutil: do upgrade silently (bsc#1208327)) from master.

[crmsh-4.4] Fix: healthcheck: do not run automatic upgrade when crmsh is called by a non-root user (bsc#1208936)

---

crmsh/log.py
crmsh/parallax.py
crmsh/qdevice.py
test/unittests/test_parallax.py
test/unittests/test_qdevice.py

Or, some commands like `rm -rf /etc/corosync/qdevice/net/*` might fail.
Also add more debug messages when configuring qdevice.

Fix: parallax: Use 'sudo bash -c' when executing commands via sudoer (bsc#1209192)

---

crmsh/corosync.py
crmsh/healthcheck.py
crmsh/parallax.py
crmsh/qdevice.py
crmsh/utils.py
test/unittests/test_corosync.py
test/unittests/test_parallax.py
test/unittests/test_utils.py

In the following scenario, `user_of()` is not able to get a user from
`core.hosts`:
1. In the early stage of cluster node initialization
2. When a cluster is upgraded from a previous version
3. Called by external code, for example, the behave test
`user_of()` uses to return `$SUDO_USER` if it exists, or return the
current user if it doesn't. However, this breaks the following use case:
* A cluster is upgraded from a previous version and users operate it
with sudo
In this case, `user_of()` returns `$SUDO_USER`, but `root` is expected.
This commit consists of the following changes:
1. `user_of()` returns `None` when it is not able to get a user from
`core.hosts`. It is expected to be used only in early stage of
initialization.
2. After the early stage of intialization, when an SSH session …

Fix: validate ssh session when the users is determined by guessing (bsc#1209193)

---

.github/workflows/crmsh-ci.yml
Dockerfile
test/features/bootstrap_sbd_normal.feature
test/testcases/node.exp
test/testcases/ra.exp
test/testcases/resource.exp

I found the resource failcount number is inconsistent, on pacemaker-2.1.2+20211124.ada5c3b36-150400.4.9.2.x86_64
Here is the trigger script:
```
crm cluster init -y &> /dev/null
echo "Info: Cluster is running..."
crm configure primitive d Dummy op monitor interval=3s &> /dev/null
echo "Info: Add resource d(Dummy)"
while :
do
echo "Info: Remove /run/resource-agents/Dummy-d.state"
rm -f /run/resource-agents/Dummy-d.state
sleep 15
echo "Info: Show failcount"
echo "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
crm resource failcount d show `hostname`
echo "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
echo "Info: Set failcount to 0"
crm resource failcount d set `hostname` 0
echo "Info: Restart resource d"
crm resource stop d
crm resource start d
sleep 5
done
```
Here are the results:
```
Info: Cluster is running...
Info: …
```

Add test case resource_failcount.feature back after upgrade pacemaker version

---

crmsh/healthcheck.py
crmsh/upgradeutil.py
crmsh/utils.py
test/features/bootstrap_bugs.feature
test/features/steps/step_implementation.py
test/unittests/test_utils.py

When cluster nodes not configured passwordless for both root and hacluster, crmsh will give a warning each time it runs any crm commands such as:
```
WARNING: SSH connection to remote node 15sp4-2 failed.
parallax.Error: Exited with error code 255, Error output: parallax error: SSH requested a password. Please create SSH keys or
use the -A option to provide a password.
parallax error: SSH requested a password. Please create SSH keys or
use the -A option to provide a password.
root@15sp4-2: Permission denied (publickey,password,keyboard-interactive).
```
Add function crmsh.utils.check_passwordless_between_nodes.
Return a list of hosts that require passwords between.
Call it when detected the hacluster passwordless was not configured:
```
if nodes and _is_upgrade_needed(nodes) and not …
```

Dev: utils: Check passwordless between cluster nodes

---

crmsh/report/utillib.py

Without this patch the hb_report will crash trying to reach out to the offline nodes.

Fix: crm report: sustain if there are offline nodes (bsc#1209480)

---

.github/workflows/crmsh-ci.yml

Remember to revert this commit after failcount number inconsistent issue fixed

[crmsh-4.4] Dev: workflows: Disable resource_failcount.feature temporarily

---

crmsh/bootstrap.py
crmsh/corosync.py
crmsh/lock.py
crmsh/qdevice.py
crmsh/utils.py
test/unittests/test_bootstrap.py
test/unittests/test_corosync.py
test/unittests/test_lock.py
test/unittests/test_qdevice.py

And `configure_ssh_key()` should be called prior to `ssh_copy_id()` to ensure there exists a key pair to be copy.

Fix: utils: qdevice initialization should user_pair_for_ssh() to get appreciated users (crmsh#1157)

---

crmsh/cibconfig.py
crmsh/utils.py

When cib schema version support OCF 1.1 and set `OCF_1_1_SUPPORT = yes` in /etc/crm/crm.conf, if origin cib configuration contain original Master/Slave for role, command `crm configure show` will be messy:
```
crm(live/15sp4-1)configure# show
INFO: Convert deprecated "Master" to "Promoted"
node 1: 15sp4-1
node 2: 15sp4-2
xml <primitive id="st" class="ocf" provider="pacemaker" type="Stateful"> \
<operations> \
<op name="monitor" role="Master" interval="10s" timeout="20s" id="st-monitor-10s"/> \
<op name="start" timeout="20s" interval="0s" id="st-start-0s"/> \
<op name="stop" timeout="20s" interval="0s" id="st-stop-0s"/> \
<op name="promote" timeout="10s" interval="0s" id="st-promote-0s"/> \
<op name="demote" timeout="10s" interval="0s" id="st-demote-0s"/> \
</operations> \
</primitive>
``` …

Dev: utils: add auto_convert_role flag for handle_role_for_ocf_1_1 function

---

crmsh/bootstrap.py
crmsh/sbd.py
crmsh/ui_cluster.py
crmsh/xmlutil.py
test/features/bootstrap_sbd_normal.feature
test/features/steps/const.py
test/unittests/test_bootstrap.py
test/unittests/test_xmlutil.py

- Originally, `crm cluster init sbd -s <device> -y` can add sbd configuration and sbd service into a running cluster
- Then, if want to re-deploy sbd or replace sbd device, `crm cluster init sbd -s <device> -y` will get error:
```
ERROR: cluster.init: Cannot configure stage sbd: sbd.service already running!
```
```
ERROR: cluster.init: Can't configure stage sbd: sbd.service already running! Please use crm option '-F' if need to redeploy
```
Change disk-based SBD as disk-less SBD
```
INFO: Loading "default" profile from /etc/crm/profiles.yml
WARNING: Diskless SBD requires cluster with three or more nodes. If you want to use diskless SBD for 2-node cluster, should be combined with QDevice.
INFO: Configuring diskless SBD
INFO: Restarting cluster service
INFO: BEGIN Waiting for cluster …
```

Dev: bootstrap: Support replacing sbd device via sbd stage

---

crmsh/report/utillib.py

Without this patch, the hb_report will crash trying to reach out to the offline nodes. (backport)

[crmsh-4.4] Fix: crm report: sustain if there are offline nodes (bsc#1209480)

---

crmsh/bootstrap.py
crmsh/cibconfig.py
crmsh/xmlutil.py

This is the cib configuration after crmsh setup a cluster:
```
node 1: 15sp4-1
node 2: 15sp4-2
property cib-bootstrap-options: \
have-watchdog=false \
dc-version="2.1.2+20211124.ada5c3b36-150400.4.9.2-2.1.2+20211124.ada5c3b36" \
cluster-infrastructure=corosync \
cluster-name=hacluster \
stonith-enabled=false
rsc_defaults build-resource-defaults: \
resource-stickiness=1
rsc_defaults rsc-options: \
migration-threshold=3
op_defaults op-options: \
timeout=600 \
record-pending=true
```
The id "build-resource-defaults" was introduced from pacemaker.
This is the text configuration:
```
property \
stonith-enabled="true" \
stonith-action="reboot" \
stonith-timeout="150s"
rsc_defaults \
resource-stickiness="1000" \
migration-threshold="5000"
op_defaults \
timeout="600"
```
Now load it
```
crm …
```

Fix: cibconfig: use any existing rsc_defaults set rather than create another one

---

crmsh/bootstrap.py
crmsh/lock.py
test/features/bootstrap_bugs.feature
test/unittests/test_lock.py

This issue was introduced since
69b18cdb7e37581c0e3173b86bb6dde5f16b6ab0.
The join node cannot be excluded because it uses a different lock directory.

Fix: lock: Join node failed to wait init node finished (bsc#1210332)

---

crmsh/bootstrap.py
crmsh/ui_cluster.py
crmsh/utils.py
test/features/steps/const.py
test/unittests/test_bootstrap.py

Problem
=======
In previous versions, `sudo crm cluster join -c <host>` use user root
for ssh sessions. However, in crmsh 4.5.0, the sudoer user is used. This
change in default behavior may break existing scripts.
Solution
========
Keep the default behavior unchanged and require using `sudo crm cluster
join -c <user>@<host>` to authenticate as a non-root user.

 Fix: bootstrap: crm cluster join default behavior change in ssh key handling (bsc#1210693)

---

test/features/bootstrap_bugs.feature
test/features/steps/utils.py

- Expected cluster setup via root ssh key by default
- Add \<user\>@ when joining for non-root case

Dev: behave: Add functional test for bsc#1210693

---

crmsh/bootstrap.py

The previous implementation fails to fallback to the current user, when user is neither specified in command line arguments nor saved in `core.hosts`.

Fix: bootstrap: `init --qnetd-hostname` fails when username is not specified (bsc#1211200)

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

 Fix: bootstrap: failed to save username for localhost when initializing a cluster with a qnet server

---

.github/workflows/crmsh-ci.yml

- Since the code will change dramatically, unit_test is temporarily disabled.
- Since submit to network:ha-clustering:Factory will
break down current functionality for corosync2, submit job is temporarily
disabled; When the corosync3 package is available, enable this job again.

Dev: workflows: Temporarily disabled unit_test and submit job

---

.github/workflows/crmsh-ci.yml

Fix for #1185 , which unit_test was skipped, then delivery job wouldn't trigger.

Dev: workflows: Temporarily remove unit_test from needs list for delivery job

---

crmsh/bootstrap.py

Or running `ssh_copy_id` will fail if no ssh key exists

Dev: bootstrap: Configure ssh key when fetch geo config

---

crmsh/corosync.py
crmsh/ui_corosync.py
crmsh/utils.py
doc/crm.8.adoc

Remove `corosync add-node` and `corosync del-node` because:
- `corosync add-node` and `corosync del-node` will make corosync.conf inconsistent if forget to sync manually, 
- And should be useless under knet case since it only supports one link

Dev: ui_corosync: Remove add-node and del-node subcommands

---

crmsh/bootstrap.py
crmsh/utils.py
data-manifest
test/features/bootstrap_bugs.feature
test/features/environment.py
test/features/steps/behave_agent.py
test/features/steps/step_implementation.py
test/features/steps/utils.py
test/run-functional-tests
test_container/Dockerfile
test_container/behave-agent.socket
test_container/behave-agent@.service
test_container/behave_agent.py

It is expected that crmsh uses the current user only unless another user
is specified explicitly. However, the code in functional tests needs operate
with different users to cover different use cases, requiring a complex
procedure to choose a user.
1. A standalone agent is used to running command in functional test. It is
used only in function test, so the test code and production code is decoupled.
Close #1182.
2. With the above changes, the user-selecting procedure is simplified in
production code. And several subcommands are found depending on the old
procedure and falls back to sudoer user implicitly when the current user fails
to create ssh session. This implicit fallback behavior is removed, the affected
subcommands are:
* `crm cluster init qdevice --qnetd-hostname <host>`
* `crm …

 Dev: behave: use a standalone agent instead of crmsh.parallax to run commands

---

crmsh/bootstrap.py
crmsh/healthcheck.py
crmsh/ui_cluster.py
crmsh/upgradeutil.py
test/features/steps/const.py
test/unittests/test_bootstrap.py

These options should be able to input interactively on prompt. So
they are not required to present in command line args and the
parsing should be deferred.

Fix: bootstrap: fix the validation of option -N and -c (bsc#1212436) 

---

.github/workflows/crmsh-ci.yml
codecov.yml
data-manifest
test/features/coveragerc
test/run-functional-tests
test/testcases/resource.exp
test_container/Dockerfile

Collect coverage data by patching the entrance file `/usr/sbin/crm` and use codecov.io to collect and combine the result from concurrent runs of different tests.

Dev: behave: add coverage and codecov.io for behave tests

---

.github/workflows/crmsh-ci.yml
crmsh/ui_context.py

Subcommands do not always return a value, but an exception is always raised when there is an error.

Fix: ui_context: wait4dc should assume a subcommand completes successfully if no exceptions are raised (bsc#1212992)

---

.github/workflows/crmsh-ci.yml
crmsh/ui_context.py

[crmsh-4.5] Fix: ui_context: wait4dc should assume a subcommand completes successfully if no exceptions are raised (bsc#1212992)

---

crmsh/ui_context.py

[crmsh-4.4] Fix: ui_context: wait4dc should assume a subcommand completes successfully if no exceptions are raised (bsc#1212992)

---

crmsh/upgradeutil.py
test/features/healthcheck.feature

Copy the seq file from the old path `~hacluster/crmsh/` to the new one `/var/lib/crmsh`, so that it can be found when upgraded to 4.5.

Fix: upgradeutil: support the change of path of upgrade_seq in crmsh-4.5 (bsc#1213050)

---

crmsh/cibconfig.py
crmsh/constants.py
crmsh/history.py
crmsh/log_patterns.py
crmsh/main.py
crmsh/ui_cluster.py
crmsh/ui_configure.py
crmsh/ui_node.py
crmsh/utils.py
crmsh/xmlutil.py
test/features/bootstrap_bugs.feature
test/unittests/test_ui_cluster.py
test/unittests/test_utils.py

[crmsh-4.4] Dev: utils: Change the way to get pacemaker's version

---

crmsh/upgradeutil.py
test/features/healthcheck.feature

A cluster running 4.4 should be able to upgrade to 4.5, without upgrade to the latest version in 4.4 branch first.
This requires #1212 to be ported to 4.5.

[crmsh-4.5] Fix: upgradeutil: support the change of path of upgrade_seq in crmsh-4.5 (bsc#1213050)

---

crmsh/upgradeutil.py
test/features/healthcheck.feature

A cluster running 4.4 should be able to upgrade to current master, without upgrade to the latest version in 4.4 branch first.
This requires #1212 to be ported to master.

[master] Fix: upgradeutil: support the change of path of upgrade_seq in crmsh-4.5 (bsc#1213050)

---

requirements.txt

parallax is not a dependency anymore and has already been removed in setup.py. It should also be removed from requirements.txt
backport #1219.

[crmsh-4.5] Dev: requirements: remove parallax

---

requirements.txt

parallax is not a dependency anymore and has already been removed in setup.py. It should also be removed from requirements.txt

Dev: requirements: remove parallax

---

crmsh/userdir.py

[crmsh-4.5] Fix: userdir: Get the effictive user name instead of using getpass.getuser (bsc#1213821)

---

crmsh/userdir.py

The return result from getpass.getuser may be incorrect since the function checks system environment variables LOGNAME, USER, LNAME, and USERNAME

Fix: userdir: Get the effictive user name instead of using getpass.getuser

---

crmsh/upgradeutil.py
crmsh/utils.py

During a rolling upgrade, some of the cluster nodes may be unreachable. In certain cases, it takes a long time to wait for a EHOSTUNREACH error.
Reducing the timeout helps crmsh to detect unreachable nodes faster and to give up quickly

[crmsh-4.4] Fix: upgradeutil: reduce ConnectTimeout when checking the availability of ssh access (bsc#1213797)

---

.github/workflows/crmsh-cd.yml
.github/workflows/crmsh-ci.yml
codecov.yml

As secrets in Github Actions are not provided to pull requests, the codecov token has to be provided in plaintext. This token is only authorized to upload reports to codecov.
See https://github.com/codecov/codecov-action/issues/557.

Fix: codecov: use token in plaintext

---

.github/workflows/crmsh-cd.yml
.github/workflows/crmsh-ci.yml
codecov.yml

[crmsh-4.5] Fix: codecov: use token in plaintext

---

codecov.yml

Sometimes codecov/patch check stuck in failed status. Try to fix it.
See https://community.codecov.com/t/github-status-check-reported-too-early/3043.

Fix: codecov: delay notifications until all reports are uploaded

---

crmsh/utils.py

[crmsh-4.5] Dev: utils: strip new line when get_stdout_or_raise_error returns

---

crmsh/constants.py

To align with pacemaker upstream, add:
'critical', 'allow-unhealthy-nodes' and 'container-attribute-target'

Fix: constants: Add several resource meta attributes (bsc#1215319)

---

crmsh/constants.py

[crmsh-4.6] Fix: constants: Add several resource meta attributes (bsc#1215319)

---

crmsh/constants.py

[crmsh-4.5] Fix: constants: Add several resource meta attributes (bsc#1215319)

---

crmsh/history.py
crmsh/report/utillib.py

To address a regression introduced after #1256 , due to hard coding the target tarball suffix as 'bz2' in the crm history.

[crmsh-4.6] Fix: report: Pick up tarball suffix dynamically (bsc#1215438)

---

crmsh/ui_utils.py
test/features/configure_bugs.feature

Now supports both:
crm node attribute <node> set <attr> <value>
crm node attribute <node> set <attr>=<value>
crm resource meta <rsc> set <attr> <value>
crm resource meta <rsc> set <attr>=<value>
crm resource param <rsc> set <param> <value>
crm resource param <rsc> set <param>=<value>

Dev: ui_utils: Supports '=' when setting node/resource attributes

---

crmsh/ui_utils.py
test/features/configure_bugs.feature

[crmsh-4.6] Dev: ui_utils: Supports '=' when setting node/resource attributes

---

.github/workflows/crmsh-ci.yml
test/unittests/test_bootstrap.py
test/unittests/test_corosync.py
test/unittests/test_qdevice.py
test/unittests/test_sbd.py
test/unittests/test_ui_cluster.py
test/unittests/test_utils.py
tox.ini

It's advisable to re-enable unit tests for the master branch; otherwise, unit test errors will accumulate with each subsequent commit.

Dev: workflows: Enable unit test for the master branch

---

test/regression.sh

[crmsh-4.6] Dev: regression.sh: Show error messages when test fails

---

.github/workflows/crmsh-ci.yml
codecov.yml
crmsh/bootstrap.py
crmsh/config.py
crmsh/healthcheck.py
crmsh/prun/prun.py
crmsh/report/collect.py
crmsh/report/utillib.py
crmsh/sh.py
crmsh/ssh_key.py
crmsh/ui_cluster.py
crmsh/ui_corosync.py
crmsh/user_of_host.py
crmsh/utils.py
data-manifest
test/features/bootstrap_options.feature
test/features/ssh_agent.feature
test/features/steps/const.py
test/features/steps/step_implementation.py
test/features/steps/utils.py
test/unittests/test_bootstrap.py
test/unittests/test_sh.py

Use Cases
=========
In a typical cloud-based deployment, a server may have password-based
authentication disabled for ssh, and an adminstrator's ssh public key
is added to authorized_keys during initialization.
For this case, it is impossible for crmsh to log into cluster node with
interactive authentication and create new key pairs for further
operations. Instead, crmsh can make use of the administrator's key, by
authenticating ssh session with ssh-agent forwarded form the
adminstrator's PC.
Usage Example
=============
```text
alice@alice-pc: ~> ssh -A root@node1
root@node1:~ # crm cluster init --use-ssh-agent -y
root@node1:~ # exit
alice@alice-pc: ~> ssh -A root@node2
root@node2:~ # crm cluster join --use-ssh-agent -c node1 -y
```

[crmsh-4.6] Dev: bootstrap: implement ssh-agent support (jsc#PED-5774) 

---

crmsh/bootstrap.py
crmsh/prun/prun.py
test/features/bootstrap_bugs.feature
test/unittests/test_bootstrap.py
test/unittests/test_prun.py

File authorized_keys created for user hacluster in previous version is owned incorrectly by root. This prevents current verison of crmsh reading/writing it as user hacluster.
Fix by setting its owner and permission after create it and before trying to read/write it.
Also fix a problem of prun trying to detect ssh availability to localhost.

[crmsh-4.5] Fix: bootstrap: fix the owner and permission of file authorized_keys(bsc#1217279)

---

crmsh/healthcheck.py
crmsh/prun/prun.py
crmsh/ssh_key.py
test/features/bootstrap_bugs.feature
test/unittests/test_prun.py

port
* #1277
Note: the fix of bsc#1217279 is implemented quite differently from crmsh-4.5.

 [crmsh-4.6] Fix: bootstrap: fix the owner and permission of file authorized_keys(bsc#1217279)

---

crmsh/bootstrap.py
crmsh/completers.py
crmsh/ocfs2.py
crmsh/qdevice.py
crmsh/sbd.py
crmsh/ui_node.py
crmsh/utils.py
crmsh/xmlutil.py
test/unittests/test_ocfs2.py
test/unittests/test_qdevice.py
test/unittests/test_sbd.py
test/unittests/test_utils.py
test/unittests/test_xmlutil.py

[crmsh-4.6] Dev: completers: Add online_nodes and standby_nodes

---

crmsh/log.py
crmsh/main.py
crmsh/ui_context.py
scripts/health/collect.py
test/evaltest.sh
test/testcases/edit.exp
test/testcases/scripts.exp
test/testcases/shadow.exp
test/unittests/test_report_collect.py
test/unittests/test_report_core.py
test/unittests/test_report_utils.py

In previous versions, crmsh does not print backtrace for most  of exceptions to make the error message more readable. However, backtrace is important information to debug a problem happened in a production environment.
This pull request enable crmsh to print the backtrace in logfile and suppress it in console in the same time, by implement a custom LogFormatter for console.
And this pull request also contains these refactoring and improvements:
* Avoid modifying module `logging` in the standard library. Instead, subclass the classes in it to customize.
* Avoid modifying `LogRecord` in handlers and formatters as it is shared by multiple handlers and formatters.
* Use `levelno` instead `levelname` to filter the logs for better performance.
* Remove `ConsoleReportFormatter` as it does …

[crmsh-4.6] Dev: log: log the backtrace of ValueError in log file and refactoring

---

crmsh/log.py
crmsh/main.py
data-manifest
test/features/environment.py
test/features/qdevice_validate.feature
test/features/resource_set.feature
test/features/steps/step_implementation.py
test/features/steps/utils.py
test/testcases/confbasic-xml.filter

If keep debug and info messages all in stdout, then some scripts that need to handle or analyze the output of the crm command might be messy.
Also redirect warning messages into stderr
backport from #1127

[crmsh-4.4] Fix: log: Redirect debug messages into stderr (bsc#1208991)

---

crmsh/ui_cluster.py
crmsh/utils.py
test/features/bootstrap_bugs.feature
test/unittests/test_ui_cluster.py
test/unittests/test_utils.py

- Fix bsc#1213889: don't try to get DC when local service is unavailable
- Create nested functions to make the whole process clear
- Support checking and setting dlm option on remote node

[crmsh-4.5] Fix: ui_cluster: Improve the process of 'crm cluster stop' (bsc#1213889)

---

crmsh/ui_cluster.py
test/features/steps/const.py

Move --use-ssh-agent from network arguments to optional arguments (only for join side)

[crmsh-4.6] Dev: ui_cluster: Move --use-ssh-agent to optional arguments

---

etc/profiles.yml

Add profile for AWS and GCP with recommended corosync token timeout.
- https://docs.aws.amazon.com/sap/latest/sap-netweaver/sap-netweaver-ha-setup.html#sample-file
- https://documentation.suse.com/sbp/sap-12/html/SLES4SAP-hana-sr-guide-PerfOpt-12_AWS/index.html#id-1.12.6.5.6
- https://cloud.google.com/solutions/sap/docs/sap-hana-ha-config-sles#create_the_corosync_configuration_file

Add profile for AWS and GCP with recommended corosync token timeout

---

.github/workflows/crmsh-cd.yml

Use LEAP 15.5 as base image. The source code of the image is at [nicholasyang2022/obs-continuous-delivery](/nicholasyang2022/obs-continuous-delivery).

[crmsh-4.6] Dev: github-actions: update container image used in CD

---

codecov.yml
crmsh/report/utils.py
data-manifest
test/features/crm_report_bugs.feature
test/unittests/pacemaker.log.2
test/unittests/test_report_utils.py

Logs in syslog format lack year information, making it challenging to determine the year a line was recorded. Therefore, when encountering a future timestamp, we must estimate the year

[crmsh-4.6] Fix: report: Unable to gather log files that are in the syslog format (bsc#1218491)

---

crmsh/parallax.py

Guide users to setup passwordless authentications.

[crmsh-4.4] Fix: parallax: refine error message when parallax fails to perform passwordless authentication

---

crmsh/parse.py
crmsh/ui_configure.py
crmsh/utils.py
test/features/resource_set.feature
test/testcases/acl.exp
test/testcases/bugs.exp
test/testcases/bundle.exp
test/testcases/commit.exp
test/testcases/confbasic-xml.exp
test/testcases/confbasic.exp
test/testcases/delete.exp
test/testcases/edit.exp
test/testcases/file.exp
test/testcases/newfeatures.exp
test/testcases/rset-xml.exp
test/testcases/rset.exp
test/unittests/test_bugs.py
test/unittests/test_cliformat.py

The monitor operation's ID is constructed as
'<resource_id>-monitor-<interval_value>'. Therefore, when the monitor
interval is altered by configure.set, the ID should also be updated to
reflect the latest interval. If not, configure.set cannot update the
value based on the current path, which is identified by
id.[op_type.][interval.]name.
See the issue https://github.com/ClusterLabs/crmsh/issues/826

[crmsh-4.6] Update the operation id after the monitor interval changed

---

crmsh/bootstrap.py
crmsh/ssh_key.py

When a cluster is bootstrap with 'crm cluster init -N', the public key of the init node is added for mutiple times to the authorized_key files of other nodes.
Fix by reusing `AuthorizedKeyManager.add` in swap_public_ssh_key.

[crmsh-4.6] Fix: bootstrap: ssh key of the init node is duplicated in the authorized_keys files of other node (bsc#1218940)

---

crmsh/bootstrap.py

When a cluster is bootstrap with 'crm cluster init -N', the public key of the init node is added for mutiple times to the authorized_key files of other nodes.
Backport #1311.

[crmsh-4.5] Fix: bootstrap: ssh key of the init node is duplicated in the authorized_keys files of other node (bsc#1218940)

---

crmsh/config.py

Failing to import sys will raise an exception when encountering a parsing failure of crm.conf. sys is used in def _disable_exception_traceback()
https://github.com/ClusterLabs/crmsh/blob/master/crmsh/config.py#L20-L23

Import missing sys library in config.py

---

crmsh/report/collect.py
crmsh/report/utils.py
crmsh/ui_node.py
crmsh/utils.py
test/features/bootstrap_bugs.feature
test/features/crm_report_normal.feature
test/unittests/test_report_utils.py
test/unittests/test_utils.py

When setting up cluster via yast2-cluster,
- Can't start the cluster with --all option:
```
15sp5-1:~ # crm cluster start --all
ERROR: cluster.start: Cannot get the node list from cluster
```
- Can't start cluster on peer node
```
15sp5-1:~ # crm cluster start 15sp5-2
ERROR: cluster.start: Cannot get the node list from cluster
```
- Can't start cluster on local node
```
15sp5-1:~ # crm cluster start 15sp5-1
ERROR: cluster.start: Cannot get the node list from cluster
```
- The --all option try to query the node list from `utils.list_cluster_nodes`, which should grab the address list from corosync.conf when there is no cib
- For the peer node case, stop compare with the return results from list_cluster_nodes, since it's hard to tell if the given name is not the alias name
- For the local …

[crmsh-4.6] Fix: ui_cluster: Can't start cluster with --all option if no cib (bsc#1219052)

---

crmsh/utils.py

To fix a minor regression introduced by #1312 , when the second node is joining 
```
ERROR: When reading file "/etc/corosync/corosync.conf": [Errno 2] No such file or directory: '/etc/corosync/corosync.conf'
```
That is because `utils.list_cluster_nodes` was called by `upgrade_if_needed`, at very beginning, when there is no corosync.conf exist

[crmsh-4.6] Dev: utils: Return empty list if corosync.conf does not exist

---

crmsh/report/utillib.py
test/features/crm_report_bugs.feature

[crmsh-4.5] Fix: report: Escape special characters in pattern (bsc#1220022)

---

crmsh/ui_node.py

"crm node show" and "clearstate" commands need adjustments. The format of the output in the //node_state has little changed in https://github.com/ClusterLabs/pacemaker/pull/3031 This PR enables the crmsh to understand both the new and the old format.
[crmsh-4.6] Backport #1323

[crmsh-4.6] Fix: ui_node: clearstate command needs adjustment (bsc#1219831)

---

crmsh/ui_configure.py

To ensure consistent behavior for warnings, see
https://github.com/ClusterLabs/crmsh/issues/861#issuecomment-1022779253
That is, the warning will be raised when there is no RA added in cluster

[crmsh-4.6] Dev: ui_configure: verify all cib objects even if there is no primitive resource configured

---

crmsh.spec.in

Since the build will fail without it on openSUSE Tumbleweed
See https://build.opensuse.org/package/live_build_log/openSUSE:Factory/crmsh/standard/x86_64

[crmsh-4.6] Dev: spec: Add setuptools as BuildRequires

---

crmsh/report/collect.py
crmsh/report/core.py
crmsh/report/sh.py
data-manifest
test/unittests/test_report_collect.py
test/unittests/test_report_core.py
test/unittests/test_report_sh.py

The current ssh implementation in crm.report will use a wrong user when using root + ssh-agent + sudo.
This patch change to use try to ClusterShell first, providing consistent behavior with other parts of crmsh. And fallback to interactive authentication when ClusterShell does not work.

[crmsh-4.6] Fix: report: use ClusterShell for ssh (bsc#1220170)

---

crmsh/report/core.py

In a cluster boostrapped with `--use-ssh-agent`, crm report depends on the agent to authenticate to other nodes. If the agent is not started, forwarded or is hidden by sudo, crmsh should print diagnostic message to help users fix the problem.

[crmsh-4.6] Fix: add diagnostic messages when crm report cannot find ssh-agent (bsc#1219538)

---

.github/workflows/crmsh-ci.yml
tox.ini

Dev: unittest: disable python 3.10 in test matrix

---

.github/workflows/crmsh-cd.yml

Since the condition to check the branch is already in the 'integration' stage (https://github.com/ClusterLabs/crmsh/blob/4a0937c33154b631a341d16c69880d1ceedd8731/.github/workflows/crmsh-cd.yml#L19), we don't need to check it again in the subsequent stages.

Dev: workflows: Remove the redundant stage condition

---

crmsh/ui_node.py

Crm throws traceback on `crm node standby` if cluster (corosync/pacemaker) stopped.
```
[root@es-3-virt1 ~]# rpm -qa | grep crmsh
crmsh-4.5.1-1.el8.noarch
crmsh-scripts-4.5.1-1.el8.noarch
crmsh-test-4.5.1-1.el8.noarch
[root@es-3-virt1 ~]# crm cluster stop
WARNING: crmsh configuration is inconsistent in cluster.
INFO: The cluster stack already stopped on es-3-virt1
[root@es-3-virt1 ~]# crm node standby
WARNING: crmsh configuration is inconsistent in cluster.
ERROR: running cibadmin -Ql: Could not connect to the CIB: Transport endpoint is not connected
Init failed, could not perform requested operations
Traceback (most recent call last):
File "/usr/sbin/crm", line 53, in <module>
rc = main.run()
File "/usr/lib/python3.6/site-packages/crmsh/main.py", line 369, in run
return …
```

Fix: ui_node: prevent traceback on node standby

---

crmsh/report/collect.py
test/unittests/test_report_collect.py

[crmsh-4.6] Fix: report: Show different perspectives of cluster status with multiple 'crm_mon' options (bsc#1204273)

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

That will cause error when there is no such interface name on the init node

Fix: bootstrap: Remove unused -i option when calling csync2_remote and ssh_remote stage (bsc#1212080)

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

[crmsh-4.6] Fix: bootstrap: Remove unused -i option when calling csync2_remote and ssh_remote stage (bsc#1212080)

---

crmsh/sh.py

[crmsh-4.6] Dev: sh: Fix typo in docstring

---

crmsh/report/sh.py
crmsh/scripts.py
crmsh/sh.py
crmsh/term.py
crmsh/ui_node.py
crmsh/user_of_host.py
crmsh/utils.py
crmsh/xmlutil.py
test/unittests/test_sh.py

A bug in python stardard library, python/cpython#100516, make
environment variables, `COLUMNS` and `ROWS` to be added at fork. These
environment variables may make some of the commands called by crmsh to
truncate its output even if those commands are not writing to the
terminal.
Passing argument `env` explicitly is a workaround for the python bug.

[crmsh-4.6] Fix: sh: pass env to child process explicitly (bsc#1205925)

---

crmsh/report/utillib.py
crmsh/scripts.py
crmsh/term.py
crmsh/ui_node.py
crmsh/utils.py
crmsh/xmlutil.py
test/unittests/test_utils.py

[crmsh-4.5] Fix: sh: pass env to child process explicitly (bsc#1205925)

---

.github/workflows/crmsh-ci.yml
crmsh/sh.py
test/features/ssh_agent.feature

[crmsh-4.6] Fix: sh: Return the value of AuthorizationError.diagnose if it is not None

---

crmsh/bootstrap.py
crmsh/corosync.py
crmsh/ssh_key.py
test/unittests/test_bootstrap.py
test/unittests/test_corosync.py

Currently, qdevice only adds the init node's key to qnetd. This patch adds all nodes' keys to qnetd authorized_keys. Then all cluster nodes can connect to qnetd without password.

Dev: qdevice: Add all nodes' keys to qnetd authorized_keys

---

crmsh/crash_test/main.py
crmsh/ui_cluster.py
crmsh/ui_context.py
crmsh/ui_node.py
crmsh/utils.py

It is not a failure.
Part of #1374.

[crmsh-4.6] Dev: ui_context: make help subcommands to exit with 0 (#1374)

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

…d ssh_remote stage (bsc#1212080, bsc#1221912)
backport #1347

[crmsh-4.1] Fix: bootstrap: Remove unused -i option when calling csync2_remote and ssh_remote stage (bsc#1212080, bsc#1221912)

---

crmsh/ui_node.py

[crmsh-4.6] Fix: ui_node: prevent traceback on node standby

---

crmsh/ui_node.py
crmsh/utils.py
test/features/bootstrap_bugs.feature
test/features/crm_report_normal.feature
test/unittests/test_utils.py

[crmsh-4.6] Fix: ui_node: When `utils.list_cluster_nodes` return None, try to get ip list from corosync.conf

---

.gitignore
doc/.gitignore
doc/Makefile
doc/toolchain/Containerfile
doc/toolchain/bin/adocxt
doc/toolchain/bin/help2adoc
doc/toolchain/lib/help2adoc/generator.py
doc/toolchain/lib/help2adoc/main.py
doc/toolchain/lib/help2adoc/parser.py

This pull request includes:
1. a tool `help2adoc` to convert the help text generated by python `argparse` module to asciidoc
2. a series of helper scripts, makefiles, containers to automatic the process to combine the asciidocs generated by `help2adoc` and `crm.8.adoc` to generated a complete document
Usage:
```shell
$ cd doc/toolchain
$ podman build -t local/crmsh-doc-builder .
$ cd ..
$ make clean
$ podman run --rm -ti -v ..:/opt/crmsh local/crmsh-doc-builder:latest
```
The final results is `doc/generated-sources/crm.8.adoc` and `doc/generated-sources/crm.8.html`
Part of #1374.

[crmsh-4.6] Dev: doc: implement help2adoc (#1374)

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

```
WARNING: chronyd.service is not configured to start at system boot.
ERROR: cluster.join:
```
```
See crmsh.log:
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/crmsh/ui_context.py", line 86, in run
rv = self.execute_command() is not False
File "/usr/lib/python3.6/site-packages/crmsh/ui_context.py", line 267, in execute_command
rv = self.command_info.function(*arglist)
File "/usr/lib/python3.6/site-packages/crmsh/ui_cluster.py", line 543, in do_join
bootstrap.bootstrap_join(join_context)
File "/usr/lib/python3.6/site-packages/crmsh/bootstrap.py", line 2246, in bootstrap_join
join_ssh(cluster_node, remote_user)
File "/usr/lib/python3.6/site-packages/crmsh/bootstrap.py", line 1596, in join_ssh
return join_ssh_impl(local_user, seed_host, seed_user, keys)
File …
```

Fix: bootstrap: Detect cluster service on init node before saving the canonical hostname (bsc#1222714)

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

[crmsh-4.6] Fix: bootstrap: Detect cluster service on init node before saving the canonical hostname (bsc#1222714) 

---

crmsh/log.py

So that the crmsh.log can include the year information.
See also: https://github.com/ClusterLabs/crmsh/pull/1295

Dev: log: Set the log format for crmsh.log as rfc5424

---

crmsh/healthcheck.py

Fix: healthcheck: Missing 'id_' prefix while checking the ssh key existence

---

crmsh/healthcheck.py

[crmsh-4.5] Fix: healthcheck: Missing 'id_' prefix while checking the ssh key existence

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

[crmsh-4.5] Fix: bootstrap: Remove unused -i option when calling csync2_remote and ssh_remote stage (bsc#1212080) 

---

crmsh/bootstrap.py
crmsh/ui_cluster.py
crmsh/utils.py
test/features/bootstrap_bugs.feature
test/features/bootstrap_options.feature
test/features/qdevice_validate.feature
test/unittests/test_bootstrap.py

- Stages dependency on init side
```
15sp5-1:~ # crm cluster init cluster -y
INFO: Loading "default" profile from /etc/crm/profiles.yml
INFO: Loading "knet-default" profile from /etc/crm/profiles.yml
ERROR: cluster.init: Please run 'ssh' stage first
15sp5-1:~ # crm cluster init ssh -y
INFO: Loading "default" profile from /etc/crm/profiles.yml
INFO: Loading "knet-default" profile from /etc/crm/profiles.yml
INFO: A new ssh keypair is generated for user root.
INFO: A new ssh keypair is generated for user hacluster.
INFO: Done (log saved to /var/log/crmsh/crmsh.log)
15sp5-1:~ # crm cluster init cluster -y
INFO: Loading "default" profile from /etc/crm/profiles.yml
INFO: Loading "knet-default" profile from /etc/crm/profiles.yml
ERROR: cluster.init: Please run 'csync2' stage first
15sp5-1:~ # …
```

Setup bootstrap stages dependency

---

crmsh/healthcheck.py

[crmsh-4.4] Fix: healthcheck: Missing 'id_' prefix while checking the ssh key existence

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

[crmsh-4.4] Fix: bootstrap: Remove unused -i option when calling csync2_remote and ssh_remote stage (bsc#1212080) 

---

crmsh/bootstrap.py
crmsh/ui_cluster.py
crmsh/utils.py
test/features/bootstrap_bugs.feature
test/features/bootstrap_options.feature
test/features/qdevice_validate.feature
test/unittests/test_bootstrap.py

[crmsh-4.6] Setup bootstrap stages dependency

---

crmsh/constants.py
crmsh/ui_context.py
test/features/bootstrap_options.feature

When cluster service is not running, entering some crm sublevel requires live cib, such as:
```
ERROR: running cibadmin -Ql: Could not connect to the CIB: Transport endpoint is not connected
Init failed, could not perform requested operations
ERROR: configure: Missing requirements
```
And it will fail to show the help info under this sublevel, like:
```
ERROR: running cibadmin -Ql: Could not connect to the CIB: Transport endpoint is not connected
Init failed, could not perform requested operations
ERROR: configure: Missing requirements
```
To fix that, should skip querying cib when the current stack is just level, or when the current command is the non functional command (like help, ls, cd, up, quit)

[crmsh-4.6] Dev: ui_context: Skip querying CIB when in a sublevel or help command

---

crmsh/constants.py
crmsh/ui_context.py
test/features/bootstrap_options.feature

Dev: ui_context: Skip querying CIB when in a sublevel or help command

---

crmsh/corosync.py
crmsh/crash_test/main.py
crmsh/ui_cluster.py
crmsh/ui_context.py
crmsh/ui_node.py
crmsh/utils.py

port:
* #1375
revert:
* 9148684b980b30291de91d9e203980ee08a610d9 which is merged by mistake
and
* make `ui_clsuter.do_start` to parse cmdline args before doing any other check

Dev: ui_context: make help subcommands to exit with 0

---

crmsh/healthcheck.py

Log a warning and continue, as join_ssh_impl should work even if local host is included in the node list.

[crmsh-4.5] Fix: healthcheck: KeyError when local nodename not found in cib (bsc#1223438)

---

contrib/bash_completion.sh
crmsh/main.py
doc/crm.8.adoc

Related issue #1390 
'id=' completion
```
```
property completion
```
batch-limit=                join-finalization-timeout=  pe-error-series-max=        stonith-enabled=
cluster-delay=              join-integration-timeout=   pe-input-series-max=        stonith-max-attempts=
cluster-ipc-limit=          load-threshold=             pe-warn-series-max=         stonith-timeout=
cluster-name=               maintenance-mode=           placement-strategy=         stonith-watchdog-timeout=
cluster-recheck-interval=   migration-limit=            priority-fencing-delay=     stop-all-resources=
concurrent-fencing=         node-action-limit=          remove-after-stop=          stop-orphan-actions=
dc-deadtime=                node-health-base=           shutdown-escalation= …
```

Enhance completion at non-interactive mode

---

doc/toolchain/bin/adocxt
doc/website-v1/man-4.6.adoc

The start of next section should be detected with
```
[[...]]
= ...
```
instead of
```
[[...,From Code]]
= ...
```

[crmsh-4.6] Fix: doc/toolchain: fix missing anchor in generated AIO doc (#1409)

---

crmsh/constants.py
test/unittests/test_xmlutil.py

OCF resource agents will be displayed as ocf:PROVIDER:AGENT rather than ocf::PROVIDER:AGENT in crm_mon and crm_simulate output and pacemaker-schedulerd logs

Dev: Change the RA name string format

---

crmsh/utils.py
test/unittests/test_utils.py

case 1
```
no 'priority' property
set 'priority=1' with no warning/info to show this behavior
```
case 2
```
show:
WARNING: "priority" in rsc_defaults is set to 0, it was 1
```
case 3
```
show:
WARNING: "priority" in rsc_defaults is set to 1, it was 0
```
This PR adds info when the property is newly added, for case 1

Dev: utils: Add info when property is newly added

---

crmsh/healthcheck.py

Fix: healthcheck: KeyError when local nodename not found in cib (bsc#1223438)

---

crmsh/healthcheck.py

[crmsh-4.6] Fix: healthcheck: KeyError when local nodename not found in cib (bsc#1223438)

---

crmsh/crash_test/task.py
crmsh/crash_test/utils.py
crmsh/ui_node.py

When running `crm node fence` or `crm cluster crash_test --fence-node`, should check if stonith device configured and running, if not, log an error and return False

Dev: log an error when fencing node without stonith device configured and running

---

crmsh/bootstrap.py
crmsh/utils.py
test/features/bootstrap_options.feature

-  Give valid value list for the -i option when the value is invalid
```
ERROR: cluster.init: Invalid value 'xxx' for -i/--interface option
ERROR: cluster.init: Invalid value 'xxx' for -i/--interface option, should be enp1s0, enp7s0, enp8s0 or 192.168.122.189, 10.10.10.61, 20.20.20.61
```
-  On join side, adjust the condition of comparing the link number
```
```
- Minor refactoring of the get_address_list function
```
...
Address for ring0 [192.168.122.189]
INFO: Configure SBD:
...
Address for ring0 [192.168.122.145]
Add another ring (y/n)?
```
```
...
Address for ring0 [10.10.10.61]
Add another ring (y/n)?
...
Address for ring0 [10.10.10.62]
Address for ring1 [20.20.20.62]
INFO: Configure SBD:
```

interface network option improvement

---

crmsh/cmd_status.py

`crm status ...`  appends tail arguments to the `crm_mon -1` without quoting or escaping. This is unsafe as they will be parsed as a shell command.
This patch changes how crmsh calls `crm_mon`. Arguments is passed as string arrays instead of shell cmdline.
Fixes #1429.

Fix: cmd_status: call crm_mon without shell (#1429)

---

crmsh/cmd_status.py

[crmsh-4.6] Fix: cmd_status: call crm_mon without shell (#1429)

---

crmsh/cmd_status.py

[crmsh-4.5] Fix: cmd_status: call crm_mon without shell (#1429)

---

.github/workflows/crmsh-cd.yml
.github/workflows/crmsh-ci.yml
codecov.yml
tox.ini

backport:
* #1436
difference:
* use ubuntu 20.04 as python 3.6 is removed in 24.04
* the number of reports are different
* no badge in README.md

[crmsh-4.6] Dev: github-actions: update to v4 (#1431)

---

.github/workflows/crmsh-cd.yml
.github/workflows/crmsh-ci.yml
codecov.yml
tox.ini

backport:
* #1436
difference:
* use ubuntu 20.04 as python 3.6 is removed in 24.04
* the number of reports are different
* no badge in README.md

[crmsh-4.5] Dev: github-actions: update to v4 (#1431)

---

crmsh/cibconfig.py
crmsh/ra.py
crmsh/ui_configure.py
crmsh/utils.py
test/testcases/acl.exp
test/testcases/bugs.exp
test/testcases/bundle.exp
test/testcases/commit.exp
test/testcases/confbasic.exp
test/testcases/delete.exp
test/testcases/edit.exp
test/testcases/file.exp
test/testcases/newfeatures.exp
test/testcases/node.exp
test/testcases/resource.exp
test/testcases/rset.exp

With the latest pacemaker version (since 2.1.8),
crmsh can get the resource meta attributes by parsing the output of `crm_resource --list-options=primitive --output-as=xml` command.
The benefit of this approach:
- Avoid hardcoding the resource meta attributes
- Provide help info at interactive mode for each meta attribute
```
crm(live/alp-1)configure# rsc_defaults maintenance=
maintenance (boolean, [false]): If true, the cluster will not schedule any actions involving the resource
If true, the cluster will not start, stop, promote, or demote the resource on any node, and will pause any recurring monitors (except those specifying role as "Stopped"). If false, a true value for the maintenance-mode cluster option or maintenance node attribute overrides this.
crm(live/alp-1)configure# …
```

Dev: Parsing resource meta attributes dynamically

---

crmsh/completers.py
crmsh/crash_test/check.py
crmsh/ui_resource.py
test/unittests/test_crashtest_check.py

- Use 'completers_repeating' instead of 'completers' for start/stop/restart/status/locate commands to get multiple complete results
- Filter out duplicated complete results
backport #1443

[crmsh-4.6] Dev: ui_resource: Improve completers for 'crm resource' command

---

crmsh/completers.py
crmsh/crash_test/check.py
crmsh/ui_resource.py
test/unittests/test_crashtest_check.py

- Use 'completers_repeating' instead of 'completers' for start/stop/restart/status/locate commands to get multiple complete results
- Filter out duplicated complete results

Dev: ui_resource: Improve completers for 'crm resource' command

---

test/testcases/bugs
test/testcases/bugs.exp
test/testcases/confbasic
test/testcases/confbasic-xml
test/testcases/confbasic-xml.exp
test/testcases/confbasic.exp
test/testcases/edit
test/testcases/edit.exp
test/testcases/ra.exp
test/testcases/resource
test/testcases/resource.exp
test_container/Dockerfile

After upgrading pacemaker version to 2.1.7+20240530.09c4d6d2e in docker image for CI, the original testcases need to do these changes:
- Convert 'ms' or 'master' command into promotable clone
- Avoid multiple rule in a location constraint
- Apply constraints to the group instead of the grouped resource
- Remove unknown resource meta attribute
- New output of pacemaker-fenced metadata

testcases update

---

crmsh.spec.in

as pattern matching(PEP-636) is used in corosync_config_format.py

Dev: spec: bump python requirement to >= 3.10

---

crmsh/command.py
crmsh/constants.py
doc/crm.8.adoc

- Hide 'configure ms' command from UI; crmsh still supports to interpret the old syntax, but not recommend to use it
- Move 'id-ref' usage into help primitive section
- Drop help info of 'configure ms' command

Dev: Hide 'configure ms' command (jsc#PED-8550)

---

doc/crm.8.adoc

- Remove 'moon' from doc, since it has been deprecated since pacemaker commit 283ab7079
- Adjust doc for deprecated multi-rule within a location constraint

Doc improvement

---

crmsh/upgradeutil.py

[crmsh-4.6] Fix: upgradeutil: refine error handling (bsc#1226147, bsc#1223371)

---

crmsh/ra.py

When adding fence agent without giving `stonith` class, get an error while using Tab to get  parameters
```
crm(live/alp-1)configure# primitive stonith-sbd fence_sbd params ERROR: ocf:heartbeat:fence_sbd: got no meta-data, does this RA exist?
```
That is allowed when adding ocf RA without giving `ocf` class
```
crm(live/alp-1)configure# primitive d Dummy params 
fake=    state=
```
In ra.disambiguate_ra_type function, return 'stonith' class type when RA starts with 'fence_'

Dev: ra: Guess stonith class type when using fence agents

---

.github/workflows/crmsh-ci.yml

As shown in https://github.com/ClusterLabs/crmsh/actions/runs/9612091155/job/26512047071, codecov reports: Error: Codecov token not found. Please provide Codecov token with -t flag.
So try a different way to provide the token.

Fix: codecov: use environ to pass CODECOV_TOKEN (#1472)

---

.github/workflows/crmsh-cd.yml

[crmsh-4.5] Fix: github-actions: should pass secrets to reusable workflows

---

.github/workflows/crmsh-cd.yml

[crmsh-4.6] Fix: github-actions: should pass secrets to reusable workflows

---

crmsh/ui_context.py

If you type
$ crm configure delete
of do it interactively
$ crm configure
crm(live/node1)configure# delete
and then double press tab it, should propose possible resource options. And this commit makes it working again.

Fix: ui_context: crm configure delete autocompletion #1403 #1460

---

crmsh/ui_context.py

backport #1469
If you type
$ crm configure delete
of do it interactively
$ crm configure
crm(live/node1)configure# delete
and then double press tab it, should propose possible resource options. And this commit makes it working again.

[crmsh-4.6] Fix: ui_context: crm cluster delete autocompletion #1403 #1460

---

crmsh/ui_context.py

The regression was introduced in beb26f3e
Before beb26f3e it was like
```
crm(live/15sp5-1)configure# primitive d Dummy
crm(live/15sp5-1)configure# up
There are changes pending. Do you want to commit them (y/n)?
```
After beb26f3e there is no prompt `There are changes pending. Do you want to commit them (y/n)?`
This change brings the prompt back.

Fix: ui_context: crm configure up prompt #1466

---

crmsh/utils.py

The initial error that we faced during our online storage upgrade:
```
Command: x Exascaler Install: apply_lustre_params,create_udev_rules,email,emf_agent,emf_node_manager,ha,hosts,ipmi,kdump,logging,lustre,lvm,mdt_backup,modprobe,nics,ntp,os,ost_pools,restart_network,serial,start_cluster,sync_exa_toml (Config ver. 1) failed
User: api
Job: x es-install --steps start_cluster on node5 failed
Step: x Run config-pacemaker on node5 failed (took: 12s 534ms 171us 586ns)
Result (Error):
Bad Exit Code: 1.
Started: 2024-02-07T03:26:16.158Z
Ended: 2024-02-07T03:26:28.692Z
Stdout:
Running Command: config-pacemaker --unmanaged-emf
Stderr:
x Command has failed.
Code: exit status: 1
Stdout: INFO: cib.commit: committed '5e8558de-1ceb-46c2-bd70-1ab4d8504c9f' shadow CIB to the cluster
Stderr: WARNING: DC …
```

DC lost during wait

---

crmsh/command.py
crmsh/ra.py
crmsh/ui_configure.py
crmsh/ui_context.py

When adding an RA, if that RA has required parameters, 
sort the completion results by required parameters and then alphabetically
```
crm(live/alp-1)configure# primitive vip IPaddr2 params 
ip=                        arp_count_refresh=         broadcast=                 flush_routes=              lvs_ipv6_addrlabel_value=  network_namespace=         noprefixroute=             send_arp_opts=
arp_bg=                    arp_interval=              cidr_netmask=              iflabel=                   lvs_support=               nic=                       preferred_lft=             unique_clone_address=
arp_count=                 arp_sender=                clusterip_hash=            lvs_ipv6_addrlabel=        mac=                       nodad=                     run_arping= …
```

Dev: ui_configure: Complete required parameters first

---

crmsh/ui_context.py

backport #1481
The regression was introduced in beb26f3e
Before beb26f3e it was like
$ crm(live/15sp5-1)configure# primitive d Dummy
$ crm(live/15sp5-1)configure# up
$ There are changes pending. Do you want to commit them (y/n)? After beb26f3e there is no prompt 'There are changes pending... (y/n)?' This change brings the prompt back.

[crmsh-4.6] Fix: ui_context: crm configure up prompt #1466

---

crmsh/command.py
crmsh/ra.py
crmsh/ui_configure.py
crmsh/ui_context.py

[crmsh-4.6] Dev: ui_configure: Complete required parameters first

---

crmsh/cibconfig.py
crmsh/constants.py
crmsh/ui_assist.py
crmsh/ui_configure.py
crmsh/ui_context.py
crmsh/ui_maintenance.py
crmsh/xmlutil.py

#1300 tried to remove unnecessary dependencies on a running pacemaker service when crmsh is not actually going to call the service. However, it removed the call to `end_game()` from `up()` and `quit()` incorrectly. This made sublevel `configure` not to have a chance to check uncommitted changes anymore, leading to a regression described in #1466.
#1481 tried to fix this regression by adding the call to `end_game()` back to `up()`, and check if pacemaker service is running before calling `end_game()`. This is not optimal as `up()` is a common method used for all sublevels and the status of pacemaker service is only related sublevel `configure`. Checking the status of pacemaker service when using other sublevels does not make sense.
This pull request uses a more straightforward method to …

Dev: refine change detection for `crm configure` (#1466)

---

crmsh/bootstrap.py
crmsh/utils.py
test/features/bootstrap_bugs.feature

The command `crm_attribute --attr-name no-quorum-policy --delete-attr` didn't work, will get
```
crm_attribute: Missing argument for --delete-attr
```
And adding a new function to delete the cluster property.

Dev: bootstrap: Use the existing function to query cluster property

---

scripts/health/hahealth.py

There are two changes:
1) use tar gz (now reports are tar.gz)
2) remove -D flag from the crm_report (obsolete)

Fix: hahealth.py script

---

crmsh/cibconfig.py
crmsh/parse.py
test/features/resource_set.feature

Run
```
crm configure rsc_template dummy_template ocf:pacemaker:Dummy op monitor interval=12s
```
Then
```
crm configure primitive d1 @dummy_template params passwd=123
```
Got error
```
ERROR: None:None: got no meta-data, does this RA exist? 
```
Solution: When adding a rsc_template as a primitive resource, should disable auto complete advised operation values
Fix #1438

Fix: cibconfig: Disable auto complete advised operation values when adding a rsc_template

---

crmsh/cibconfig.py
crmsh/parse.py
test/features/resource_set.feature

[crmsh-4.6] Fix: cibconfig: Disable auto complete advised operation values when adding a rsc_template

---

crmsh/bootstrap.py
crmsh/prun/prun.py
crmsh/qdevice.py
crmsh/ui_cluster.py
test/features/qdevice_options.feature
test/features/qdevice_usercase.feature
test/features/qdevice_validate.feature
test/features/steps/const.py
test/features/steps/step_implementation.py
test/unittests/test_bootstrap.py
test/unittests/test_qdevice.py

When TLS for qdevice/qnetd communication is disabled, the current implementation changes only the configuration on the client side (qdevice), and the server side (qnetd) still uses default value: "on". As a result, qnetd needs to be prepared for accepting incoming TLS connections. This requires CA and server certificates to be generated.
This pull request ensures CA and server certificates present on qnetd node and qnetd service started before starting to configure qdevice.

Fix: qnetd fails to start when TLS is disabled (bsc#1227649)

---

crmsh/bootstrap.py
crmsh/prun/prun.py
crmsh/qdevice.py
crmsh/ui_cluster.py
test/features/qdevice_options.feature
test/features/qdevice_usercase.feature
test/features/qdevice_validate.feature
test/features/steps/const.py
test/features/steps/step_implementation.py
test/unittests/test_bootstrap.py
test/unittests/test_qdevice.py

[crmsh-4.6] Fix: qnetd fails to start when TLS is disabled (bsc#1227649)

---

crmsh/bootstrap.py
crmsh/prun/prun.py
crmsh/qdevice.py
crmsh/ui_cluster.py
test/features/qdevice_options.feature
test/features/qdevice_usercase.feature
test/features/qdevice_validate.feature
test/features/steps/const.py
test/features/steps/step_implementation.py
test/unittests/test_bootstrap.py
test/unittests/test_qdevice.py

[crmsh-4.5] Fix: qnetd fails to start when TLS is disabled (bsc#1227649)

---

scripts/health/hahealth.py

[crmsh-4.6] Fix: hahealth.py script (bsc#1228271)

---

utils/crm_rpmcheck.py

This PR introduces `ansible` and this change is just the right place. Instead of repeatedly calling `rpm -q ...` it calls ansible only once and gets all the package information.

Dev: crm_rpmcheck: use ansible to get package versions

---

crmsh/ui_context.py

Fix a regression introduced in ac812f17b1fd94ff489e1f0ca17e968019a08417.

Fix: ui_context: enter_level() should not check requirements for non-functional subcommands

---

crmsh/cibconfig.py
crmsh/config.py
crmsh/parse.py
etc/crm.conf.in

This PR is for issue #1442 
The default value for `add_advised_op_values` is 'yes'.
When set to 'no', the advised operation values will not be added automatically if the user has not specified them

Add an option 'add_advised_op_values' to disable adding advised op values

---

crmsh/cibconfig.py
crmsh/config.py
crmsh/parse.py
etc/crm.conf.in

[crmsh-4.6] Add an option 'add_advised_op_values' to disable adding advised op values

---

crmsh/bootstrap.py
crmsh/utils.py
test/unittests/test_bootstrap.py
test/unittests/test_utils.py

When running `crm cluster init qdevice --qnetd-hostame <qnetd-node>` with an environ `SSH_AUTH_SOCK`, even if `--enable-ssh-agent` is not specified, crmsh will use that ssh-agent for `check_ssh_passwd_need`. If the ssh-agent provides a key enabling passwordless ssh authentication to the `<qnetd-node>`, the ssh public key of the `<init-node>` will not be added to the `authorized_keys` of `<qnetd-node>`.
This makes the ssh authentication between `<init-node>` and `<qnetd-node>` to depend on ssh-agent. It is unexpected and causes problems. For example, when a new node joins without ssh-agent, the new node needs the help of `<init-node>` to copy its ssh public key to `<qnetd-node>` (by running `crm cluster init qnetd-remote <new-node>` on `<init-node>`). This will fail as the `<init-node>` …

[crmsh-4.6] Fix: bootstrap: ssh public key should be copied to qnetd node when ssh-agent feature is not enabled (bsc#1228950)

---

crmsh/utils.py
test/unittests/test_utils.py

As written in getgroups(2):
It is unspecified whether the effective group ID of the calling process
is included in the returned list. (Thus, an application should also call
getegid(2) and add or remove the resulting value.)
Also use numeric 'haclient' gid instead of text group name, as it
performs less access to the group database

[crmsh-4.5] Fix: utils: group check failure when os.getgroups() returns empty (bsc#1229030)

---

crmsh/config.py
crmsh/constants.py
crmsh/main.py
crmsh/report/collect.py
crmsh/report/core.py
crmsh/report/utillib.py
crmsh/ui_cluster.py
crmsh/upgradeutil.py
crmsh/utils.py
etc/crm.conf.in

In some environments with a network firewall dropping ssh packets, any ssh operation could hang. 
- Add the 'core.no_ssh' option in crm.conf. 
"no" is the default. 
"yes" means all ssh-related operations are disabled and will directly return on purpose.
- Define a 'utils.NoSSHError' exception and an ssh wrapper function. Raise the exception when `no_ssh` is `yes`.
- Catch `utils.NoSSHError` in `main` so that SSH-related commands will log a general error message: `ERROR: ssh-related operations are disabled. crm report works in local mode.`
- Catch 'utils.NoSSHError' when running certain commands that call ssh, and provide a more user-friendly message.
- `upgradeutil`, which is called regardless of the command being called, will return without calling ssh, when `no_ssh` is `yes`.
- Other …

[crmsh-4.5] Fix: Raise an exception as a rapid return of ssh-related operations to prevent hang  (bsc#1228899)

---

crmsh/ui_configure.py
doc/crm.8.adoc

[crmsh-4.5] Revert "Dev: ui_configure: Deprecate configure erase sub-command" (bsc#1228713)

---

crmsh/ui_configure.py
doc/crm.8.adoc

Revert #1107, since `configure erase` is still used by the user, it shouldn't be deprecated

Revert "Dev: ui_configure: Deprecate configure erase sub-command" (bsc#1228713)

---

crmsh/ui_configure.py
doc/crm.8.adoc

[crmsh-4.6] Revert "Dev: ui_configure: Deprecate configure erase sub-command" (bsc#1228713)

---

crmsh/report/collect.py
crmsh/sh.py
test/unittests/test_report_collect.py
test/unittests/test_sh.py

Command `crm report` will hang if CIB contains invalid configurations, like lack of `stonith-enabled=false` when there is no stonith device configured.
When running `crm report`, crmsh tries to collect the output of `crm_verify`, by calling `get_stdout_or_raise_error`.
`crm_verify` will return non 0 value, then `get_stdout_or_raise_error` will raise custom exception `CommandFailure`, which will be wrongly pickled between processes.
1. Implementing the `__reduce__` method to provide custom pickling
support. This method returns a tuple specifying how to reconstruct
instances of CommandFailure during the unpickling process, ensuring all
necessary arguments (`cmd`, `host`, `user`, `msg`) are correctly passed
to the `__init__` method
2. When there is invalid configuration in cib as crm_verify …

[crmsh-4.6] Fix: report: crm report will hang if CIB contains invalid configuraions (bsc#1229686)

---

crmsh/cibconfig.py
crmsh/parse.py
test/features/resource_set.feature

Commit 7b2cfb23 automatically appends 's' as the default time unit for timeout and interval. This causes inconsistency in the existing CIB.
1. Run `crm configure primitive vip IPaddr2 params ip=10.10.10.123 op monitor interval=10`
2. Run `crm configure show vip`, we can see `interval=10s`
```
primitive vip IPaddr2 \
params ip=10.10.10.123 \
op monitor interval=10s timeout=20s \
op start timeout=20s interval=0s \
op stop timeout=20s interval=0s
```
3. Run `crm configure edit xml vip`, change `interval=10s` as `interval=10`, then run `crm configure show vip`
```
xml <primitive id="vip" class="ocf" provider="heartbeat" type="IPaddr2"> \
<instance_attributes id="vip-instance_attributes"> \
<nvpair name="ip" value="10.10.10.123" id="vip-instance_attributes-ip"/> \
</instance_attributes> \ …
```

[crmsh-4.6] Fix: Don't add time units to values for existing CIB (bsc#1228817)

---

crmsh/completers.py
crmsh/prun/prun.py
crmsh/scripts.py
crmsh/utils.py
test/features/user_access.feature

After the non-root feature is introduced, most of the subprocess calling rountines, including local ones and remote ones, try to switch to root before calling the specified command. This is good for command line usages. However, hawk2 also calls `crm script`, and as a webservice with less privileges, runs as user hacluster and should not escalate to root.
This pull request uses the interceptor interface provided by `prun` module to modify its behaviors. When `crm script` runs as hacluster, subprocesses will also be created as hacluster.
Also fixes a minor problem which stops script `hahealth` from parsing outputs correctly. The problem is caused by module `completers`, which try to call `crm_mon` before setting up the `PATH` environment variable.

[crmsh-4.6] Fix: hawk2 cannot call `crm script` as user hacluster (bsc#1228271)

---

crmsh/utils.py
test/unittests/test_utils.py

[crmsh-4.6] Fix: utils: group check failure when os.getgroups() returns empty (bsc#1229030)

---

crmsh/utils.py
test/unittests/test_utils.py

Fix: utils: group check failure when os.getgroups() returns empty (bsc#1229030)

---

crmsh/cibconfig.py
crmsh/parse.py
test/features/resource_set.feature

Fix: Don't add time units to values for existing CIB (bsc#1228817)

---

crmsh/ui_configure.py
crmsh/ui_node.py
crmsh/utils.py
test/features/configure_bugs.feature
test/features/steps/step_implementation.py

When cluster is not running, load CIB_file environment variable before some readonly commands to avoid the error message. (issue #1499 )
Current affected commands:
- crm configure show
- crm configure get_property
- crm configure verify
- crm node show
- crm node server

Dev: utils: Load CIB_file env before some readonly commands

---

crmsh/utils.py
test/features/user_access.feature
test/unittests/test_utils.py

As the title, to avoid misleading the user for the security risk, crmsh just raises the general error message. That says, let the user figure out the best practice according to the security policy of their organization.

Fix: utils: Stop providing the detailed and precise sudoer rules to "hack" the privilege (bsc#1229093)

---

crmsh/cibconfig.py
crmsh/config.py
crmsh/parse.py
etc/crm.conf.in
test/run-functional-tests

This option is used to automatically add the advised operation values
for fencing agents. Default value is 'no', which means doesn't add the
advised operation values for fencing agents.
Other changes:
- Dev: Add a new internal flag to control auto add time units on operation
- Dev: Rename the option 'add_advised_op_values' to 'has_ra_advised_op'

[crmsh-4.6] Fix: Add a new option 'has_fa_advised_op' (bsc#1228858)

---

crmsh/utils.py
test/features/user_access.feature
test/unittests/test_utils.py

[crmsh-4.5] Fix: utils: Stop providing the detailed and precise sudoer rules to "hack" the privilege (bsc#1229093)

---

crmsh/cibconfig.py
crmsh/config.py
crmsh/parse.py
etc/crm.conf.in
test/run-functional-tests

Fix: Add a new option 'has_fa_advised_op' (bsc#1228858)

---

crmsh/utils.py
test/features/user_access.feature
test/unittests/test_utils.py

[crmsh-4.6] Fix: utils: Stop providing the detailed and precise sudoer rules to "hack" the privilege (bsc#1229093)

---

crmsh/ui_node.py

Log an error and return False if the node is not found in CIB, avoid IndexError for subsequent code

Dev: ui_node: Improve command 'clearstate <node>'

---

crmsh/command.py
crmsh/help.py
crmsh/sh.py
crmsh/ui_root.py
crmsh/utils.py
doc/crm.8.adoc
doc/toolchain/bin/adocxt

#1471 adds 3rd level subcommands to crmsh. However, the `help` module is hardcoded to uses 2 levels of subcommands. This pull request modifies the `help` module to support arbitrary levels of subcommands.
It consists of 2 parts:
1. Replace `_`, the subcommand level separators used in `crm.8.adoc`, with `.`, to avoid ambiguity with `_` used in subcommand names (such as `geo_init`).
2. Use tree structure to store help data in memory, so that it works with arbitrary levels of subcommands.

Dev: help: support multi level subcommands

---

crmsh/utils.py

Log a warning message instead of an error during the crm report process under hacluster, as logging an error may be considered too severe

Dev: utils: Catch PermissionError when reading files

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

[crmsh-4.6] Fix: bootstrap: check is_nologin more robustly (bsc#1228251)

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

Note: the implementation is different with #1552.

Fix: bootstrap: check is_nologin more robustly (bsc#1228251)

---

crmsh/command.py
test/features/bootstrap_options.feature

should pass the name of all ancestor levels to `help_contextual`.

Fix: command: `do_help` does not work as a 3rd level subcommand

---

crmsh/report/core.py
crmsh/report/sh.py
test/unittests/test_report_core.py

1. Fix `crm.report.sh.Shell.subprocess_run_without_input`. It is expected to run commands as a specified user on a specified host. The user and host is carried in `Shell` instance, so that callers do not need to specify one when calling method `subprocess_run_without_input`.
2. Modify `crm.report.sh.Shell. _try_create_report_shell` to make it work for 2 different senerios:
1. When the specified user is `root` or `hacluster`, returns a  `crmsh.sh.SSHShell` wrapped in an adaptor `crm.report.sh.SSHShell`, so that commands runs directly as the specified user.
2. When the specified user is not `root` or `hacluster`, try to run `sudo` with the `SSHShell`. If
1. sudo works, returns a `crmsh.report.sh.SSHSudoShell`, which prepends a `sudo` to the command and runs it with `crmsh.SSHShell`.
2. sudo …

Fix: report: find_shell should accept hacluster user (bsc#1228899)

---

crmsh/report/core.py
crmsh/report/sh.py
test/unittests/test_report_core.py

[crmsh-4.6] Fix: report: find_shell should accept hacluster user (bsc#1228899)

---

crmsh/help.py

1. When len(args) is 1, should check if it is a topic first.
2. Should check _is_command() or _is_level() before calling help_command().
3. Refine the error message printed when no suitable help entries are found.
Fixes #1567.

Fix: help: crm help <topic> does not work (#1567)

---

crmsh/bootstrap.py
crmsh/qdevice.py
crmsh/report/core.py
crmsh/ui_node.py
crmsh/utils.py
test/features/crm_report_normal.feature
test/unittests/test_qdevice.py
test/unittests/test_report_core.py
test/unittests/test_utils.py

If both ping and ssh fail, the node is considered unreachable.
To fix issue #1551

Dev: utils: Check node is reachable by using both ping and ssh

---

crmsh/bootstrap.py
crmsh/qdevice.py
crmsh/sbd.py
crmsh/ui_cluster.py

Give user a hint that the cluster name should not be renamed when using qdevice, should remove qdevice first.
And also automatically restart cluster when there is no any resource running, when renaming the cluster name.
Fix issue #1465

Fix: ui_cluster: Stop renaming cluster name when using qdevice

---

crmsh/config.py
etc/crm.conf.in
test/features/cluster_api.feature
test/features/crm_report_normal.feature
test/run-functional-tests

Since this auto-add feature might surprise users, we should disable it by setting the option 'has_ra_advised_op' value to 'no'.

Fix: cibconfig: Disable auto add advise values for operations (bsc#1231386)

---

crmsh/config.py
etc/crm.conf.in
test/features/cluster_api.feature
test/features/crm_report_normal.feature
test/run-functional-tests

[crmsh-4.6] Fix: cibconfig: Disable auto add advise values for operations (bsc#1231386)

---

crmsh/bootstrap.py
crmsh/qdevice.py
crmsh/sbd.py
crmsh/ui_cluster.py

[crmsh-4.6] Fix: ui_cluster: Stop renaming cluster name when using qdevice

---

crmsh/sbd.py
crmsh/utils.py

- A new function `detect_duplicate_device_path` has been added to `utils.py`.
- This function checks for duplicated device paths in a given list of devices, raising a ValueError if duplicates are found.
To fix issue #1581

[crmsh-4.6] Dev: utils: Introduced `detect_duplicate_device_path` function in utils

---

crmsh/cibconfig.py
crmsh/config.py
etc/crm.conf.in
test/features/cluster_api.feature
test/features/crm_report_bugs.feature
test/run-functional-tests

- Dev: Add option core.has_ra_advised_op;
- Since this auto-add feature might surprise users, we should disable it by setting the option 'has_ra_advised_op' value to 'no'.

[crmsh-4.5] Fix: cibconfig: Disable auto add advise values for operations (bsc#1231386)

---

crmsh/sbd.py
crmsh/utils.py

[crmsh-4.4] Dev: utils: Introduced `detect_duplicate_device_path` function in utils

---

crmsh/sbd.py
crmsh/utils.py

[crmsh-4.5] Dev: utils: Introduced `detect_duplicate_device_path` function in utils

---

scripts/health/hahealth.py

This will help external applications (e.g. hawk) better understand the result of the 'crm script run health' execution.

Fix: hahealth: return fail when report failed (bsc#1231840)

---

.github/workflows/crmsh-ci.yml
test/features/bootstrap_bugs.feature
test/features/bootstrap_options.feature
test/features/cluster_blocking_ssh.feature
test/features/qdevice_usercase.feature
test/run-functional-tests
test/testcases/resource.exp
test_container/Dockerfile

* use knet-1.29 and rebuild the test container with latest tumbleweed
* replace privileged docker containers with unprivileged podman containers
* latest systemd in tumbleweed does no longer like to run in a privileged container. Instead it need the container runtime to setup a environment according to CONTAINER_INTERFACE[^1].
* replace legacy iptables with iptables-nft
* legacy iptables does not work in unprivileged containers
* stop using the default bridge container network
* ha_netowork_first and ha_network_second are enough for functional tests
* the default bridge network makes network interface names inside the containers unstable
close #1572.
[^1]: https://systemd.io/CONTAINER_INTERFACE/

Dev: behave: update test container to latest tumbleweed and use knet-1.29

---

README.md

as crmsh-ci no longer runs for master branch

README.md: use crmsh-cd as build status badge

---

crmsh/bootstrap.py

- Rename init_remote_auth to generate_pacemaker_remote_auth, call it in cluster stage
- In check_stage_dependency, don't check if the stage is internal or not, just check if the stage check function returns True
Fix #1593

Dev: bootstrap: Refine remote_auth stage

---

crmsh/bootstrap.py

[crmsh-4.4] Dev: bootstrap: Add log info when starting pacemaker.service

---

crmsh/bootstrap.py

Add a log message to indicate the start of pacemaker.service. This helps users understand that the system is not hanging but is actually starting pacemaker, especially when SBD_DELAY_START is set and it takes longer to start pacemaker.

[crmsh-4.6] Dev: bootstrap: Add log info when starting pacemaker.service

---

crmsh/report/collect.py
crmsh/report/constants.py
crmsh/report/utils.py
test/unittests/test_report_utils.py

The function `extract_critical_log` can be very slow when processing large log files. The main issue is the inefficiency of the regular expression, which combines multiple wildcards (.*) with alternation (|), leading to excessive backtracking. Additionally, the function reads the entire file into memory, which is not optimal for large files.
To improve performance, it is better to use `grep` with the -F option to search for fixed strings.
And for a sequence of archived log files, check the modify time. No need to check the rest of the files if the from time is greater than the modify time of the file.

[crmsh-4.6] Fix: report.utils: Fix the performance issue (bsc#1232821)

---

crmsh/report/collect.py
crmsh/report/constants.py
crmsh/report/utils.py
test/unittests/test_report_utils.py

Fix: report.utils: Fix the performance issue (bsc#1232821)

---

crmsh/bootstrap.py
crmsh/utils.py

Dev: bootstrap: more robust implementation for ssh_merge (bsc#1230530)

---

crmsh/bootstrap.py
crmsh/utils.py

* Do not use legacy `write_remote_file`, which does not work well with `_guess_user_for_ssh`.
* Implement deduplication when merging known_hosts

[crmsh-4.5] Dev: bootstrap: more robust implementation for ssh_merge (bsc#1230530)

---

test/run-functional-tests

Use apparmor=unconfined when the distribution does not provide a proper profile.

Fix: behave: systemd bpf-restrict-fs fails in opensuse tumbleweed

---

crmsh/bootstrap.py
crmsh/ssh_key.py
crmsh/utils.py
test/unittests/test_bootstrap.py

- The join process will fail if the existing key type is not RSA. See: https://github.com/ClusterLabs/crmsh/issues/1504#issuecomment-2443330157
- If the init and join nodes are already set up for passwordless access using an ed25519 key, an RSA key pair is still generated during the init/join process.
- Avoid hardcoding the ssh key type as RSA
- Introduced a new function `ssh_key.fetch_public_key_list` to fetch public keys from local or remote, return as public key path list or public key content list
- In KeyFileManager, use class variable to store the key type instead of hardcoding it as RSA
- Improve shell script in generate_ssh_key_pair_on_remote to avoid hardcoding the key type as RSA
- Remove unused code

Dev: utils: Avoid hardcoding the ssh key type as RSA

---

crmsh/report/utils.py

Single irregular file like crm.conf and profiles.yml are not collected, which was introduced by commit 210661b3.
Should determine if the file does have archived logs first.

Fix: report: Fix a regression for irregular file collection

---

crmsh/bootstrap.py
crmsh/constants.py
crmsh/qdevice.py
crmsh/report/collect.py
crmsh/report/utils.py
crmsh/sbd.py
crmsh/sh.py
crmsh/ui_root.py
crmsh/ui_sbd.py
crmsh/utils.py
crmsh/watchdog.py
data-manifest
doc/crm.8.adoc
test/features/bootstrap_sbd_delay.feature
test/features/bootstrap_sbd_normal.feature
test/features/sbd_ui.feature
test/features/steps/step_implementation.py
test/unittests/test_bootstrap.py
test/unittests/test_qdevice.py
test/unittests/test_report_collect.py
test/unittests/test_sbd.py
test/unittests/test_ui_sbd.py
test/unittests/test_utils.py
test/unittests/test_watchdog.py

The main configurations for sbd use cases are scattered among sysconfig,
on-disk meta data, CIB, and even could be related to other OS components
eg. coredump, SCSI, multipath. 
It's desirable to reduce the management complexity among them and to
streamline the workflow for the main use case scenarios. 
1. Show usage when syntax error
2. Completion
3. Display SBD related configuration (UC4 in PED-8256)
4. Change the on-disk meta data of the existing sbd disks (UC2.1 in PED-8256)
5. Add a sbd disk with the existing sbd configuration (UC2.2 in PED-8256)
6. Remove a sbd disk (UC2.3 in PED-8256)
7. Remove sbd from cluster
8. Replace the storage for a sbd disk (UC2.4 in PED-8256)]
9. display status (focusing on the runtime information only) (UC5 in PED-8256)
1. Show usage when syntax error …

Add 'crm sbd' sub-level (jsc#PED-8256)

---

crmsh/config.py
crmsh/report/collect.py
crmsh/report/core.py
crmsh/report/utils.py
etc/crm.conf.in
test/unittests/test_report_collect.py
test/unittests/test_report_core.py

1. The file `~/.config/crm/crm.conf` is now collected in crm report result
2. To manage files that have the same basename (e.g., `crm.conf`), the PR implements a new directory. When multiple files share the same basename, a directory named `{basename}.d` is created in the report result. All files with the same basename are then placed inside this directory. For instance, the files `/etc/crm/crm.conf` and `/root/.config/crm/crm.conf` will be placed inside a directory named `crm.conf.d`

Collect ~/.config/crm/crm.conf in crm report result

---

crmsh/utils.py

The behavior of `crmadmin -D` changed when no DC elected
original:
```
error: Timed out after 1000ms waiting for reply from controller API on DC
error: Command failed: Resource temporarily unavailable
```
now:
```
Designated Controller is: not yet elected
```

Dev: utils: Change `get_dc` function as the behavior of `crmadmin -D` changed

---

crmsh/command.py
crmsh/help.py
crmsh/ui_configure.py
doc/crm.8.adoc

By using `crm configure property <property_name> --help`, print the help of property on non-interactive mode.
Also, for `crm configure property` command, print all properties if no property is specified

Dev: help: Support '--help' option for cluster properties

---

crmsh/command.py
crmsh/help.py
crmsh/ui_configure.py
doc/crm.8.adoc

[crmsh-4.6] Dev: help: Support '--help' option for cluster properties

---

test/unittests/test_report_utils.py

Dev: unittests: Rewrite test_findln_by_timestamp by using fixed date

---

test/unittests/test_scripts.py

so that it will not be collected as a test case.

Fix: unittest: rename TestPrinter to UnitTestPrinter

---

crmsh/bootstrap.py
test/unittests/test_bootstrap.py

Filter out the files that not exist in local and remote

Fix: bootstrap: Improve sync_files_to_disk function (bsc#1219537)

---

test/unittests/test_report_utils.py

Some test cases should be duplicated after #1650 merged

Dev: unittests: Remove duplicated test case

---

crmsh/report/collect.py
test/unittests/test_report_collect.py

[crmsh-4.6] Fix: report: Check corosync.service status before querying quorum status (bsc#1235930)

---

crmsh/bootstrap.py
test/features/bootstrap_options.feature

To avoid potential misconfiguration between nodes on interactive mode.
e.g. Specify multiple interfaces on local node, but the peer node don't know the configuration.

Dev: bootstrap: Option -N should require option -y

---

crmsh/bootstrap.py
test/features/bootstrap_options.feature

[crmsh-4.6] Dev: bootstrap: Option -N should require option -y

---

crmsh/ui_context.py

Fix issue #1613 
- Don't complete for unknown command
- Don't complete for unknown arguments

Fix: ui_context: crmsh still complete even for unknown command

---

crmsh/sbd.py
test/unittests/test_sbd.py

Avoid possible inconsistency for multiple places to specify the sbd devices.
For #1642

Dev: sbd: Remove the 'devices' parameter for fence_sbd agent

---

crmsh/sbd.py
test/unittests/test_sbd.py

This checking can be useful for both interactive and non-interactive cases

Fix: sbd: Check if fence_sbd command exists before initializing device (bsc#1236184)

---

crmsh/report/collect.py
test/unittests/test_report_collect.py

[crmsh-4.6] Fix: report: Check if mounted.ocfs2 command exists before using it (bsc#1236220)

---

crmsh/bootstrap.py

Otherwise, the local joining node's known_hosts entry will not be synced to the other nodes.

Fix: bootstrap: Local joining node should be included when merging known_hosts (bsc#1229419)

---

crmsh/bootstrap.py

[crmsh-4.6] Fix: bootstrap: Local joining node should be included when merging known_hosts (bsc#1229419) 

---

crmsh/bootstrap.py

[crmsh-4.5] Fix: bootstrap: Local joining node should be included when merging known_hosts (bsc#1229419)

---

crmsh/ui_context.py

This reverts commit 9c308b2c3ae85b7d004f114a07ab65b5ffa58dcd.
To fix regression #1681 
Since it's hard to tell if this 'unknown argument' is an `id` or not

Revert "Fix: ui_context: Don't complete for unknown argument"

---

crmsh/ui_context.py

This reverts commit 3221cb93b6a7d0e886b78ae7579cd1c2114d6547.
backport from #1682

[crmsh-4.6] Revert "Fix: ui_context: Don't complete for unknown argument"

---

crmsh/command.py
crmsh/ui_configure.py

To complete existing pacemaker-*.rng files under /usr/share/pacemaker directory

Dev: ui_configure: Add completer for 'configure schema' command

---

crmsh/bootstrap.py
crmsh/sbd.py
test/unittests/test_bootstrap.py

When using sbd stage, detect if sbd package is missing on peer nodes
To fix issue #1635

Fix: sbd: Detect if sbd package is missing on peer nodes

---

crmsh/ui_configure.py
crmsh/ui_context.py
crmsh/utils.py

This PR is an implementation for #1685 
When running `up` or `Ctrl-C` or `quit` while there are changes not been committed, there is an option `c` to cancel `up` or exit, and it will stay at `configure` level to do further check/modify
```
crm(live/alp-1)configure# primitive d Dummy
crm(live/alp-1)configure# up
There are changes pending. Do you want to commit them, or cancel the operation  (y/n/c)? c
crm(live/alp-1)configure# show d
primitive d Dummy
crm(live/alp-1)configure# Ctrl-C, leaving
There are changes pending. Do you want to commit them, or cancel the operation  (y/n/c)? c
crm(live/alp-1)configure# show d
primitive d Dummy
crm(live/alp-1)configure# quit
There are changes pending. Do you want to commit them, or cancel the operation  (y/n/c)? c
crm(live/alp-1)configure# show d …
```

Dev: Add cancel option when confirming to commit for the pending changes

---

crmsh/bootstrap.py
crmsh/cmd_status.py
crmsh/completers.py
crmsh/constants.py
crmsh/crash_test/utils.py
crmsh/parse.py
crmsh/ra.py
crmsh/report/collect.py
crmsh/ui_resource.py
crmsh/ui_root.py
crmsh/utils.py
crmsh/xmlutil.py
doc/crm.8.adoc
test/testcases/common.excl
test/unittests/test_cliformat.py
test/unittests/test_crashtest_utils.py
test/unittests/test_parse.py

Changed:
- Dev: bootstrap: Drop 'record-pending' operation option
- Dev: utils: Make change since 'crmd-transition-delay' already renamed to 'transition-delay'
- Dev: constants: Drop deprecated "crmd-integration-timeout" and "crmd-finalization-timeout"
- Dev: crash_test: Drop deprecated 'poweroff' value of 'stonith-action' option
- Dev: Remove deprecated cibadmin --local option
- Dev: Drop unsupported 'moon' in date_spec
- Dev: constants: Drop deprecated 'restart-type' resource option
- Dev: Improve options of 'crm status' command
- Reduce duplicated options definition
- Drop deprecated '-s/--simple-status' option

Make minor changes based on Pacemaker-3.0's changelog (jsc#PED-8231)

---

test_container/Dockerfile

* No need to install libopenssl manually any more as bsc#1195792 is fixed.
* libglue-devel is gone.
* python3* pacakges is now named python311*.

Fix: ci: test container image build failure in tumbleweed

---

crmsh/cibconfig.py
crmsh/schema.py
crmsh/ui_configure.py
doc/crm.8.adoc
test/features/configure_bugs.feature
test/features/steps/step_implementation.py

- Make sure schema changed after setting new schema by `configure schema`
- Add test case for schema change
- Get schema statically when cluster is not running
- Improve documentation for `configure schema` command

Improve `configure schema` command

---

crmsh/bootstrap.py
crmsh/service_manager.py
crmsh/ui_cluster.py
test/unittests/test_ui_cluster.py

crmsh will show success logs when success to start:
```
INFO: Starting pacemaker.service on alp-1, alp-2
INFO: The cluster stack started on alp-1
INFO: The cluster stack started on alp-2
```
But will show nothing when fail to start:
```
INFO: Starting pacemaker.service on alp-1, alp-2
```
```
INFO: Starting pacemaker.service on alp-1, alp-2
ERROR: The cluster stack failed to start on alp-1
INFO: The cluster stack started on alp-2
```
When the fatal error leads to start pacemaker failing, the bootstrap process will wait for a long time:
```
...
INFO: Starting pacemaker.service on alp-1
INFO: BEGIN Waiting for cluster
............................................................. …
```

Dev: Add error log when cluster services fail to start

---

crmsh/cluster_fs.py
test/features/gfs2.feature
test/features/ocfs2.feature

- Commit c4d23d820 set a default DLM RA name when configuring gfs2/ocfs2, without syncing the name in related behave functional test cases
- The default DLM RA name is too simple and may conflict with
- Dev: cluster_fs: Use 'dlm-controld-ra' as the default dlm ra name;
Since the original name 'dlm' is simply too short and may conflict with
- Dev: behave: Sync dlm ra name in ocfs2 and gfs2 test cases

Change default DLM RA name

---

crmsh/cibconfig.py
crmsh/ui_configure.py
doc/crm.8.adoc

```
crm(live/alp-1)configure# schema
pacemaker-3.9
crm(live/alp-1)configure# upgrade               # Don't know this not works
crm(live/alp-1)configure# schema
pacemaker-3.9
crm(live/alp-1)configure# upgrade force
crm(live/alp-1)configure# schema                # Still show the old schema version
pacemaker-3.9
```
- Make the 'force' option mandatory for the 'upgrade' command
```
crm(live/alp-1)configure# upgrade
ERROR: configure.upgrade: 'force' option is required
```
- Show current schema version after successfully upgraded
```
crm(live/alp-1)configure# upgrade force
INFO: Current schema version is pacemaker-4.0
```
- Refresh before reading the schema version

Dev: ui_configure: Improve 'configure upgrade' command

---

crmsh/ssh_key.py

add `set -e` to the shell script so that it exits and reports on errors.

Dev: ssh_key: more robust error handling in KeyFileManager (bsc#1239084)

---

crmsh/ssh_key.py

add `set -e` to the shell script so that it exits and reports on errors.
(cherry picked from commit af9f40cea180079875d1e094e65a224aa3cd9b4a)

[crmsh-4.6] Dev: ssh_key: more robust error handling in KeyFileManager (bsc#1239084)

---

crmsh/cmd_status.py
crmsh/command.py
crmsh/constants.py
crmsh/rsctest.py
crmsh/ui_configure.py
scripts/db2-hadr/main.yml
scripts/drbd/main.yml
test/unittests/test_bugs.py

As pacemaker 3.0 already dropped support for deprecated master resources [1][2]
[1]
https://github.com/ClusterLabs/pacemaker/blob/main/xml/resources-4.0.rng#L19-L30
[2]
https://github.com/ClusterLabs/pacemaker/releases/tag/Pacemaker-3.0.0

Dev: ui_configure: Remove 'ms' sub-command (jsc#PED-8231)

---

crmsh/cibverify.py
test/testcases/common.excl

To avoid the log level difference between pacemaker and crmsh
backport from #1673

[crmsh-4.6] Dev: cibverify: Print output of crm_verify directly

---

crmsh/idmgmt.py
test/features/configure_bugs.feature

[crmsh-4.6] Fix: idmgmt: Replace hashtag('#') with point('.') in id (bsc#1239782)

---

crmsh/ui_resource.py
doc/crm.8.adoc
test/testcases/resource.exp

Ensure the trace directory is specified either through the argument or by using the value of the heartbeat_dir option. Eliminate any inconsistencies that might arise from heartbeat_dir (from etc/crm/crm.conf) or from HA_VARLIB (from /usr/lib/ocf/heartbeat/ocf-directories).

Dev: ui_resource: Refactor do_trace function

---

crmsh/cibconfig.py
crmsh/ui_configure.py

- `show changed` interface, to show what has been removed and added, using a diff-like format
```
crm(live/alp-1)configure# delete d
crm(live/alp-1)configure# primitive vip IPaddr2 params ip=10.10.10.123
crm(live/alp-1)configure# property cluster-delay=3
crm(live/alp-1)configure# show changed
node 1: alp-1
node 2: alp-2
-primitive d Dummy \
-       meta target-role=Stopped
primitive stonith-sbd stonith:fence_sbd \
params pcmk_delay_max=30s
+primitive vip IPaddr2 \
+       params ip=10.10.10.123
property cib-bootstrap-options: \
have-watchdog=true \
dc-version="3.0.0+20250310.476dc59612-2.1-3.0.0+20250310.476dc59612" \
cluster-name=hacluster \
stonith-enabled=true \
stonith-timeout=83 \
-       priority-fencing-delay=60
+       priority-fencing-delay=60 \
+       cluster-delay=3 …
```

Dev: ui_configure: Show the changes with diff like format

---

crmsh/constants.py
crmsh/parse.py
crmsh/ra.py
crmsh/rsctest.py
crmsh/ui_configure.py
crmsh/utils.py
crmsh/xmlutil.py
doc/crm.8.adoc
test/unittests/test_parse.py

- Dev: Drop node type normal and ping
According to the nodes-4.0.rng schema, only supports node type "member" and "remote"
- Dev: Remove codes that include rhcs term
- Dev: ra: Drop legacy codes to fetch ra informations

Drop deprecated codes

---

crmsh/constants.py
crmsh/parse.py
crmsh/ra.py
crmsh/rsctest.py
crmsh/ui_configure.py
crmsh/xmlutil.py
doc/crm.8.adoc

- Dev: Drop node type normal
It's been deprecated for a long time, and it's time to remove it.
- Dev: Remove codes that include rhcs term

[crmsh-4.6] Drop deprecated codes

---

crmsh/bootstrap.py
crmsh/cibquery.py
crmsh/sbd.py
crmsh/ui_sbd.py
crmsh/utils.py
doc/crm.8.adoc
test/features/sbd_ui.feature
test/unittests/test_sbd.py
test/unittests/test_ui_sbd.py
test/unittests/test_utils.py

This PR supports configuring the crashdump watchdog timeout
by using `crm sbd configure crashdump-watchdog-timeout=<timeout>`,
for both disk-based and diskless SBD.
- disk-based SBD case
```
WARNING: Kdump service is not active on alp-1
WARNING: Kdump service is not active on alp-2
INFO: Set crashdump option for fence_sbd resource
INFO: Set msgwait-timeout to 2*watchdog-timeout + crashdump-watchdog-timeout: 90
INFO: Configuring disk-based SBD
INFO: Initializing SBD device /dev/sda8
INFO: Update SBD_TIMEOUT_ACTION in /etc/sysconfig/sbd: flush,crashdump
INFO: Update SBD_OPTS in /etc/sysconfig/sbd: -C 60
INFO: Already synced /etc/sysconfig/sbd to all nodes
WARNING: Resource is running, need to restart cluster service manually on each node
INFO: Update SBD_DELAY_START in /etc/sysconfig/sbd: …
```

Dev: ui_sbd: Configure crashdump watchdog timeout

---

.github/workflows/crmsh-cd.yml
.github/workflows/crmsh-ci.yml

- Dev: workflows: Update CI image on github action
As ubuntu-20.04 is not provided by github action anymore, we need to update the CI image to ubuntu-24.04.
- Dev: workflows: Run unit test with python container

[crmsh-4.6] Dev: workflows: Update CI image on github action

---

crmsh/sbd.py
crmsh/ui_sbd.py
crmsh/utils.py
doc/crm.8.adoc
test/unittests/test_sbd.py
test/unittests/test_utils.py

Changing the SBD configuration requires restarting the cluster.
This PR enables the use of the crm -F/--force option to leverage maintenance mode when a cluster restart is necessary.
```
...
INFO: Set cluster to maintenance mode
WARNING: "maintenance-mode" in crm_config is set to true, it was false
INFO: Configuring disk-based SBD
...
INFO: Restarting cluster service
INFO: BEGIN Waiting for cluster
............                                                                                                                                                                                       
INFO: END Waiting for cluster
INFO: Set cluster from maintenance mode to normal
INFO: Delete cluster property "maintenance-mode" in crm_config
```

Dev: sbd: Leverage maintenance mode when need to restart cluster

---

crmsh/ui_cluster.py
test/features/cluster_api.feature
test/features/cluster_blocking_ssh.feature

When cluster is already started, the return value of `crm cluster start` is 1, which was expected as 0
```
INFO: The cluster stack already started on node1
1
```
This regression was introduced from #1692

Fix: ui_cluster: Return when cluster service on all nodes are already startd (bsc#1241358)

---

crmsh/ui_cluster.py
test/features/cluster_api.feature
test/features/cluster_blocking_ssh.feature

[crmsh-4.6] Fix: ui_cluster: Return when cluster service on all nodes are already startd (bsc#1241358) 

---

crmsh/ui_sbd.py
test/unittests/test_ui_sbd.py

Fix #1745 
```
ERROR: SBD configuration file /etc/sysconfig/sbd not found
```

Dev: ui_sbd: Raise TerminateSubCommand if /etc/sysconfig/sbd is not found

---

crmsh/utils.py

- Add detection to check if the cluster is already in maintenance mode. If yes, yield `True` and exit early to avoid resetting the maintenance mode unnecessarily.
- Introduce docstring to describe the behavior of the `leverage_maintenance_mode` function.
- Add proper type hints to the function, specifying it returns a `Generator[bool, None, None]`.
Fix issue #1759

Dev: utils: Enhance maintenance mode management with detection and type hints

---

contrib/bash_completion.sh
crmsh/command.py

In interactive mode, some completers display in a custom order, whereas in non-interactive mode, these custom completers are displayed in alphabetical order.
```
crm(live/alp-2)configure# primitive vip IPaddr2 params 
ip=
...
crm configure primitive vip IPaddr2 params 
arp_bg=                                    
...
```
This PR:
- On the `bash_completion.sh` side, add the `nosort` option to disable sorting. This ensures that completion results are displayed in the same order as returned by the command's completer.
- On the `crmsh` side, if a custom order completer is used, return the results as is; otherwise, sort the results before returning them.
Fix #1684

Dev: bash_completion.sh: Add nosort option to disable sorting

---

crmsh/report/core.py
crmsh/ui_node.py
crmsh/ui_sbd.py
crmsh/utils.py
test/unittests/test_report_core.py
test/unittests/test_utils.py

- Added the function `get_reachable_node_list` to `crmsh/utils.py` for centralizing node reachability checks.
- Update node list handling in multiple modules to use `utils.get_reachable_node_list`. Avoid possible modification of node list which can lead to unexpected behavior [#1764 ].

Dev: Refactored node reachability handling in multiple modules

---

crmsh/cibconfig.py
crmsh/ra.py
crmsh/ui_configure.py
crmsh/utils.py
crmsh/xmlutil.py
test/features/cluster_api.feature
test/features/resource_set.feature
test/unittests/test_utils.py

[crmsh-4.6] Fix: ra: Prevent to add unknown operation (bsc#1236442)

---

crmsh/cibconfig.py
crmsh/ra.py
test/unittests/test_bugs.py

#1679 only updated some sanity check functions and failed to change all related return values to use `VerifyResult`. 
This PR ensures that all related functions now consistently use `VerifyResult` as the return value.

Dev: cibconfig: Use VerifyResult to define the return value of sanity check related functions

---

crmsh/ui_cluster.py
crmsh/utils.py
test/features/ocfs2.feature

- Dev: ui_cluster: Skip stop cluster if cluster is in maintenance mode and dlm is running
```
INFO: The cluster is in maintenance mode
ERROR: Stopping pacemaker/corosync will trigger unexpected node fencing when 'dlm_controld' is running in maintenance mode.
INFO: The cluster is in maintenance mode
ERROR: Stopping pacemaker/corosync will trigger unexpected node fencing when 'dlm_controld' is running in maintenance mode.
```
Dev: ui_cluster: Refactor the `do_restart` function
- Ensure the function returns `False` immediately if `do_stop` returns
`False`, avoiding the execution of `do_start`.
- Update the function to return the result of `do_start`, as it may
return `False`.

 Dev: ui_cluster: Skip stopping cluster if dlm_controld is running in maintenance mode

---

crmsh/ui_cluster.py
crmsh/utils.py
test/features/ocfs2.feature

 [crmsh-4.6] Dev: ui_cluster: Skip stopping cluster if dlm_controld is running in maintenance mode

---

test/features/bootstrap_bugs.feature

After the GitHub Actions environment was updated, the network isolation between the two interfaces no longer functions as it did previously. As a result, the test case "Setup cluster with crossed network" does not fail as expected.
To address this, an iptables rule was added to simulate the isolated network environment required for the test case.

Dev: behave: Fix cross-network isolation issue

---

crmsh/log.py

[crmsh-4.5] Fix: log: fix a typo of a variable name

---

crmsh/ui_configure.py

Avoid crmsh treating kind of order(Mandatory, Optional, and Serialize) as a resource name.
backport #1775

[crmsh-4.6] Dev: ui_configure: Add ':' suffix to order kind completer

---

crmsh/ui_configure.py

Avoid crmsh treating kind of order(Mandatory, Optional, and Serialize) as a resource name.

Dev: ui_configure: Add ':' suffix to order kind completer

---

crmsh/corosync.py
test/features/qdevice_setup_remove.feature

Fix: corosync: Don't set quorum.two_node to 1 if qdevice configured

---

crmsh/sbd.py
crmsh/utils.py
test/unittests/test_sbd.py

fix #1739
- Remove pcmk_delay_max from the formula to calculate stonith-timeout
- Remove pcmk_delay_max from the formula to calculate SBD_DELAY_START

Dev: sbd: Remove pcmk_delay_max while cacaulating stonith timeout value

---

Makefile.am
crmsh.spec.in

Makefile.am:
- add target to build Python wheel
- fix an error when install tests
- fix uninstall-local target with Python3 pip uninstall
- install bash-completion
crmsh.spec.in:
- Recommends bash-completion

Fix: Makefile.am: add python wheel target and .spec Recommends bash-completion

---

crmsh/bootstrap.py
test/features/bootstrap_options.feature

- If an invalid admin IP is configured (for example, one on a different subnet), the process will wait for a long time
- When a timeout occurs, it will simply exit and will not proceed to configure the qdevice.
```
...
INFO: BEGIN Configuring virtual IP (40.40.40.123)
.........................................................    # here we wait for a long time, actually IPaddr2 RA failed quickly                                                                                                   ERROR: FAIL Configuring virtual IP (40.40.40.123)
ERROR: cluster.init: Time out waiting for resource.          # cannot configure qdevice here, just exit
```
- Wait for shorter time for admin IP to be started
- Don't exit if admin IP start fails, just log an error

Dev: bootstrap: Improve configuration for admin IP

---

crmsh/bootstrap.py
test/features/bootstrap_init_join_remove.feature
test/unittests/test_bootstrap.py

When removing a peer node from the cluster, if the cluster service is not running on that node, get_node_canonical_hostname fails because `crm_node --name` does not return a hostname.
```
INFO: Removing node alp-2 from cluster
ERROR: cluster.remove:
DEBUG: 2025/06/06 21:44:00
DEBUG: crm(live/alp-1)# cluster remove alp-2
DEBUG: ================================================================
DEBUG: /sbin/crm -d cluster remove alp-2
DEBUG: ----------------------------------------------------------------
INFO: Removing node alp-2 from cluster
DEBUG: su_subprocess_run: ['/bin/sh', '-c', 'ssh -A -o StrictHostKeyChecking=no -o BatchMode=yes root@alp-2 sudo -H -u root --preserve-env=SSH_AUTH_SOCK /bin/sh'], env={'SSH_AUTH_SOCK': ''}, {'input': b'crm_node --name', 'start_new_session': True, …
```

Dev: bootstrap: Improve node removal handling and messaging

---

crmsh/report/collect.py
test/features/crm_report_bugs.feature
test/features/crm_report_normal.feature
test/unittests/test_report_collect.py

This is the same error as reported in https://github.com/ClusterLabs/crmsh/pull/1606, which can be reproduced by deleting the `logfile:` line from corosync.conf. Although this was previously fixed, the issue regressed in #1622.
To prevent future regressions, I have added functional test cases for both #1622 and this scenario.

Fix: report.collect: Detect log existence before using it (bsc#1244515)

---

crmsh/report/collect.py
test/features/crm_report_bugs.feature
test/features/crm_report_normal.feature
test/unittests/test_report_collect.py

[crmsh-4.6] Fix: report.collect: Detect log existence before using it (bsc#1244515)

---

crmsh/crash_test/config.py
crmsh/crash_test/task.py
crmsh/xmlutil.py
test/unittests/test_crashtest_task.py

Previously, `crash_test --fence-node` obtained fence event information by parsing the string output from crm_mon and stonith_admin, which was unreliable. This update changes the approach to parse the XML output from crm_mon at the '//fence_history/fence_event' path, resulting in more accurate and robust retrieval of fence event details.

Fix: crash_test: Correctly retrieve fence event information (bsc#1243786)

---

crmsh/bootstrap.py
crmsh/utils.py
test/unittests/test_bootstrap.py

[crmsh-4.6] Dev: bootstrap: Remove user@host item from /root/.config/crm/crm.conf when removing node

---

crmsh/bootstrap.py
crmsh/completers.py
crmsh/qdevice.py
crmsh/ui_sbd.py
crmsh/utils.py
crmsh/xmlutil.py
test/features/bootstrap_init_join_remove.feature
test/unittests/test_bootstrap.py
test/unittests/test_qdevice.py
test/unittests/test_ui_sbd.py
test/unittests/test_utils.py
test/unittests/test_xmlutil.py

Before performing operations that require all nodes to be online or at least SSH-reachable, such as:
- Joining a node to the cluster
- Removing a node from the cluster
- Configure SBD
- Setup SBD
- Setup QDevice
- Removing QDevice
Check for any offline nodes that are also unreachable.
If such nodes are found, the operation is blocked, and the user is 
prompted to either bring the nodes online or forcibly remove them from
the cluster.
This enhances cluster safety by ensuring potentially problematic nodes
are handled explicitly before critical actions are taken.
```
WARNING: host "alp-2" is unreachable
ERROR: sbd.purge: There are offline nodes also unreachable: alp-2.
Please bring them online before purging SBD.
Or use `crm cluster remove <offline_node> --force` to remove the offline node. …
```

Dev: Prevent actions when offline nodes are unreachable

---

crmsh/log.py

If the answer is empty or not "y" or "n", it will now prompt in a loop, until a valid answer is provided

Fix: log: Improve function confirm's logic (bsc#1245386)

---

crmsh/bootstrap.py

Previously, the qnetd_remote stage was only triggered if ssh-agent usage was disabled (use_ssh_agent=False).
However, the use_ssh_agent flag defaults to True, which could skip the configuration even if the necessary SSH key is not available in the agent.
This change updates the condition to also trigger the qnetd_remote stage when the SSH key is not found in the agent, ensuring that the join node's key is correctly added to the qnetd's authorized_keys file when needed.

Fix: bootstrap: Refine qnetd passwordless configuration logic (bsc#1245387)

---

crmsh/bootstrap.py
test/features/bootstrap_bugs.feature
test/unittests/test_bootstrap.py

Fix: bootstrap: should fallback to default user when `core.hosts` is not availabe from the seed node (bsc#1245343)

---

crmsh/corosync.py
test/unittests/test_corosync.py

[crmsh-4.6] Dev: corosync: Get value from runtime.config prefix

---

crmsh/ui_context.py

[crmsh-4.6] Fix: ui_context: should not require root privilege when using subcommand 'help'

---

crmsh/sbd.py
test/features/bootstrap_sbd_delay.feature
test/unittests/test_sbd.py

Previously, when configuring diskless SBD with crmsh bootstrap, the option `stonith-watchdog-timeout` was set to -1 to prompt Pacemaker to automatically calculate the appropriate value.
However, Pacemaker now raises a warning when a negative value is used for timeout or duration options such as `stonith-watchdog-timeout`:
```
pacemaker-fenced[...]:  warning: '-1' is not a valid time duration: Negative
pacemaker-controld[...]:  warning: '-1' is not a valid time duration: Negative
```
Set the default value of `stonith-watchdog-timeout` to 2*SBD_WATCHDOG_TIMEOUT. The value of SBD_WATCHDOG_TIMEOUT is stored in /etc/sysconfig/sbd and can be kept consistent across all nodes using crmsh.

Fix: sbd: Avoid negative value for the property 'stonith-watchdog-timeout' (bsc#1246622)

---

crmsh/sbd.py
crmsh/utils.py
test/features/bootstrap_sbd_delay.feature
test/unittests/test_sbd.py

[crmsh-4.6] Fix: sbd: Avoid negative value for the property 'stonith-watchdog-timeout' (bsc#1246622) 

---

crmsh/sbd.py
crmsh/utils.py
test/unittests/test_sbd.py

[crmsh-4.4] Fix: sbd: Avoid negative value for the property 'stonith-watchdog-timeout' (bsc#1246622)

---

crmsh/sbd.py
crmsh/utils.py
test/features/bootstrap_sbd_delay.feature
test/unittests/test_sbd.py

In PR #1740, the parameter `pcmk_delay_max` was removed. However, the formula for `SBD_DELAY_START` still needs to account for the `pcmk_delay_max` factor [1]. This PR restores the use of `pcmk_delay_max` in the calculation.
[1] https://github.com/ClusterLabs/crmsh/pull/1740#discussion_r2221356833

Dev: sbd: Add pcmk_delay_max back to calculate SBD_DELAY_START

---

crmsh/sbd.py
crmsh/utils.py
test/features/bootstrap_sbd_delay.feature
test/unittests/test_sbd.py

Changes:
-  Dev: behave: Change the expected value of SBD_WATCHDOG_TIMEOUT and stonith-timeout
These values in testcases in file bootstrap_sbd_delay.feature should be updated first before backport
- backport #1873

[crmsh-4.6] Dev: sbd: Add pcmk_delay_max back to calculate SBD_DELAY_START

---

crmsh/qdevice.py
test/unittests/test_qdevice.py

No need to reload on all nodes, `corosync-cfgtool -R` will do it for us.

Dev: qdevice: Reload corosync configuration on one node

---

crmsh/sbd.py
test/unittests/test_sbd.py

When dlm is running, we cannot restart the cluster in maintenance mode as this will trigger node fencing. This is not a fatal error because:
1. The configuration has already been changed successfully.
2. Users may restart the cluster manually.

Fix: sbd: should show warning instead of error when unable to restart cluster automatically after changing configs (bsc#1246956)

---

crmsh/bootstrap.py
crmsh/sbd.py
test/unittests/test_bootstrap.py
test/unittests/test_sbd.py

Call `crm sbd configure watchdog-timeout=<new_value>` should also keep the property `stonith-watchdog-timeout` >= 2* SBD_WATCHDOG_TIMEOUT
Example:
```
SBD_WATCHDOG_TIMEOUT=15
stonith-watchdog-timeout=30
INFO: Configuring diskless SBD
WARNING: Diskless SBD requires cluster with three or more nodes. If you want to use diskless SBD for 2-node cluster, should be combined with QDevice.
INFO: Update SBD_WATCHDOG_TIMEOUT in /etc/sysconfig/sbd: 20
INFO: Already synced /etc/sysconfig/sbd to all nodes
INFO: Restarting cluster service
INFO: BEGIN Waiting for cluster
...........                                                                                                                                                                                        INFO: END Waiting for cluster
INFO: Update …
```

Fix: sbd: Ensure stonith-watchdog-timeout is >= 2 * SBD_WATCHDOG_TIMEOUT (bsc#1247415)

---

crmsh/log.py

In #1020 we right pad the progress bar with space characters so that it will not mess up with log messages printed concurrently during the progress bar runs. However, if the temrinal width changes after the progress bar is printed, the message line following it will be shown in the same line with it.
This commit fixes this by adding a final turn to print the progress bar without right padding and with a LF character.
Fixes #1886.

Fix: log: missing LF after a progress bar (#1886)

---

crmsh/bootstrap.py
crmsh/cibquery.py
crmsh/completers.py
crmsh/idmgmt.py
crmsh/ui_node.py
crmsh/utils.py
crmsh/xmlutil.py
test/features/bootstrap_bugs.feature
test/features/pacemaker_remote.feature
test/features/steps/step_implementation.py
test/unittests/test_bootstrap.py
test/unittests/test_utils.py
test/unittests/test_xmlutil.py

- Can't standby pacemaker remote node #1817
- Can't maintenance pacemaker remote node https://github.com/ClusterLabs/crmsh/issues/1817#issuecomment-3026676284
- The way to get remote node's name
```
/cib/status/node_state[@remote_node="true"]/@uname
```
Might have problem:
```
>>> xmlutil.listnodes()
['rm', 'alp-2']
>>> xmlutil.listnodes()
['rm', 'rm_node', 'alp-2']
```
-  Drop xmlutil.listnodes function; And refactor xmlutil.CrmMonXmlParser.get_node_list function, get pacemaker remote node from `crm_mon --output-as=xml` looks more accurately
- Enable standby/online pacemaker remote node
- Enable maintenance/ready pacemaker remote node

Dev: ui_node: Enable standby and maintenance on pacemaker remote node

---

Makefile
doc/Makefile

`CURDIR` is a make builtin and is more reliable than environment variable `PWD`.

Fix: packaging: use `CURDIR` instead of `PWD` in Makefile

---

crmsh/bootstrap.py
crmsh/sbd.py
test/unittests/test_bootstrap.py
test/unittests/test_sbd.py

This PR is a follow-up to #1905, addressing additional cases that were not covered in the previous PR.
- Dev: sbd: Check if fence-agents-sbd is installed for non sbd stage
```
ERROR: cluster.init: Package fence-agents-sbd is not installed
```
- Dev: sbd: Check if fence-agents-sbd is installed on interactive mode
```
...
Do you wish to use SBD (y/n)? y
SBD_DEVICE in /etc/sysconfig/sbd is already configured to use '/dev/sda5' - overwrite (y/n)? y
Path to storage device (e.g. /dev/disk/by-id/...), or "none" for diskless sbd, use ";" as separator for multi path []/dev/sda6
WARNING: All data on /dev/sda6 will be destroyed
Are you sure you wish to use this device (y/n)? y
ERROR: cluster.init: Package fence-agents-sbd is not installed
```
- Dev: sbd: Check if fence-agents-sbd is installed on …

Dev: sbd: Check if fence-agents-sbd is installed for other cases

---

crmsh/cibconfig.py
crmsh/ui_configure.py
crmsh/utils.py
test/testcases/confbasic.exp
test/testcases/resource.exp

1. When keeping OCF_1_1_SUPPORT to `no`, see #1918 
2. When setting OCF_1_1_SUPPORT to `yes`, `ms` command should be automatically converted to promotable clone
3. When setting OCF_1_1_SUPPORT to `yes` in /etc/crm/crm.conf, crmsh-4.6 has the same issue which was mentioned in https://github.com/ClusterLabs/crmsh/pull/1919#issue-3430202283
- To address problems 1 and 2, introduce utils.handle_deprecated_ms_command function, convert `ms` command to promotable clone if meeting conditions, otherwise, raise warning.
- To address problem 3, backport from #1919

[crmsh-4.6] Improvements for auto convert role and ms command
