ClusterLabs/crmsh

hb_report/hb_report.in
Synchronize crm report with hb_report. The -X feature was missing. -Q was not mentioned in the usage.
=> Sync hb report

doc/crm.8.adoc
Some self-explanatory changes.
=> improve fencing-topology docs

setup.py
it seems you already tagged a `2.2.1` release but `setup.py` wasn't updated.
=> fixed version number

hb_report/hb_report.in, hb_report/utillib.sh
dash dislikes initializing variables along with the local
statmement (and it's anyway bad practice).
=> Medium: hb_report: don't use backticks in local

crmsh/cliformat.py, crmsh/parse.py
This would add support for matching resource attributes and meta-attributes in location constraints (pacemaker PR 1208).
=> medium: Add support for pacemaker PR#1208

crmsh/ui_context.py
for issue [178](https://github.com/ClusterLabs/crmsh/issues/178)
=> remove _keywords/_objects/_regtest/_test options from tab completion

crmsh/command.py, crmsh/ui_context.py
Hi:
These are changes about cd completion:
* on the root level, complete sublevel names after "cd "
* on the sublevel, complete other sublevel path after "cd ../"
* prevent '..' completion happend many times when type "tab"
Regards,
xin
=> Improved cd completion:

crmsh/command.py
* sorted outputs
* print results column by column, like other complete results
=> Improve ls command outputs:

crmsh/bootstrap.py
for ucast and mcast port, valid range should between 1024-65536
=> medium: bootstrap: add callback function to check valid port range

doc/website-v1/index.adoc
=> Add missing ')'

crmsh/ui_cluster.py
just print help messages and return
=> low: ui_cluster: when use -h/--help option, do not exit

crmsh/help.py
adjust the width between cmd and cmd short description for long cmd name
=> low: help: adjust the help print width

crmsh/completers.py
if the action came from promote or demote, just filter out master/slave resource to complete
=> low: completers: filter out ms resource when doing promote/demote

crmsh/bootstrap.py
=> low: bootstrap: color the input error message

crmsh/ui_cluster.py, doc/crm.8.adoc
to make "cluster run" more flexible
Thanks,
xin
=> low: ui_cluster: run command on a specific node

crmsh/ui_cluster.py
it's easy to read the status log which log block belongs what node:)
Thanks,
xin
=> low: ui_cluster: Add two new lines before add a new node

crmsh/bootstrap.py, crmsh/utils.py, test/unittests/test_utils.py
commit medium: utils: extend "IP/Network" codes for IPv4/IPv6 calculation
and add test codes for testing:
1) Check if the given ip is part of the network
2) get ipv6 network
==============================
based on above commit,
second commit is -- medium: bootstrap: valid adminIP
The administration virtaul IP must:
1) have a valid IPv4/IPv6 formation
2) belongs one of local networks
=> medium: bootstrap: valid adminIP

crmsh/main.py
is this necessary?
I think it's more clear when in cluster level
=> low: main: add hostname in promptstr

crmsh/bootstrap.py, crmsh/utils.py
a valid adminIP should also:
1) not be the network address
2) not be exist address
=> medium: bootstrap: valid adminIP rules update

crmsh/bootstrap.py, crmsh/utils.py
against with commit #265 
maybe can save a little running time:)
regards,
xin
=> low: bootstrap: simplify the code for checking adminIP

crmsh/bootstrap.py
For example, firewalld and ufw are available in Debian.
=> Detect firewall by checking installed packages

crmsh/bootstrap.py
Disables pacemaker mode and enables watchdog device.
=> Fix SBD configuration when using SBD device (Fixes #235)

crmsh/cibconfig.py, crmsh/ui_configure.py
when modgroup, 
after "add", id should not from any groups, 
after "remove", id must from the specific group,
after "after/before", id must from the specific group
=> medium: ui_configure: in modgroup, add free id and remove id in group

crmsh/ui_node.py
and define a new completer function "_find_utilization" to complete utilization attrs
BTW: in ui_node, do_attribute and do_status_attr seems have the same problem
=> medium: ui_node: node utilization is about node attr, not for resources

crmsh/ui_corosync.py
* add completer to complete node for delete
* limit to udpu transport according to del_node in corosync.py
=> medium: ui_corosync: adjust for do_delnode

crmsh/bootstrap.py
* we can add other option checkings to here later
=> medium: bootstrap: check init options before running

crmsh/bootstrap.py, crmsh/corosync.py, crmsh/ui_cluster.py, crmsh/utils.py
With "-M" option after cluster init, user can add a second connection line
Regards,
xin
=> low: bootstrap: change multi-heartbeats as option-mode

crmsh/ui_configure.py, crmsh/utils.py
Apply this commit to avoid this completion situation:
1 primitive vip ocf:Heartbeat:IPaddr2 params ip=10.10.10.123 nic=eth1 nic=xxxx ip=xxxx
2 primitive vip ocf:Heartbeat:IPaddr2 meta is-managed=xxx is-managed=xxx
=> medium: filter exist args

crmsh/constants.py, crmsh/ui_configure.py
We should complete clone meta keywords like "interleave" because user wouldn't remember these.
BTW, It' nice that if we add some help messages for meta attributes like primitive params,
give some hints for suggestion value
=> low: ui_configure: Improve do_clone completer

crmsh/constants.py, crmsh/ui_configure.py
like #316 , improve group and ms completer, and integrate them into one function
Regards,
xin
=> low: ui_configure: Improve group/clone/ms completer

scripts/nginx/main.yml
Use apache as template
Thanks:)
Regards,
xin
=> Low: script: Add nginx script for Hawk

crmsh/cibconfig.py, crmsh/constants.py, crmsh/parse.py, crmsh/ui_configure.py, crmsh/utils.py, data-manifest, test/testcases/basicset, test/testcases/bundle, test/testcases/bundle.exp
Hi all:
This commit is about bundle sub-command, changes include:
1. both docker and rkt container types are supported(create/delete/edit/show)
2. all options and keywords about bundle are well completed(include container options/network/network-mapping/storage(-mapping)/primitive/meta)
3. options with help messages which from latest documents in clusterlabs
Todo list:
1. test scripts
2. inputs validation if needed
3. more test
Any help or suggestions are welcome!
Thanks!
Regards,
xin
=> dev: bundle: add bundle sub-command

crmsh/ra.py
=> fix: ra: Convert bytes to str

crmsh/ui_configure.py
element primitives in group should be one or more
=> low: ui_configure: improve do_group completer

hb_report/utillib.py
Collect irregular time-format log file such as ha-cluster-bootstrap.log.
I will fire a bug if this commit make sense
=> fix: hb_report: Collect irregular log file

hb_report/utillib.py
implement dlm dump info which from original shell-hb_report
=> medium: hb_report: implement dlm_dump info(bsc#1078710)

hb_report/utillib.py
Command 'file /var/log/messages' return 'data', 
So, this will cause lose /var/log/messages :(
=> fix: hb_report: got the right file decompressor(bsc#1077553)

crmsh/bootstrap.py
Changed:
1. Using dd to create /etc/pacemaker/authkey when cluster->init
2. sync this key to other nodes when other nodes run cluster->join
other:
Maybe need copy this authkey to the remote node manually.
=> fix: bootstrap: Create pacemaker_remote authkey(#bsc 1077389)

doc/crm.8.adoc, doc/website-v1/man-1.2.adoc, doc/website-v1/man-2.0.adoc
Sorry, forgot them in the previous PR.
=> low: doc: Fix remaining references to oxf:... resource agent

crmsh/constants.py, crmsh/ui_context.py, crmsh/utils.py
refer to #298,
this is a common way to fix this problem:)
=> low: terminal will lose cursor after type ctrl+c(bsc#1090626)

crmsh/config.py, crmsh/constants.py, crmsh/main.py, crmsh/ra.py, crmsh/ui_ra.py, crmsh/utils.py, test/containerized-regression-tests.sh, test/run-in-container.sh
Fix the problems with finding the correct pacemaker daemon path, and support the new Pacemaker 2.0 daemon names.
=> Pacemaker daemon path fixes

crmsh/ui_context.py
=> dev: make command accept -h or --help option

crmsh/command.py
for issue #377 
We do not show/complete all sub-commands alias, but when input original alias,
that will work
=> dev: drop all sub-command alias while provide compatibility

hb_report/constants.py, hb_report/utillib.py
Hi krig,
Could you please review the pull request?
Thanks
=> support ocfs2 log collecting

crmsh/bootstrap.py, crmsh/utils.py
Add logic for detecting cloud platforms. Currently able to detect AWS, Azure and GCP.
=> medium: utils: Detect cloud platform (bsc#1106946)

crmsh/utils.py
=> dev: utils: Fix issues with cloud detection

utils/crm_pkg.py
Allows package management on Debian and Ubuntu.
=> low: utils: add support for apt-get

utils/crm_rpmcheck.py
For checking package status on Debian and Ubuntu.
=> low: utils: add support for dpkg

crmsh/constants.py, doc/crm.8.adoc, test/testcases/confbasic, test/testcases/confbasic.exp
According to https://wiki.clusterlabs.org/wiki/Pacemaker_2.0_Configuration_Changes#Promotable_clone_resources,
add "promotable", "promoted-max" and "promoted-node-max" tag in clone_meta_attributes
=> Support new meta attributes for clone

hb_report/utillib.py
to solve this bug: https://bugzilla.suse.com/show_bug.cgi?id=1129719
=> Fix: bsc#1129719: check command and related files exist

hb_report/constants.py, hb_report/utillib.py
- Output of "sbd dump"
- Output of "sbd list"
On diskless sbd mode, no output in sbd.txt
=>  low: hb_report: collect output of "sbd dump" and "sbd list"(bsc#1129383)

ChangeLog, crmsh/ui_maintenance.py
* Release 3.0.4
* auto-commit enabling/disabling maintenance mode for a whole cluster
=> Change log update for 3.0.4 and bug fix for bsc#1112593

.travis.yml, README.md
As soon as a Pull Request gets merged, a new RPM package will be built on network:ha-clustering:Unstable and a submit request will be created to the crmsh package maintainers at network:ha-clustering:Factory. This will update the package and change log using the _service available on OBS.
This PR depends on the merge of this PR: https://github.com/arbulu89/continuous-delivery/pull/1
=> Obs service integration

hb_report/constants.py, hb_report/hb_report.in, hb_report/utillib.py, test/unittests/pacemaker.log, test/unittests/pacemaker_unicode.log, test/unittests/test_report.py
* unittest: add test_report.py to test hb_report module
- cover most functions hb_report related
- use special characters(see test/unittests/pacemaker_unicode.log) and invalid utf-8 in test case
* setting error='replace' to handle UnicodeDecodeError caused by invalid utf-8 characters(bsc#1130715)
* try to catch UnicodeDecodeError and print traceback
* Using Tempfile class to manage tempfiles
=> hb_report unittest

crmsh/utils.py
also for bsc#1137783, on 12sp3, so we need back port
=> medium: bootstrap: Pick first match for multiple routes (bsc#1106946)

crmsh/utils.py, test/unittests/test_utils.py
When coming string has non utf-8 characters the
error is ignored
Fixes bsc#1138115
=> Fix issue in to_ascii (bsc#1138115)

doc/crm.8.adoc, doc/website-v1/man-1.2.adoc, doc/website-v1/man-2.0.adoc, doc/website-v1/man-3.adoc
=> doc: manpages: Fix spelling

crmsh/ui_resource.py, doc/crm.8.adoc, doc/website-v1/man-2.0.adoc, doc/website-v1/man-3.adoc, test/testcases/resource, test/testcases/resource.exp
The maintenance and is-managed are conflicting atributes. When setting
one of them, the user is proposed to remove another.
=> Dev: ui_resource: resolve maintenance vs is-managed conflict

test/run
Make sure we can also see which unit test case has passed successfully
=> Dev: unittest: make unittest results more verbose

.travis.yml, crmsh/bootstrap.py, crmsh/ui_cluster.py, test/unittests/test_bootstrap.py
Back port #476 to crmsh-3.0 branch
=> [crmsh-3.0]Low: bootstrap: don't overwrite ssh key if already exists

test/unittests/test_report.py
Use current year instead of assuming 2019.
=> dev: unittest: fix test_report.py failing in 2020

.travis.yml, crmsh/bootstrap.py, data-manifest, test/features/bootstrap_bugs.feature, test/features/steps/step_implenment.py, test/unittests/__init__.py, test/unittests/test_bugs.py
According to [pacemaker explained](https://clusterlabs.org/pacemaker/doc/en-US/Pacemaker/2.0/html/Pacemaker_Explained/s-cluster-options.html), set the value of cluster option "placement-strategy" as "default"
=> Fix: bootstrap: set placement-strategy value as "default"(bsc#1129462)

.travis.yml, crmsh/bootstrap.py, data-manifest, test/features/bootstrap_bugs.feature, test/features/steps/step_implenment.py, test/unittests/__init__.py, test/unittests/test_bugs.py
=> [crmsh-4.1] Fix: bootstrap: set placement-strategy value as "default"(bsc#1129462)

crmsh/bootstrap.py, test/unittests/__init__.py, test/unittests/test_bugs.py
=> [crmsh-3.0] Fix: bootstrap: set placement-strategy value as "default"(bsc#1129462)

crmsh/bootstrap.py, crmsh/ui_cluster.py
backport #492 to crmsh-3.0 branch
=> [crmsh-3.0] Improve multi sbd case usability

crmsh/bootstrap.py, crmsh/ui_cluster.py
backport #489 and #492 to crmsh-4.1 branch
=> [crmsh-4.1] Improve multi sbd case usability

crmsh.spec
First, update the spec file from ibs
Then, backport from #502
=> [crmsh-3.0] Update spec file and backport for mktemp issue

crmsh/main.py, crmsh/ui_cluster.py, data-manifest, test/features/bootstrap_options.feature, test/features/steps/const.py, test/features/steps/step_implenment.py
Backport from #469 
BTW, for **multi sbd** and **--no-overwrite-sshkey**, this branch is the same with the master branch;
For **qdevice**, since this branch originally includes some simple qdevice options, I just improve `help` and `metavar` parameters for existing qdevice related options
=> [crmsh-4.1] Dev: replace optparse with argparse

hb_report/utillib.py, test/unittests/test_report.py
=> [crmsh-4.1] Fix: hb_report: disable dump all tasks stack into dmesg(bsc#1158060)

.travis.yml, crmsh/main.py, crmsh/ui_cluster.py, crmsh/utils.py, test/features/bootstrap_bugs.feature
=> [crmsh-4.1] Fix: Not allowed space value for option(bsc#1141976)

crmsh/main.py, crmsh/ui_cluster.py, crmsh/utils.py
=> [crmsh-3.0] Fix: Not allowed space value for option(bsc#1141976)

.travis.yml, Dockerfile, crmsh/parallax_helper.py, crmsh/utils.py, data-manifest, test/docker_scripts.sh, test/features/bootstrap_bugs.feature, test/features/bootstrap_init_join_remove.feature, test/features/bootstrap_options.feature, test/features/environment.py, test/features/steps/const.py, test/features/steps/step_implenment.py, test/features/steps/utils.py, test/run-in-travis.sh, test/unittests/test_parallax.py
* Backport parallax related PR from #482, since behave will use parallax a lot
* travis: Change the Dockerfile and image for testing
* behave: backport functional test using behave from master branch
=> [crmsh-3.0] Functional test using behave

crmsh/ui_configure.py, data-manifest, doc/crm.8.adoc, test/features/resource_set.feature, test/features/steps/step_implenment.py
=> [crms-4.1] Feature: configure: make configure.set to update operation

crmsh/minieval.py
When the unitetss are run with python 3.8 they break on changes in ast.
File "/usr/lib/python3/dist-packages/crmsh/minieval.py", line 222, in _eval
handler = self.nodes[type(node)]
KeyError: <class '_ast.Constant'>
This is due to [1] which states "Class ast.Constant is now used for all
constants. Old classes ast.Num, ast.Str, ast.Bytes, ast.NameConstant and
ast.Ellipsis are still available, but they will be removed in future
Python releases.".
Even thou this is just the deprecation it already triggers an error
in the tests of crmsh.
[1]: https://docs.python.org/3/library/ast.html#ast.AST
Fixes #518
Signed-off-by: Christian Ehrhardt <christian.ehrhardt@canonical.com>
=> scripts: python3.8 unittest compatibility

test/unittests/test_utils.py
Unit test for `detect_cloud` method
=> Low: unittest: add unit test to detect_cloud

.coveragerc, .travis.yml, pytest.ini, requirements.txt, setup.py, test/run-in-travis.sh, test/unittests/test_bugs.py, test/unittests/test_cib.py, test/unittests/test_cliformat.py, test/unittests/test_handles.py, test/unittests/test_objset.py, test/unittests/test_parse.py, test/unittests/test_scripts.py, test/unittests/test_time.py, tox.ini
=> [crmsh-3.0] Replace nose with pytest

crmsh/bootstrap.py, crmsh/utils.py, test/unittests/test_utils.py
Backport from #392 #522 and #524
And this PR depend on #530 , we should deploy pytest in crmsh-3 branch firstly
=> [crmsh-3.0] Low: utils: update detect_cloud pattern for aws

crmsh/bootstrap.py, crmsh/corosync.py, crmsh/utils.py, test/docker_scripts.sh, test/features/bootstrap_bugs.feature, test/features/steps/step_implenment.py, test/features/steps/utils.py, test/unittests/test_bootstrap.py, test/unittests/test_corosync.py
=> [crmsh-4.1] For udpu, don't check join node's ip was in the same network 

crmsh/bootstrap.py, crmsh/corosync.py, crmsh/utils.py, test/docker_scripts.sh, test/features/bootstrap_bugs.feature, test/features/steps/step_implenment.py, test/features/steps/utils.py, test/unittests/test_bootstrap.py, test/unittests/test_corosync.py
=> [crmsh-3.0] For udpu, don't check join node's ip was in the same network

configure.ac, crmsh.spec.in, setup.py
And sync contents from NHF's crmsh.spec
=> Fix bash completion(bsc#1166329)

crmsh/bootstrap.py, test/unittests/test_bootstrap.py
=> [crmsh-4.1] Resolve csync2 conflicts(bsc#1166684)

crmsh/bootstrap.py, test/unittests/test_bootstrap.py
=> [crmsh-3.0] Resolve csync2 conflicts(bsc#1166684)

crmsh/bootstrap.py
=> [crmsh-4.1]Dev: bootstrap: binding interface when calling "crm cluster init"

crmsh/bootstrap.py
=> [crmsh-3.0]Dev: bootstrap: binding interface when calling "crm cluster init"

crmsh/bootstrap.py
=> [crmsh-4.1] Fix: bootstrap: Change condition to add stonith-sbd resource

crmsh/bootstrap.py
=> [crmsh-3.0] Fix: bootstrap: Change condition to add stonith-sbd resource

.travis.yml, crmsh/bootstrap.py, crmsh/ui_cluster.py, data-manifest, test/docker_scripts.sh, test/features/bootstrap_bugs.feature, test/features/geo_setup.feature, test/run-in-travis.sh
=> [crmsh-4.1] Simplify bootstrap context

crmsh/main.py, crmsh/ui_cluster.py, test/features/steps/const.py
=> [crmsh-3.0] Dev: replace optparse with argparse

crmsh/ui_context.py, test/crm-interface, test/features/bootstrap_bugs.feature, test/testcases/bugs.exp, test/testcases/confbasic.exp, test/testcases/history.exp, test/testcases/resource.exp
=> [crmsh-4.1] Low: ui_context: give warning if using alias command

doc/crm.8.adoc
=> [crmsh-4.1] Fix: doc: Update man page about completion example of crm resource

.travis.yml, crmsh/bootstrap.py, crmsh/ui_cluster.py, data-manifest, test/docker_scripts.sh, test/features/bootstrap_bugs.feature, test/features/geo_setup.feature, test/run-in-travis.sh
=> [crmsh-3.0] Simplify bootstrap context

crmsh/ui_cluster.py, crmsh/utils.py, test/unittests/test_report.py, test/unittests/test_utils.py
=> [crmsh-4.1] Validate interface using argparse choices

crmsh/ui_cluster.py, crmsh/utils.py, test/unittests/test_utils.py
=> [crmsh-3.0] Validate interface using argparse choices

crmsh/bootstrap.py
When doing some ssh/scp jobs, ssh connect will failed if not input password for a long time.
In that way, process should exit, and with proper error messages
=> Low: bootstrap: exit with proper error messages when ssh return failed

Makefile.am, crmsh.spec.in, crmsh/bootstrap.py, crmsh/config.py
Let's store the bootstrap logs in the more specific location.
=> Low: bootstrap: change ha-cluster-bootstrap log path

crmsh/bootstrap.py, crmsh/constants.py, crmsh/corosync.py, crmsh/crm_pssh.py, crmsh/parallax.py, crmsh/scripts.py, crmsh/ui_cluster.py, crmsh/utils.py, hb_report/utillib.py, test/features/bootstrap_bugs.feature, test/features/bootstrap_init_join_remove.feature, test/features/bootstrap_options.feature, test/features/geo_setup.feature, test/features/resource_failcount.feature, test/features/resource_set.feature, test/features/steps/const.py, test/features/steps/utils.py, test/unittests/test_bootstrap.py, test/unittests/test_utils.py
=> [crmsh-4.1] Fix: bootstrap: crmsh use its own specific ssh key(bsc#1169581)

crmsh/bootstrap.py, crmsh/constants.py, crmsh/corosync.py, crmsh/crm_pssh.py, crmsh/parallax_helper.py, crmsh/scripts.py, crmsh/ui_cluster.py, crmsh/utils.py, test/features/bootstrap_bugs.feature, test/features/bootstrap_init_join_remove.feature, test/features/bootstrap_options.feature, test/features/geo_setup.feature, test/features/steps/const.py, test/features/steps/utils.py, test/unittests/test_bootstrap.py, test/unittests/test_utils.py
=> [crmsh-3.0] Fix: bootstrap: crmsh use its own specific ssh key(bsc#1169581)

crmsh/bootstrap.py, crmsh/ui_cluster.py, data-manifest, test/features/bootstrap_sbd.feature, test/features/steps/step_implenment.py, test/unittests/test_bootstrap.py
=> [crmsh-4.1] SBD management improve

crmsh/bootstrap.py, crmsh/ui_cluster.py, data-manifest, test/features/bootstrap_sbd.feature, test/features/steps/step_implenment.py, test/unittests/test_bootstrap.py
=> [crmsh-3.0] SBD management improve

crmsh/bootstrap.py, crmsh/constants.py, crmsh/corosync.py, crmsh/crm_pssh.py, crmsh/parallax.py, crmsh/scripts.py, crmsh/ui_cluster.py, crmsh/utils.py, hb_report/utillib.py, test/features/bootstrap_bugs.feature, test/features/bootstrap_init_join_remove.feature, test/features/bootstrap_options.feature, test/features/geo_setup.feature, test/features/resource_failcount.feature, test/features/resource_set.feature, test/features/steps/const.py, test/features/steps/utils.py, test/unittests/test_bootstrap.py, test/unittests/test_utils.py
Followint PR #597 , revert PR #577
=> [crmsh-4.1] Revert PR#577 -- Fix: bootstrap: crmsh use its own specific ssh key(bsc#1169581)

crmsh/bootstrap.py, crmsh/constants.py, crmsh/corosync.py, crmsh/crm_pssh.py, crmsh/parallax_helper.py, crmsh/scripts.py, crmsh/ui_cluster.py, crmsh/utils.py, test/features/bootstrap_bugs.feature, test/features/bootstrap_init_join_remove.feature, test/features/bootstrap_options.feature, test/features/geo_setup.feature, test/features/steps/const.py, test/features/steps/utils.py, test/unittests/test_bootstrap.py, test/unittests/test_utils.py
Following PR #597 , revert PR #578
=> [crmsh-3.0] Revert PR#578 -- Fix: bootstrap: crmsh use its own specific ssh key(bsc#1169581) 

crmsh/bootstrap.py, crmsh/corosync.py, crmsh/ui_cluster.py, crmsh/utils.py, test/docker_scripts.sh, test/features/bootstrap_options.feature, test/features/steps/const.py, test/features/steps/step_implenment.py, test/unittests/test_bootstrap.py, test/unittests/test_corosync.py, test/unittests/test_utils.py
=> [crmsh-4.1] Bootstrap network improvement

crmsh/bootstrap.py, crmsh/ui_cluster.py, crmsh/utils.py, test/features/bootstrap_bugs.feature, test/features/bootstrap_init_join_remove.feature, test/features/bootstrap_options.feature, test/features/geo_setup.feature, test/features/resource_failcount.feature, test/features/resource_set.feature, test/unittests/test_bootstrap.py, test/unittests/test_utils.py
=> [crmsh-4.1] bootstrap process will not overwrite existing ssh keys

crmsh/bootstrap.py, crmsh/ui_cluster.py, crmsh/utils.py, test/features/bootstrap_bugs.feature, test/features/bootstrap_init_join_remove.feature, test/features/bootstrap_options.feature, test/features/geo_setup.feature, test/unittests/test_bootstrap.py, test/unittests/test_utils.py
=> [crmsh-3.0] bootstrap process will not overwrite existing ssh keys

crmsh/bootstrap.py, test/features/bootstrap_sbd.feature, test/unittests/test_bootstrap.py
=> [crmsh-4.1] Adjust sbd configure process in stage

crmsh/bootstrap.py, test/features/bootstrap_sbd.feature, test/unittests/test_bootstrap.py
=> [crmsh-3.0] Adjust sbd configure process in stage

.travis.yml, data-manifest, hb_report/utillib.py, test/features/hb_report_bugs.feature, test/features/steps/step_implenment.py, test/features/steps/utils.py, test/unittests/test_report.py
=> [crmsh-4.1] hb report include archived log

.travis.yml, crm.conf.in, crmsh/config.py, crmsh/ui_configure.py, data-manifest, doc/crm.8.adoc, test/features/configure_bugs.feature, test/features/steps/step_implenment.py, test/run-in-travis.sh
=> [crmsh-4.1] Obscure sesitive data by default

.travis.yml, crm.conf.in, crmsh/config.py, crmsh/ui_configure.py, data-manifest, doc/crm.8.adoc, test/features/configure_bugs.feature, test/features/steps/step_implenment.py, test/features/steps/utils.py, test/run-in-travis.sh
=> [crmsh-3.0] Obscure sesitive data by default

scripts/lvm/main.yml, scripts/raid1/main.yml, scripts/sapdb/main.yml, scripts/sapinstance/main.yml
see #bsc1176569 @liangxin1300 cc
=> fix on_fail should be on-fail

scripts/lvm/main.yml, scripts/raid1/main.yml, scripts/sapdb/main.yml, scripts/sapinstance/main.yml
=> [crmsh-4.1] fix on_fail should be on-fail

scripts/lvm/main.yml, scripts/raid1/main.yml, scripts/sapdb/main.yml, scripts/sapinstance/main.yml
=> [crmsh-3.0] fix on_fail should be on-fail

crmsh/bootstrap.py, crmsh/corosync.py, crmsh/ui_cluster.py, crmsh/utils.py, test/features/bootstrap_bugs.feature, test/features/bootstrap_options.feature, test/features/steps/step_implenment.py, test/features/steps/utils.py, test/unittests/test_bootstrap.py
=> [crmsh-4.1] Fix bug of remove node(bsc#1165644) 

crmsh/bootstrap.py, crmsh/corosync.py, crmsh/utils.py, test/features/bootstrap_bugs.feature, test/features/bootstrap_options.feature, test/features/steps/step_implenment.py, test/features/steps/utils.py, test/unittests/test_bootstrap.py
=> [crmsh-3.0] Fix bug of remove node(bsc#1165644)

crmsh/bootstrap.py, crmsh/utils.py, test/unittests/test_bootstrap.py, test/unittests/test_utils.py
1. Check whether sbd package was installed
2. Add `utils.run_cmd_on_remote` function
3. Change `utils.package_is_installed` function
=> [crmsh-4.1] sync with master branch for some minor changes

crmsh/bootstrap.py, crmsh/utils.py, test/unittests/test_bootstrap.py, test/unittests/test_utils.py
=> [crmsh-3.0] sync with master branch for some minor changes

crmsh/bootstrap.py, test/features/bootstrap_bugs.feature, test/features/steps/utils.py, test/unittests/test_bootstrap.py
crmsh should stop hawk.service when removing node
=> Stop hawk service when removing node

crmsh/bootstrap.py, crmsh/utils.py, test/unittests/test_bootstrap.py, test/unittests/test_utils.py
=> [crmsh-4.1] Refactor service management codes

crmsh/bootstrap.py, crmsh/utils.py, test/unittests/test_bootstrap.py, test/unittests/test_utils.py
=> [crmsh-3.0] Refactor service management codes 

crmsh/bootstrap.py, test/features/bootstrap_bugs.feature, test/features/steps/utils.py, test/unittests/test_bootstrap.py
=> [crmsh-3.0] Stop hawk service when removing node 

crmsh/ui_cluster.py, test/unittests/test_ui_cluster.py
=> [crmsh-3.0] Check cluster service status while start or stop

crmsh/ui_cluster.py, test/unittests/test_ui_cluster.py
=> [crmsh-4.1] Check cluster service status while start or stop

test/unittests/test_bugs.py
=> [crmsh-3.0] Dev: unittest: adjust duplicated test function name

hb_report/utillib.py, test/features/hb_report_bugs.feature
=> [crmsh-4.1] Fix: hb_report: collect corosync.log if it defined in config file(bsc#1148874)

crmsh/bootstrap.py, test/unittests/test_bootstrap.py
=> [crmsh-4.1] Minor change for _get_sbd_device_interactive function

crmsh/bootstrap.py, test/unittests/test_bootstrap.py
=> [crmsh-3.0] Minor change for _get_sbd_device_interactive function

crmsh/bootstrap.py, crmsh/utils.py, test/unittests/test_utils.py
=> [crmsh-3.0] Dev: bootstrap: use ping to test host is reachable before joining

crmsh/bootstrap.py, crmsh/utils.py, test/unittests/test_utils.py
=> [crmsh-4.1] Dev: bootstrap: use ping to test host is reachable before joining

.github/workflows/crmsh-ci.yml
=> [crmsh-3.0] Dev: test: add timeout-minutes to each test job

.github/workflows/crmsh-ci.yml
=> [crmsh-4.1] Dev: test: add timeout-minutes to each test job

test/docker_scripts.sh, test/features/bootstrap_bugs.feature, test/features/bootstrap_options.feature
=> [crmsh-3.0] Simplify container deploy bash script docker_scripts.sh for functional test 

crmsh/bootstrap.py, test/unittests/test_bootstrap.py
=> [crmsh-4.1] Dev: bootstrap: improve invoke to print error to give specific hints

crmsh/bootstrap.py, test/unittests/test_bootstrap.py
=> [crmsh-3.0] Dev: bootstrap: improve invoke to print error to give specific hints

data-manifest, preflight_check/task.py, test/unittests/test_preflight_check.py, test/unittests/test_preflight_main.py, test/unittests/test_preflight_task.py, test/unittests/test_preflight_utils.py, tox.ini
=> Unit test code for preflight check module

hb_report/utillib.py, test/unittests/test_report.py
=> [crmsh-4.1] Fix: hb_report: run lsof with specific ocfs2 device

hb_report/utillib.py
=> [crmsh-4.1] Add entry limitation for dump_ocfs2 function

crmsh/lock.py, test/unittests/test_lock.py
=> [crmsh-4.1] Dev: lock: give more specific error message when raise ClaimLockError

crmsh/lock.py, test/unittests/test_lock.py
=> [crmsh-3.0] Dev: lock: give more specific error message when raise ClaimLockError

crmsh/corosync.py, crmsh/utils.py
Compare with #726, this PR was more generic
=> Dev: utils: change default file mod as 644 for str2file function

crmsh/bootstrap.py, crmsh/utils.py, hb_report/hb_report.in, test/unittests/test_bootstrap.py
=> [crmsh-3.0] Run hb_report under hacluster

crmsh/bootstrap.py, crmsh/utils.py, hb_report/hb_report.in, hb_report/utillib.py, test/unittests/test_bootstrap.py
=> [crmsh-4.1] Run hb_report under hacluster

crmsh/ra.py, crmsh/ui_configure.py
=> [crmsh-3.0] Fix: ui_configure: raise error when params not exist

crmsh/ra.py, crmsh/ui_configure.py
=> [crmsh-4.1] Fix: ui_configure: raise error when params not exist

crmsh/ui_node.py, doc/crm.8.adoc
=> [crmsh-3.0] Remove crm node status subcommand

crmsh/ui_node.py, doc/crm.8.adoc
=> [crmsh-4.1] Remove crm node status subcommand

crmsh/cibconfig.py
According issue #759 , and consider from very early version of pacemaker, crm_diff has `--no-version`, remove unneeded related codes in this PR
=> Dev: cibconfig: remove related code about detecting crm_diff support --no-version

crmsh/cibconfig.py
=> [crmsh-4.1] Dev: cibconfig: remove related code about detecting crm_diff support --no-version

crmsh/cibconfig.py
=> [crmsh-3.0] Dev: cibconfig: remove related code about detecting crm_diff support --no-version

crmsh/corosync.py, crmsh/ui_cluster.py, crmsh/ui_corosync.py, crmsh/ui_node.py, crmsh/utils.py
=> [crmsh-4.1] Dev: utils: remove unused utils.cluster_stack and its related codes

crmsh/corosync.py, crmsh/ui_cluster.py, crmsh/ui_corosync.py, crmsh/ui_node.py, crmsh/utils.py
=> [crmsh-3.0] Dev: utils: remove unused utils.cluster_stack and its related codes

crmsh/lock.py, test/features/bootstrap_bugs.feature, test/unittests/test_lock.py
=> [crmsh-4.1] Change lock directory under /run

crmsh/lock.py, test/features/bootstrap_bugs.feature, test/unittests/test_lock.py
=> [crmsh-3.0] Change lock directory under /run

crmsh/ui_resource.py, test/features/resource_failcount.feature
=> [crmsh-4.1] Fix: ui_resource: change return code and error to warning for some unharmful actions

configure.ac, setup.py
=> [crmsh-4.1] Fix: update verion and author

configure.ac, setup.py
=> [crmsh-3.0] Fix: update verion and author

crmsh/bootstrap.py, crmsh/utils.py, test/unittests/test_bootstrap.py, test/unittests/test_utils.py
=> [crmsh-4.1] Support parse space in sbd device name

crmsh/bootstrap.py, crmsh/utils.py, test/unittests/test_bootstrap.py, test/unittests/test_utils.py
=> [crmsh-3.0] Support parse space in sbd device name

crmsh/bootstrap.py, crmsh/corosync.py, crmsh/utils.py, test/unittests/test_bootstrap.py, test/unittests/test_corosync.py
=> [crmsh-4.1] Fix: bootstrap: sync files before finished joining

crmsh/bootstrap.py, crmsh/corosync.py, crmsh/utils.py, test/unittests/test_bootstrap.py, test/unittests/test_corosync.py
=> [crmsh-3.0] Fix: bootstrap: sync files before finished joining

crmsh/bootstrap.py, test/unittests/test_bootstrap.py
=> [crmsh-4.1] Adjust/Disable unnecessary warnings

crmsh/bootstrap.py, test/unittests/test_bootstrap.py
=> [crmsh-3.0] Adjust/Disable unnecessary warnings

crmsh/bootstrap.py, test/unittests/test_bootstrap.py
backport #803 and #812
Additional change include "Dev: bootstrap: make update_expected_votes as outer function for reuse"
=> [crmsh-3.0] Change status_long function by using contextmanager

crmsh/bootstrap.py, test/unittests/test_bootstrap.py
backport #803 and #812
Additional change include "Dev: bootstrap: make update_expected_votes as outer function for reuse"
=> [crmsh-4.1] Change status_long function by using contextmanager 

crmsh/bootstrap.py, crmsh/constants.py, crmsh/utils.py, test/unittests/test_bootstrap.py
=> [crmsh-3.0] Fix: bootstrap: change StrictHostKeyChecking=no as a constant

crmsh/bootstrap.py, crmsh/constants.py, crmsh/utils.py, test/unittests/test_bootstrap.py
=> [crmsh-4.1] Fix: bootstrap: change StrictHostKeyChecking=no as a constant

crmsh/cibconfig.py
=> [crmsh-4.1] Dev: cibconfig: resolve TypeError for fencing-topology tag

crmsh/cibconfig.py
=> [crmsh-3.0] Dev: cibconfig: resolve TypeError for fencing-topology tag

crmsh/history.py, crmsh/utils.py, test/testcases/history.exp
And check if the directory name was sane
=> Fix: history: use Path.mkdir instead of mkdir command

crmsh/bootstrap.py, crmsh/utils.py, test/unittests/test_bootstrap.py, test/unittests/test_utils.py
=> [crmsh-4.3] Dev: sbd: enable SBD_DELAY_START in virtualization environment 

crmsh/help.py, crmsh/ui_cluster.py, crmsh/ui_context.py, doc/crm.8.adoc, test/features/steps/const.py
=> [crmsh-4.1] Show help message from command line if that subcommand use argparse

crmsh/bootstrap.py
=> [crmsh-4.3] Fix: bootstrap: check for missing fields in 'crm_node -l' output

crmsh/ui_resource.py, data-manifest, test/unittests/test_bugs.py, test/unittests/test_ratrace.py
=> [crmsh-4.1] Fix: resource: make untrace consistent with trace

crmsh/ui_resource.py, data-manifest, test/unittests/test_bugs.py, test/unittests/test_ratrace.py
=> [crmsh-4.3] Fix: resource: make untrace consistent with trace

crmsh/ocfs2.py, test/unittests/test_ocfs2.py
=> Dev: ocfs2: set no-quorum-policy as freeze when configuring OCFS2

crmsh/ui_context.py, test/testcases/bugs.exp, test/testcases/confbasic.exp, test/testcases/history.exp, test/testcases/resource.exp
=> [crmsh-4.3] Dev: ui_context: Add info when spell-corrections happen

crmsh/ra.py, test/testcases/common.excl
=> [crmsh-4.3] Medium: ra: performance/usability improvement (avoid systemd)

crmsh/ui_resource.py, test/testcases/resource.exp
* Show the specific directory under /var/lib/heartbeat/trace_ra/
* Give info when untrace ra
=> Dev: ui_resource: Enhancement trace output

crmsh/ui_resource.py, test/testcases/resource.exp
=> [crmsh-4.3] Dev: ui_resource: Enhancement trace output

crmsh/constants.py, crmsh/utils.py, test/unittests/test_utils.py
=> [crmsh-4.3] Fix: utils: Improve detect_cloud function and support non-Hyper-V in Azure

crmsh/constants.py, crmsh/utils.py, test/unittests/test_utils.py
=> [crmsh-4.1] Fix: utils: Improve detect_cloud function and support non-Hyper-V in Azure

crmsh/log.py
Use RotatingFileHandler class to rotated crmsh.log, archived when reach 1M size, keep latest 10 archived log
=> Dev: log: Rotate crmsh.log as 1M and backup count as 10

crmsh/ui_resource.py, test/features/resource_set.feature, test/features/steps/step_implenment.py
=> [crmsh-4.3] Fix: ui_resource: Parse node and lifetime correctly

crmsh/bootstrap.py, crmsh/cibconfig.py, crmsh/constants.py, crmsh/log.py, crmsh/ocfs2.py, crmsh/sbd.py, crmsh/utils.py, crmsh/xmlutil.py, test/unittests/test_bootstrap.py, test/unittests/test_ocfs2.py, test/unittests/test_sbd.py, test/unittests/test_utils.py, test/unittests/test_xmlutil.py
See #902
- Add `xmlutil.CrmMonXmlParser.is_node_online` to check if node is online
- Add `xmlutil.CrmMonXmlParser.is_resource_configured` to check if the RA configured
- Add `xmlutil.CrmMonXmlParser.is_any_resource_running` to check if any RA is running
- Add `xmlutil.CrmMonXmlParser.is_resource_started` to check if the RA started(in all clone instances if configured as clone)
=> Dev: xmlutil: Add class CrmMonXmlParser to parse xml output of crm_mon

Makefile.am, crmsh.spec.in, doc/crm.8.adoc, doc/profiles.adoc
see #901, mention /etc/crm/profiles.yml(see #842) in man crm
=> Dev: doc: Mention /etc/crm/profiles.yml in man crm

crmsh/bootstrap.py
=> [crmsh-4.3] Fix: bootstrap: Change log info when need to change user login shell

crmsh/sbd.py, crmsh/utils.py, test/unittests/test_sbd.py, test/unittests/test_utils.py
see #884
Consider the compatibility, in `has_stonith_running`, check if using diskless-sbd after check stonith device
=> Dev: ocfs2: Fix running ocfs2 stage on cluster with diskless-sbd

ChangeLog, setup.py
- Dev: update version setup.py
- Dev: ChangeLog: update for the recent releases
=> Update ChangeLog for release 4.4.0

crmsh/ui_resource.py, test/features/resource_set.feature, test/features/steps/step_implenment.py, test/testcases/resource.exp
=> [crmsh-4.1] Fix: ui_resource: Parse lifetime option correctly

crmsh/constants.py, crmsh/ui_node.py, crmsh/utils.py
To fix issue #910, avoid possible race condition
=> Dev: ui_node: Use diff and patch instead of replace cib

doc/website-v1/Makefile, doc/website-v1/documentation.adoc, doc/website-v1/index.adoc, doc/website-v1/man-4.3.adoc, doc/website-v1/news/2021-06-17-release-4_3_1.adoc, doc/website-v1/postprocess.py
- doc: Website: Upload crmsh 4.3.x doc
- doc: Website: Add 4.3.1 release note
=> crmsh.github.io website update

crmsh/bootstrap.py, crmsh/constants.py
=> Dev: bootstrap: the joining node retries an active cluster

crmsh/sbd.py, test/unittests/test_sbd.py
=> Fix: sbd: not overwrite SYSCONFIG_SBD and sbd-disk-metadata if input 'n'(bsc#1194870)

crmsh/utils.py, test/unittests/test_utils.py
=> [crmsh-4.3] medium: utils: update detect_cloud pattern for aws

crmsh/utils.py, test/unittests/test_utils.py
=> [crmsh-4.1] medium: utils: update detect_cloud pattern for aws

crmsh/cibconfig.py, crmsh/completers.py, crmsh/rsctest.py, crmsh/ui_configure.py, crmsh/ui_resource.py, crmsh/xmlutil.py, test/crm-interface, test/testcases/confbasic.exp, test/testcases/file.exp, test/testcases/resource.exp
=> [crmsh-4.3] Fix: xmlutil: Parse promotable clone correctly and also consider compatibility 

crmsh/bootstrap.py, crmsh/utils.py, test/unittests/test_bootstrap.py, test/unittests/test_utils.py
=> [crmsh-4.3]Dev: ocfs2: Fix running ocfs2 stage on cluster with diskless-sbd

crmsh/bootstrap.py, crmsh/ui_cluster.py, test/features/bootstrap_options.feature, test/features/qdevice_usercase.feature, test/features/steps/const.py, test/features/steps/step_implenment.py
=> [crmsh-4.3] bootstrap: Change default transport type as udpu

crmsh/utils.py
Backport from #971, to fix issue #970
=> [crmsh-4.3] Fix: utils: wait4dc: Make change since output of 'crmadmin -S' change

crmsh/report/constants.py, crmsh/report/core.py, crmsh/report/utillib.py
=> Fix: crm report: use sudo when under non root and hacluster user

crmsh/msg.py, crmsh/utils.py, hb_report/constants.py, hb_report/hb_report.in, hb_report/utillib.py
Changes:
- Add "sudo -u root" for other user
- Put info/warning/debug messages into stdout
- Suppress some unnecessary logs
=> [crmsh-4.3] Fix: crm report: use sudo when under non-root and hacluster user 

crmsh/bootstrap.py
=> [crmsh-4.3] Dev: bootstrap: Don't open mgmt port since it's deprecated

crmsh/parallax.py
=> [crmsh-4.3] Dev: parallax: Add strict option to avoid raise exception when set to False

test/features/steps/step_implementation.py
Not enough in some environments
=> Dev: behave: Increase wait time for resource started

crmsh/bootstrap.py
=> [crmsh-4.4] Dev: bootstrap: Don't open mgmt port since it's deprecated

Dockerfile, test/run-functional-tests, test/testcases/ra.exp
=> [crmsh-4.4] Dev: CI: crmsh-4.4 branch change to use opensuse/leap:15.4 as docker image

crmsh/cibconfig.py, crmsh/ui_configure.py
=> [crmsh-4.4] fix: configure: refresh cib before showing or modifying if no pending changes has been made (bsc#1202465)

crmsh/parallax.py, crmsh/ui_context.py, crmsh/utils.py
=> [crmsh-4.4] Fix: utils: raise exception when failed to run command remotely

crmsh/bootstrap.py, crmsh/log.py
=> [crmsh-4.4] Dev: log: print begin and end marker in different lines in status_long

crmsh/sbd.py, test/unittests/test_sbd.py
When sbd device already created, running `crm cluster init -s <sbd_device>`, that's on the interactive mode, but the existing sbd device will be overwritten
Check if the given sbd device already initialized, if on the interactive mode, ask user if overwrite, input 'n', no overwrite for sbd device
- sbd device already initialized BUT not configured in /etc/sysconfig/sbd
- Run `crm cluster init`, specify the same sbd device
- crmsh ask "SBD is already configured to use <device> - overwrite (y/n)?", input `n`
- Then this device will NOT be overwritten
- /etc/sysconfig/sbd will be configured (SBD_DEVICE=<device>)
- sbd device already initialized BUT not configured in /etc/sysconfig/sbd
- Run `crm cluster init -s <device>`, use -s to specify the same sbd device
- crmsh ask "SBD is already …
=> Fix: sbd: Ask if overwrite when given sbd device on interactive mode

crmsh/userdir.py
=> fix: userdir: race condition during directory creation

test/features/bootstrap_bugs.feature, test/features/steps/step_implementation.py
https://github.com/krig/parallax/issues/17
=> Dev: behave: Add functional test for parallax OSError: [Errno 24] Too many open files

Dockerfile, test/features/resource_set.feature
=> Dev: behave: Add functional test for tracing ra with specific directory

test/features/qdevice_validate.feature, test/run-functional-tests
To avoid such issue https://github.com/ClusterLabs/crmsh/actions/runs/3462549620/jobs/5781592295
=> Dev: behave: stop sshd.service in test case

.github/workflows/crmsh-ci.yml, test/run-functional-tests
=> Dev: run-functional-tests: get index of test case in github action

.github/workflows/crmsh-ci.yml
- actions/checkout@v3 to v3
- actions/setup-python@v2 to v4
- use ubuntu-20.04 instead of ubuntu-latest, see https://github.com/actions/setup-python/issues/544#issuecomment-1320295576
=> Dev: workflows: update actions version

.github/workflows/crmsh-ci.yml
=> [crmsh-4.4] Dev: workflows: update actions version

test/features/qdevice_validate.feature, test/run-functional-tests
=> [crmsh-4.4] Dev: behave: stop sshd.service in test case

crmsh/bootstrap.py, crmsh/constants.py, crmsh/qdevice.py
=> Dev: bootstrap: add timeout to wait_for_cluster and wait_for_resource

.github/workflows/crmsh-ci.yml
=> [crmsh-4.3] Dev: workflows: update actions version

crmsh/bootstrap.py, crmsh/ui_cluster.py, test/unittests/test_bootstrap.py
fix issue #1050 
- Dev: bootstrap: join process return immediately when joining itself
- Dev: unittest: Add unit test for previous commit
=> Dev: bootstrap: join process return immediately when joining itself

crmsh/bootstrap.py, crmsh/qdevice.py, crmsh/sbd.py, test/unittests/test_bootstrap.py, test/unittests/test_qdevice.py, test/unittests/test_sbd.py
=> [crmsh-4.4] Dev: qdevice: Refactor qdevice validation code

.github/workflows/crmsh-ci.yml, crmsh/bootstrap.py, crmsh/healthcheck.py, crmsh/main.py, crmsh/upgradeutil.py, crmsh/utils.py, data-manifest, test/crm-interface, test/features/healthcheck.feature, test/features/steps/step_implementation.py, test/run-functional-tests, test/unittests/test_healthcheck.py, test/unittests/test_upgradeuitl.py, test/unittests/test_utils.py
=> [crmsh-4.4] Fix: ha-cluster-join fails to add nodes to a existing cluster after the version update (bsc#1201785)

crmsh/cibconfig.py, crmsh/constants.py, crmsh/parse.py, crmsh/ra.py, crmsh/ui_resource.py, crmsh/utils.py, crmsh/xmlutil.py, test/features/resource_set.feature, test/testcases/acl.exp, test/testcases/bugs.exp, test/testcases/bundle.exp, test/testcases/commit.exp, test/testcases/confbasic-xml.exp, test/testcases/confbasic.exp, test/testcases/delete.exp, test/testcases/edit.exp, test/testcases/file.exp, test/testcases/newfeatures.exp, test/testcases/resource.exp, test/testcases/rset-xml.exp, test/testcases/rset.exp, test/unittests/test_parse.py, test/unittests/test_utils.py
=> [crmsh-4.4] Dev: parse: cli_to_xml: populate advised monitor/start/stop operations values 

.github/workflows/crmsh-ci.yml, data-manifest, test/features/bootstrap_sbd_normal.feature, test/features/cluster_api.feature, test/features/steps/step_implementation.py, test/features/steps/utils.py, test/run-functional-tests
Test cases include:
- Start and stop resource
- crm resource move
- crm configure show
- pacemaker ACL related operations
- crm --force node fence \<target_node\>
=> Dev: behave: Add functional test for cluster API

crmsh/report/utillib.py
=> [crmsh-4.4] Fix: report: Catch read exception

hb_report/utillib.py, test/features/qdevice_validate.feature
=> [crmsh-4.3] Fix: report: Catch read exception

.github/workflows/crmsh-ci.yml, hb_report/utillib.py
=> [crmsh-4.1] Fix: report: Catch read exception

crmsh/bootstrap.py, test/features/qdevice_validate.feature
=> [crmsh-4.3] Dev: qdevice: Adjust qdevice reload policy

crmsh/qdevice.py, test/unittests/test_qdevice.py
=> [crmsh-4.4] Dev: qdevice: Adjust qdevice reload policy

crmsh/healthcheck.py, crmsh/upgradeutil.py, crmsh/utils.py
=> [crmsh-4.4] Dev: upgradeutil: do not ask when running in a background process group

crmsh/report/utillib.py
=> Dev: report: 'crm report' to collect journal.log in microseconds

crmsh/ui_configure.py, doc/crm.8.adoc
=> Dev: ui_configure: Deprecate configure erase sub-command

Dockerfile, crmsh/ui_resource.py, test/docker_scripts.sh, test/features/bootstrap_options.feature, test/features/resource_set.feature, test/features/steps/step_implenment.py, test/features/steps/utils.py
=> [crmsh-4.3] Backport trace ra dir feature (more test cases)

Dockerfile, crmsh/report/collect.py, crmsh/ui_resource.py, crmsh/utils.py, test/features/crm_report_bugs.feature, test/features/resource_set.feature, test/features/steps/step_implementation.py
=> [crmsh-4.4] Backport trace ra dir feature (more test cases and enable crm report to collect)

crmsh.spec.in
=> Dev: spec: Requires parallax version 1.0.8

crmsh/ui_cluster.py
Hi,
It should be better like this no? Or at least apply for the replace.
Thanks!
=> replace 2&>1 by 2>&1 and swap with >/dev/null

crmsh/report/constants.py, crmsh/report/core.py, crmsh/report/utillib.py
- Use crmsh.utils.su_get_stdout_stderr instead of crmsh.utils.get_stdout_stderr
- Reuse crmsh.utils.check_ssh_passwd_need
- Remove unused codes
=> Fix: report: fix crm report regression

crmsh/bootstrap.py, test/features/bootstrap_init_join_remove.feature, test/features/steps/step_implementation.py, test/unittests/test_bootstrap.py
=> Swap hacluster ssh key with other nodes

ChangeLog, configure.ac, setup.py
And update the ChangeLog for crmsh 4.5.0-rc2
=> Bump crmsh version to 4.5.0

test/features/qdevice_setup_remove.feature
=> Dev: behave: Add more test cases for bug 1209193

crmsh/healthcheck.py, crmsh/upgradeutil.py, crmsh/utils.py
=> [crmsh-4.4] Dev: utils: Check passwordless between cluster nodes

crmsh/bootstrap.py, crmsh/cibconfig.py, crmsh/xmlutil.py
=> [crmsh-4.4] Fix: cibconfig: use any existing rsc_defaults set rather than create another one

crmsh/help.py
=> [crmsh-4.3] Fix: help: Long time to load and parse crm.8.adoc

.github/workflows/crmsh-ci.yml, test/features/bootstrap_options.feature, test/features/crm_report_bugs.feature, test/features/qdevice_setup_remove.feature, test/features/qdevice_usercase.feature, test/features/qdevice_validate.feature, test/features/steps/step_implementation.py, test/features/steps/utils.py, test/run-functional-tests
- Dev: behave: Add -q option for run-functional-tests to create qnetd-node
- Dev: behave: Create normal user that does not belong to the haclient group
- Dev: behave: Simulate Azure instance ssh environment; Set 'PermitRootLogin no' and 'PasswordAuthentication no' in sshd_config
- wrap crm cluster join command with '<user>@', and for the -N option, too
=> Dev: behave: Simulate Azure instance ssh environment

Dockerfile, crmsh.spec.in, crmsh/rsctest.py, test/features/crm_report_bugs.feature, test/features/resource_set.feature
To avoid possible regression for #1147, add more functional test cases:
- 'crm configure rsctest'
- 'crm script'
- 'crm history'
=> Add more functional tests for modules using parallax

crmsh/bootstrap.py
=> [crmsh-4.5] Dev: bootstrap: Configure ssh key when fetch geo config

crmsh/bootstrap.py, crmsh/ocfs2.py, crmsh/sbd.py, crmsh/ui_cluster.py, crmsh/utils.py, test/features/bootstrap_options.feature, test/features/bootstrap_sbd_normal.feature, test/unittests/test_bootstrap.py, test/unittests/test_ocfs2.py, test/unittests/test_sbd.py, test/unittests/test_utils.py, tox.ini
`CustomAppendAction` is a custom class for argparse append action:
- Flatten the value like '-s "/dev/sda1;/dev/sda2"'
- Detect duplicated input
=> Dev: ui_cluster: Use 'CustomAppendAction' instead of 'append' argparse action

crmsh/bootstrap.py, crmsh/ocfs2.py, crmsh/sbd.py, crmsh/ui_cluster.py, crmsh/utils.py, test/features/bootstrap_options.feature, test/features/bootstrap_sbd_normal.feature, test/unittests/test_bootstrap.py, test/unittests/test_ocfs2.py, test/unittests/test_sbd.py, test/unittests/test_utils.py
=> [crmsh-4.5] Dev: ui_cluster: Use 'CustomAppendAction' instead of 'append' argparse action

crmsh/ui_node.py
node standby / online had a race:
The current cib is queried ("base of change"), then manipulated to create,delete or change the values of, the "standby" nvpair(s). Then the current cib is queried *again* ("base of diff"), this time to be used as the "original", to produce a cib diff, which is then send to pacemaker to be applied.
Any changes to the cib between "base of change" and "base of diff" will be "rolled back", which can include master-scores, or operation results.
This has lead to attempted demotion of already stopped resources, resulting in spurious operation failures.
Fixed by using the same cib as basis for both the changes, and the diff. Currently this fix uses copy.deepcopy() on an already parsed cib object.
If someone feels like "optimizing" things, it would be more …
=> medium: ui_node: fix cib rollback race on node standby

crmsh/ui_node.py
=> [crmsh-4.5] medium: ui_node: fix cib rollback race on node standby

crmsh/ui_node.py
=> [crmsh-4.4] medium: ui_node: fix cib rollback race on node standby

.github/workflows/crmsh-ci.yml, codecov.yml, crmsh/bootstrap.py, crmsh/healthcheck.py, crmsh/ui_cluster.py, crmsh/upgradeutil.py, crmsh/utils.py, data-manifest, test/features/bootstrap_bugs.feature, test/features/coveragerc, test/features/environment.py, test/features/steps/behave_agent.py, test/features/steps/const.py, test/features/steps/step_implementation.py, test/features/steps/utils.py, test/run-functional-tests, test/testcases/resource.exp, test/unittests/test_bootstrap.py, test_container/Dockerfile, test_container/behave-agent.socket, test_container/behave-agent@.service, test_container/behave_agent.py
=> [crmsh-4.5] Backport #1194, #1205, and #1206

crmsh/corosync.py, test/features/crm_report_bugs.feature
=> [crmsh-4.5] Dev: corosync: Enable logging.to_logfile

codecov.yml, crmsh/prun/prun.py, crmsh/prun/runner.py, crmsh/upgradeutil.py, crmsh/utils.py, test/features/bootstrap_bugs.feature, test/features/steps/step_implementation.py, test/unittests/test_prun.py, test/unittests/test_utils.py
=> [crmsh-4.5] Fix: upgradeutil: reduce the timeout for getting sequence from remote node (bsc#1213797)

.github/workflows/crmsh-cd.yml, codecov.yml
=> [crmsh-4.5] Fix: github-actions: add condition to prevent crm-cd.yml running in a forked repo

test/run-functional-tests
=> add vim modeline to shell script run-functional-tests

.github/workflows/crmsh-cd.yml
Picked from #1242 
Disable them in crmsh-4.5
=> [crmsh-4.5] Dev: workflows: Enable delivery and submit CD stages for branch crmsh-4.6

crmsh/history.py, crmsh/report/utillib.py
backport #1257 
Fix regression after #1252
=> [crmsh-4.5] Fix: report: Pick up tarball suffix dynamically (bsc#1215438)

crmsh/history.py, crmsh/report/utillib.py
backport #1257 
Fix regression after #1251
=> [crmsh-4.4] Fix: report: Pick up tarball suffix dynamically (bsc#1215438)

crmsh/report/utillib.py, crmsh/utils.py, test/features/cluster_api.feature
=> [crmsh-4.5] Fix: utils: Add 'sudo' only when there is a sudoer(bsc#1215549)

crmsh/report/utillib.py, crmsh/utils.py, test/features/cluster_api.feature
=> Fix: utils: Add 'sudo' only when there is a sudoer(bsc#1215549)

crmsh/ui_cluster.py, crmsh/utils.py, test/features/bootstrap_bugs.feature, test/testcases/confbasic-xml.exp, test/testcases/confbasic.exp, test/testcases/file.exp, test/testcases/resource.exp, test/unittests/test_ui_cluster.py, test/unittests/test_utils.py
=> [crmsh-4.4] Fix: ui_cluster: Improve the process of 'crm cluster stop' (bsc#1213889)

crmsh/ui_corosync.py
=> [crmsh-4.6] Dev: ui_corosync: Add a completer for corosync.set to enumerate all current paths

crmsh/parallax.py
Guide users to setup passwordless authentications.
=> [crmsh-4.5] Fix: parallax: refine error message when parallax fails to perform passwordless authentication (bsc#1218940)

crmsh/cibconfig.py, crmsh/constants.py, crmsh/parse.py, crmsh/ui_configure.py, test/testcases/bundle.exp
- Add break lines at bundle container properties, port-mapping and storage-mapping #1303 
- Hide the id of port-mapping and storage-mapping #1302 
- Assign meaningful id to the bundle's port-mapping and storage-mapping
- Support podman #1317
=> [crmsh4.6] Enhance the configuration of the bundle

doc/website-v1/start-guide.adoc
Fix for https://github.com/ClusterLabs/crmsh/issues/1337
=> Fix cluster init example on the start guide.

crmsh/report/sh.py, crmsh/scripts.py, crmsh/sh.py, crmsh/term.py, crmsh/ui_node.py, crmsh/user_of_host.py, crmsh/utils.py, crmsh/xmlutil.py, test/unittests/test_sh.py
=> Fix: sh: pass env to child process explicitly (bsc#1205925)

crmsh/report/utillib.py, crmsh/scripts.py, crmsh/term.py, crmsh/ui_node.py, crmsh/utils.py, crmsh/xmlutil.py
=> [crmsh-4.4] Fix: sh: pass env to child process explicitly (bsc#1205925)

crmsh/bootstrap.py, crmsh/ui_cluster.py, crmsh/utils.py, test/features/steps/const.py, test/unittests/test_bootstrap.py, test/unittests/test_utils.py
- Dev: bootstrap: Refactor qdevice user parsing and finding
- Dev: ssh_key: Extract duplicate code about list keys from ssh-agent to a function
=> Minor refactoring for code duplication

crmsh/bootstrap.py, crmsh/ui_cluster.py, crmsh/utils.py, test/unittests/test_bootstrap.py, test/unittests/test_utils.py
Mostly backport #1351 , except the commit `Dev: Remove unused vgfs term from the code`
=> [crmsh-4.6] Minor refactoring for code duplication 

crmsh/bootstrap.py, test/features/ssh_agent.feature
=> [crmsh-4.6] Dev: bootstrap: Give a warning when detecting $SSH_AUTH_SOCK but not use --use-ssh-agent option

crmsh/bootstrap.py, crmsh/corosync.py, crmsh/ssh_key.py, test/unittests/test_bootstrap.py, test/unittests/test_corosync.py
=> [crmsh-4.6] Dev: qdevice: Add all nodes' keys to qnetd authorized_keys

crmsh/constants.py, crmsh/ui_context.py, doc/toolchain/bin/adocxt, doc/website-v1/man-4.6.adoc
=> Dev: ui_context: ignore requirements when option --help is specified

crmsh/bootstrap.py, crmsh/corosync.py
to check if the corosync.conf is valid or not
=> Dev: corosync: Add corosync.is_valid_corosync_conf function

contrib/bash_completion.sh, crmsh/main.py
=> [crmsh-4.6] Enhance completion at non-interactive mode

doc/toolchain/bin/adocxt, doc/website-v1/man-4.6.adoc
=> Fix: doc/toolchain: fix missing anchor in generated AIO doc (#1409)

crmsh/constants.py, crmsh/corosync.py, crmsh/ui_corosync.py, doc/crm.8.adoc
=> Dev: corosync: Show corosync cpg status in `crm corosync status cpg`

crmsh/bootstrap.py, crmsh/constants.py, crmsh/crash_test/check.py, scripts/health/collect.py, test/unittests/test_crashtest_check.py, utils/crm_init.py
- Drop SuSEfirewall2 support
- bootstrap: open corosync ports in firewalld
=> Fix: bootstrap: open corosync ports in firewalld

crmsh/utils.py, test/unittests/test_utils.py
=> [crmsh-4.6] Dev: utils: Add info when property is newly added

crmsh/utils.py, test/unittests/test_utils.py
=> [crmsh-4.5] Dev: utils: Add info when property is newly added

crmsh/crash_test/task.py, crmsh/crash_test/utils.py, crmsh/ui_node.py
=> [crmsh-4.6] Dev: log an error when fencing node without stonith device configured and running

crmsh/config.py, test/features/resource_set.feature, test/testcases/confbasic-xml.exp, test/testcases/confbasic.exp
Then deprecated 'Master' and 'Slave' in command line will be converted to 'Promoted' and 'Unpromoted' automatically
=> Dev: config: Set OCF_1_1_SUPPORT to yes (jsc#PED-8550)

.github/workflows/crmsh-cd.yml, .github/workflows/crmsh-ci.yml, README.md, codecov.yml, tox.ini
* update runners to ubuntu 24.04
* update actions/checkout to v4
* update codecov@codecov-actions to v4
* and specify token as required in [Breaking Changes](https://github.com/codecov/codecov-action/blob/679cd7bee6931c6a12ddbd91ca3b186f3b90d406/README.md#breaking-changes)
and also:
* upload the coverage data of unit tests to codecov
* add codecov badge to README.md
close #1431
=> Dev: github-actions: update to v4 (#1431)

crmsh/ui_resource.py
When running crm resource promote/demote, set role as Promoted/Unpromoted
=> Dev: ui_resource: Set role as Promoted/Unpromoted when promote/demote (jsc#PED-8550)

.github/workflows/crmsh-ci.yml, codecov.yml, crmsh/ui_corosync.py, crmsh/utils.py, data-manifest, test/features/corosync_ui.feature
- corosync.show: validate corosync.conf before showing it
- corosync.edit: edit a temporary copy of corosync.conf, validate it before saving it,
then give the user hints on how to sync to other nodes
- Add corosync_ui.feature to collect test cases for crm corosync ui
=> Dev: ui_corosync: Improve corosync.show and corosync.edit subcommands

crmsh/upgradeutil.py
=> Fix: upgradeutil: refine error handling (bsc#1226147, bsc#1223371)

crmsh/upgradeutil.py
Getting upgrade seq from remote node may fails for various reasons. Previous code handles SSH problems gracefully but other problems are note handled and turn into misleading error messages.
This commit handles those problems in the same way in which SSH problems are handled: output detail information to debug log and skip upgrading.
=> [crmsh-4.5] Fix: upgradeutil: refine error handling (bsc#1226147, bsc#1223371)

crmsh/ra.py
=> [crmsh-4.6] Dev: ra: Guess stonith class type when using fence agents

.github/workflows/crmsh-cd.yml, .github/workflows/crmsh-ci.yml
=> Fix: github-actions: should pass secrets to reusable workflows

scripts/lvm/main.yml, templates/virtual-ip, test/testcases/bugs.exp, test/testcases/ra, test/testcases/ra.exp, test/testcases/scripts.exp, test_container/Dockerfile
- Dev: Dockerfile: Update dockerfile after corosync3 is in the Factory
- Dev: testcases: Replace IPaddr with IPaddr2
- Dev: testcases: Replace LVM with LVM-activate
=> Dev: Dockerfile: Update dockerfile after corosync3 is in the Factory

crmsh/cibconfig.py, crmsh/constants.py, crmsh/ui_assist.py, crmsh/ui_configure.py, crmsh/ui_context.py, crmsh/ui_maintenance.py, crmsh/xmlutil.py
=> [crmsh-4.6] Dev: refine change detection for crm configure (#1466)

crmsh/utils.py, scripts/health/collect.py, utils/crm_rpmcheck.py
This PR continues the #1497 . Additionally to the package information also the system information is read from ansible.
=> Dev: scripts/health/collect: use ansible to get sysinfo

crmsh/report/collect.py, crmsh/sh.py, test/unittests/test_report_collect.py, test/unittests/test_sh.py
=> Fix: report: crm report will hang if CIB contains invalid configuraions (bsc#1229686)

Dockerfile, crmsh/cibverify.py, crmsh/msg.py, test/crm-interface, test/docker_scripts.sh, test/testcases/common.excl
- Fix: msg: Redirect info messages to stdout (bsc#1229027)
- Fix: cibverify: give warning if crm_verify return warning(bsc#1122391)
- Update for dockerfile and docker run option
=> [crmsh-4.1] Fix: msg: Redirect info messages to stdout (bsc#1229027)

.github/workflows/crmsh-ci.yml, codecov.yml, crmsh/config.py, crmsh/constants.py, crmsh/main.py, crmsh/report/core.py, crmsh/ui_cluster.py, crmsh/upgradeutil.py, crmsh/user_of_host.py, crmsh/utils.py, data-manifest, etc/crm.conf.in, test/features/cluster_blocking_ssh.feature, test/unittests/test_report_core.py
port #1508 , also add functional test for ssh blocking case
=> [crmsh-4.6] Fix: Raise an exception as a rapid return of ssh-related operations to prevent hang (bsc#1228899)

.github/workflows/crmsh-ci.yml, codecov.yml, data-manifest, test/features/cluster_blocking_ssh.feature, test/features/steps/step_implementation.py
Add functional test for ssh blocking case for PR #1508
=> [crmsh-4.5] Dev: behave: Add functional test for ssh blocking case

crmsh/completers.py, crmsh/prun/prun.py, crmsh/scripts.py, crmsh/utils.py, test/features/user_access.feature
=> Fix: hawk2 cannot call crm script as user hacluster (bsc#1228271)

crmsh/prun/prun.py, crmsh/scripts.py, crmsh/utils.py, test/features/user_access.feature
=> [crmsh-4.5] Fix: hawk2 cannot call crm script as user hacluster (bsc#1228271)

crmsh/bootstrap.py, crmsh/utils.py, test/unittests/test_bootstrap.py, test/unittests/test_utils.py
=> Fix: bootstrap: ssh public key should be copied to qnetd node when ssh-agent feature is not enabled (bsc#1228950)

.github/workflows/crmsh-ci.yml, codecov.yml, crmsh/config.py, crmsh/constants.py, crmsh/main.py, crmsh/report/core.py, crmsh/ui_cluster.py, crmsh/upgradeutil.py, crmsh/user_of_host.py, crmsh/utils.py, data-manifest, etc/crm.conf.in, test/features/cluster_blocking_ssh.feature, test/unittests/test_report_core.py
port #1508 , also add functional test for ssh blocking case
=> Fix: Raise an exception as a rapid return of ssh-related operations to prevent hang (bsc#1228899)

crmsh/ui_configure.py, crmsh/ui_node.py, crmsh/utils.py, test/features/configure_bugs.feature, test/features/steps/step_implementation.py
=> [crmsh-4.6] Dev: utils: Load CIB_file env before some readonly commands

crmsh/ui_node.py
=> [crmsh-4.6] Dev: ui_node: Improve command 'clearstate <node>'

crmsh/utils.py
=> [crmsh-4.6] Dev: utils: Catch PermissionError when reading files

.github/workflows/crmsh-ci.yml, codecov.yml, crmsh/healthcheck.py, crmsh/report/core.py, crmsh/scripts.py, crmsh/ui_cluster.py, data-manifest, test/features/healthcheck.feature
for checking and fixing paswordless ssh authentication for user hacluster.
=> [crmsh-4.5] Dev: ui_cluster: add subcommand 'crm cluster health hawk2 [--fix]' (bsc#1228899)

crmsh/bootstrap.py, crmsh/ui_cluster.py, test/unittests/test_bootstrap.py
- Dev: bootstrap: Enhance log clarity during crm cluster remove process
- Dev: completers: Reuse node completer for cluster remove and health
=> Improve cluster remove

crmsh/bootstrap.py, crmsh/ui_cluster.py, test/unittests/test_bootstrap.py
=> [crmsh-4.6] Improve cluster remove

crmsh/bootstrap.py, test/unittests/test_bootstrap.py
=> [crmsh-4.5] Fix: bootstrap: check is_nologin more robustly (bsc#1228251)

crmsh/healthcheck.py, crmsh/ui_cluster.py
=> [crmsh-4.6] Minor improve for cluster health

crmsh/bootstrap.py, crmsh/qdevice.py, crmsh/report/core.py, crmsh/ui_node.py, crmsh/utils.py, test/features/crm_report_normal.feature, test/unittests/test_qdevice.py, test/unittests/test_report_core.py, test/unittests/test_utils.py
=> [crmsh-4.6] Dev: utils: Check node is reachable by using both ping and ssh

crmsh/cibconfig.py, crmsh/config.py, etc/crm.conf.in, test/run-functional-tests
=> [crmsh-4.4] Fix: cibconfig: Disable auto add advise values for operations (bsc#1231386)

crmsh/bootstrap.py
=> [crmsh-4.5] Dev: bootstrap: Add log info when starting pacemaker.service

.github/workflows/test-container-image.yml, test/run-functional-tests, test_container/Dockerfile
This pull request add a new action to build and push the test container image automatically, when the image definition changes.
=> Dev: github-actions: build and push test container image automatically

.github/workflows/test-container-image.yml
so that we will catch up with the updates from tumbleweed
=> Dev: github-actions: rebuild the test container image weekly

crmsh/log.py
Combine "filter_report" and "filter" into one filter
Fix issue #1607
=> Fix: log: The report DEBUG log message is not displayed in the log file

crmsh/log.py
=> [crmsh-4.6] Fix: log: The report DEBUG log message is not displayed in the log file

crmsh/bootstrap.py, crmsh/utils.py
=> [crmsh-4.6] Dev: bootstrap: more robust implementation for ssh_merge (bsc#1230530)

crmsh/report/utils.py
=> [crmsh-4.6] Fix: report: Fix a regression for irregular file collection

crmsh/config.py, crmsh/report/collect.py, crmsh/report/core.py, crmsh/report/utils.py, etc/crm.conf.in, test/unittests/test_report_collect.py, test/unittests/test_report_core.py
=> [crmsh-4.6] Collect ~/.config/crm/crm.conf in crm report result

crmsh/ui_resource.py, doc/crm.8.adoc, test/features/resource_failcount.feature
- Enable set failcount for resource operation when there is no failcount
entry
- Improve readability of code
- Add functional test cases to increase coverage
=> Dev: ui_resource: Refine 'do_failcount' function

crmsh/ui_resource.py, doc/crm.8.adoc, test/features/resource_failcount.feature
=> [crmsh-4.6] Dev: ui_resource: Refine 'do_failcount' function

crmsh/ui_resource.py, doc/crm.8.adoc, test/features/resource_failcount.feature
=> [crmsh-4.5] Dev: ui_resource: Refine 'do_failcount' function

crmsh/ui_resource.py, doc/crm.8.adoc, test/features/resource_failcount.feature
=> [crmsh-4.4] Dev: ui_resource: Refine 'do_failcount' function

test/unittests/test_report_utils.py
=> [crmsh-4.6] Dev: unittests: Rewrite test_findln_by_timestamp by using fixed date

crmsh/bootstrap.py, test/unittests/test_bootstrap.py
=> [crmsh-4.6] Fix: bootstrap: Improve sync_files_to_disk function (bsc#1219537)

crmsh/ui_context.py
=> [crmsh-4.6] Fix: ui_context: crmsh still complete even for unknown command

crmsh/bootstrap.py, crmsh/ui_cluster.py, test/unittests/test_bootstrap.py
=> Dev: bootstrap: Check if core packages like corosync/pacemaker are installed

crmsh/bootstrap.py, crmsh/ui_cluster.py, test/unittests/test_bootstrap.py
=> [crmsh-4.6] Dev: bootstrap: Check if core packages like corosync/pacemaker are installed

crmsh/command.py, crmsh/ui_configure.py
To complete existing pacemaker-*.rng files under /usr/share/pacemaker directory
backport #1677
=> [crmsh-4.6] Dev: ui_configure: Add completer for 'configure schema' command

crmsh/ui_configure.py, crmsh/ui_context.py, crmsh/utils.py
=> [crmsh-4.6] Dev: Add cancel option when confirming to commit for the pending changes

crmsh/cibconfig.py, crmsh/schema.py, crmsh/ui_configure.py, doc/crm.8.adoc, test/features/configure_bugs.feature, test/features/steps/step_implementation.py
=> [crmsh-4.6] Improve `configure schema` command

crmsh/bootstrap.py, crmsh/service_manager.py, crmsh/ui_cluster.py, test/unittests/test_ui_cluster.py
=> [crmsh-4.6] Dev: Add error log when cluster services fail to start

codecov.yml, crmsh/migration.py
and advise to replace it with "fence_sbd".
=> [crmsh-4.6] Dev: pre-migration: report "cannot migrate" if using external_sbd (jsc#PED-11808)

crmsh/cluster_fs.py, test/features/gfs2.feature, test/features/ocfs2.feature
=> [crmsh-4.6] Change default DLM RA name

crmsh/utils.py
Avoid get empty options in else case
=> Dev: utils: Add parentheses to if else statements

crmsh/utils.py
Avoid get empty options in else case
backport #1698
=> [crmsh-4.6] Dev: utils: Add parentheses to if else statements

crmsh/config.py, crmsh/utils.py, etc/crm.conf.in, test/unittests/test_utils.py
- Dev: etc: Drop OCF_1_1_SUPPORT option in crm.conf
- Dev: utils: Ignore config.core.OCF_1_1_SUPPORT option
=> Drop OCF_1_1_SUPPORT option in crm.conf (jsc#PED-8550)

crmsh/cibconfig.py, crmsh/ui_configure.py, doc/crm.8.adoc, test/features/configure_bugs.feature, test/features/steps/step_implementation.py
backport from #1701 #1705 #1710
=> [crmsh-4.6] Dev: ui_configure: Improve 'configure upgrade' command

test/features/configure_bugs.feature, test/features/steps/step_implementation.py
- Dev: behave: Adjust test case for 'configure schema'
- Dev: behave: Add test case for 'configure upgrade' command
=> Dev: behave: Add test case for 'configure upgrade' command

test/features/steps/const.py, test/testcases/edit.exp, test/testcases/shadow.exp
We can revert this commit if the test is under python3.11
=> Dev: behave: const: Update output of argparse metavar under python3.13

crmsh/ui_resource.py, doc/crm.8.adoc, test/testcases/resource.exp
=> [crmsh-4.6] Dev: ui_resource: Refactor do_trace function

crmsh/ui_corosync.py
Fix #1546 
> 1. Completer of crm corosync link remove not works
=> Dev: ui_corosync: fix completer for link remove

crmsh.spec.in, crmsh/bootstrap.py, crmsh/report/constants.py, doc/website-v1/development.adoc, scripts/health/collect.py, test/features/bootstrap_init_join_remove.feature, test/features/steps/step_implementation.py, utils/crm_init.py
- Dev: bootstrap: Drop /var/lib/heartbeat in source code (jsc#PED-8733)
- Dev: Drop cluster-glue in multiple places (jsc#PED-8733)
- Dev: behave: Adjust functional tests to replace /var/lib/heartbeat
=> Dev: Drop cluster-glue in multiple places (jsc#PED-8733)

test_container/Dockerfile
And don't install python setuptools
=> Dev: Dockerfile: Install python build

Makefile.am
to build and install the package.
=> Dev: Makefile: Use modern tools python build and pip instead of setup.py

contrib/bash_completion.sh, crmsh/command.py
=> [crmsh-4.6] Dev: bash_completion.sh: Add nosort option to disable sorting

crmsh/report/core.py, crmsh/ui_node.py, crmsh/utils.py, test/unittests/test_report_core.py, test/unittests/test_utils.py
=> [crmsh-4.6] Dev: Refactored node reachability handling in multiple modules

crmsh/cibconfig.py, crmsh/ra.py, test/unittests/test_bugs.py
=> [crmsh-4.6] Dev: cibconfig: Use VerifyResult to define the return value of sanity check related functions 

crmsh/cibconfig.py, crmsh/ui_configure.py
=> [crmsh-4.6] Dev: ui_configure: Show the changes with diff like format

crmsh/main.py
=> [crmsh-4.6] Dev: main: Ignore crm flag option to get completion

test/features/bootstrap_bugs.feature
=> [crmsh-4.6] Dev: behave: Fix cross-network isolation issue

.github/workflows/crmsh-cd.yml, .github/workflows/crmsh-ci.yml, test/features/bootstrap_bugs.feature
=> [crmsh-4.5] Dev: workflows: Update CI image on github action 

.github/workflows/crmsh-ci.yml, test/features/bootstrap_bugs.feature, test/unittests/test_bootstrap.py, test/unittests/test_qdevice.py
=> [crmsh-4.4] Dev: workflows: Update CI image on github action

test/features/bootstrap_sbd_delay.feature
=> Dev: behave: Adjust related timeout values after removing pcmk_delay_max

crmsh/report/collect.py
to avoid potential race conditions
=> [crmsh-4.5] Fix: report: Don't collect cib.txt separately (bsc#1243498)

crmsh/bootstrap.py, test/features/bootstrap_options.feature
=> [crmsh-4.6] Dev: bootstrap: Improve configuration for admin IP

.github/workflows/crmsh-ci.yml, codecov.yml, crmsh/cibconfig.py, data-manifest, test/features/pacemaker_remote.feature, test/features/steps/step_implementation.py, test/run-functional-tests
=> [crmsh-4.6] Dev: cibconfig: Prevent adding Pacemaker remote resources to groups, orders, or colocations

test/run-functional-tests
=> Dev: run-functional-tests: Fetch container's IP address correctly

crmsh/log.py
=> [crmsh-4.6] Fix: log: Improve function confirm's logic (bsc#1245386)

crmsh/log.py
=> [crmsh-4.5] Fix: log: Improve function confirm's logic (bsc#1245386)

crmsh/ui_cluster.py, crmsh/ui_node.py, crmsh/utils.py, test/features/bootstrap_init_join_remove.feature, test/unittests/test_utils.py
=> [crmsh-4.6] Dev: ui_cluster: Enhance membership validation

crmsh/sbd.py, crmsh/utils.py, test/features/bootstrap_sbd_delay.feature, test/unittests/test_sbd.py
=> [crmsh-4.6] Dev: sbd: Remove pcmk_delay_max while cacaulating stonith timeout value

crmsh/ui_context.py
=> Fix: ui_context: should not require root privilege when using subcommand 'help'

crmsh/command.py
Fix issue [Completion shows help topic but can't run](https://github.com/ClusterLabs/crmsh/issues/1878)
=> Dev: command: Show help topic completion only at root level

crmsh/bootstrap.py, test/unittests/test_bootstrap.py
This is unnecessary after commit b38e92f7
=> Dev: bootstrap: No need to remove /var/lib/crmsh

test/run-functional-tests
It will be convenient to terminate the testcase manually.
=> Dev: run-functional-tests: Add -i option for podman exec command to support interactive mode

Makefile, crmsh.spec.in, doc/Makefile, doc/toolchain/lib/help2adoc/parser.py
=> Dev: packaging: add `--help` text of all subcommands to the man page

crmsh/ui_cluster.py
=> [crmsh-5.0] Fix: ui_cluster: Call crm report directly for the legacy `crm cluster health` command (bsc#1230324)
